targets:
  $default:
    builders:
      foxy:foxy_entity:
        generate_for:
          - lib/entity/**_entity.dart
      foxy:foxy_filter_entity:
        generate_for:
          - lib/entity/**_entity.dart

builders:
  foxy_entity:
    import: "package:foxy/infrastructure/codegen/builder.dart"
    builder_factories: ["foxyEntityBuilder"]
    build_extensions:
      ".dart": [".foxy_entity.g.part"]
    auto_apply: root_package
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  foxy_filter_entity:
    import: "package:foxy/infrastructure/codegen/builder.dart"
    builder_factories: ["foxyFilterEntityBuilder"]
    build_extensions:
      ".dart": [".filter.g.dart"]
    auto_apply: root_package
    build_to: source
