name: foxy_workspace
description: "Foxy monorepo workspace — AzerothCore 数据库可视化工具及其代码生成器。"
publish_to: none

environment:
  sdk: ^3.9.2

workspace:
  - packages/foxy
  - packages/foxy_annotation
  - packages/foxy_generator
  - packages/foxy_lint
