export const SEARCH_CREATURE_TEMPLATES = "SEARCH_CREATURE_TEMPLATES";
export const COUNT_CREATURE_TEMPLATES = "COUNT_CREATURE_TEMPLATES";
export const PAGINATE_CREATURE_TEMPLATES = "PAGINATE_CREATURE_TEMPLATES";
export const FIND_CREATURE_TEMPLATE = "FIND_CREATURE_TEMPLATE";
export const SEARCH_ITEM_TEMPLATES = "SEARCH_ITEM_TEMPLATES";
export const COUNT_ITEM_TEMPLATES = "COUNT_ITEM_TEMPLATES";
export const PAGINATE_ITEM_TEMPLATES = "PAGINATE_ITEM_TEMPLATES";
export const FIND_ITEM_TEMPLATE = "FIND_ITEM_TEMPLATE";
