export const SEARCH_CREATURE_TEMPLATES = "SEARCH_CREATURE_TEMPLATES";
export const COUNT_CREATURE_TEMPLATES = "COUNT_CREATURE_TEMPLATES";
export const PAGINATE_CREATURE_TEMPLATES = "PAGINATE_CREATURE_TEMPLATES";
