// global
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const SET_ACTIVE = "SET_ACTIVE";
// creature
export const UPDATE_CREATURE_TEMPLATE_CREDENTIAL_ENTRY = "UPDATE_CREATURE_TEMPLATE_CREDENTIAL_ENTRY";
export const UPDATE_CREATURE_TEMPLATE_CREDENTIAL_NAME = "UPDATE_CREATURE_TEMPLATE_CREDENTIAL_NAME";
export const UPDATE_CREATURE_TEMPLATE_CREDENTIAL_SUBNAME = "UPDATE_CREATURE_TEMPLATE_CREDENTIAL_SUBNAME";
export const SEARCH_CREATURE_TEMPLATES = "SEARCH_CREATURE_TEMPLATES";
export const COUNT_CREATURE_TEMPLATES = "COUNT_CREATURE_TEMPLATES";
export const PAGINATE_CREATURE_TEMPLATES = "PAGINATE_CREATURE_TEMPLATES";
export const FIND_CREATURE_TEMPLATE = "FIND_CREATURE_TEMPLATE";
// game object
export const SEARCH_GAME_OBJECT_TEMPLATES = "SEARCH_GAME_OBJECT_TEMPLATES";
// item
export const SEARCH_ITEM_TEMPLATES = "SEARCH_ITEM_TEMPLATES";
export const COUNT_ITEM_TEMPLATES = "COUNT_ITEM_TEMPLATES";
export const PAGINATE_ITEM_TEMPLATES = "PAGINATE_ITEM_TEMPLATES";
export const FIND_ITEM_TEMPLATE = "FIND_ITEM_TEMPLATE";
export const SEARCH_ITEM_TEMPLATE_LOCALES = "SEARCH_ITEM_TEMPLATE_LOCALES";
export const STORE_ITEM_TEMPLATE_LOCALE = "STORE_ITEM_TEMPLATE_LOCALE";
export const DESTROY_ITEM_TEMPLATE_LOCALE = "DESTROY_ITEM_TEMPLATE_LOCALE";
// quest
export const SEARCH_QUEST_TEMPLATES = "SEARCH_QUEST_TEMPLATES";
// smart script
export const SEARCH_SMART_SCRIPTS = "SEARCH_SMART_SCRIPTS";
