// ignore_for_file: depend_on_referenced_packages, experimental_member_use

import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'package:foxy_annotation/repository_annotations.dart';
import 'list_model.dart';
import 'naming.dart';

const _fullEntityChecker = TypeChecker.fromUrl(
  'package:foxy_annotation/entity_annotations.dart#FoxyFullEntity',
);
const _fullFieldChecker = TypeChecker.fromUrl(
  'package:foxy_annotation/entity_annotations.dart#FoxyFullField',
);
const _repositoryChecker = TypeChecker.fromUrl(
  'package:foxy_annotation/repository_annotations.dart#FoxyRepository',
);
const _filterChecker = TypeChecker.fromUrl(
  'package:foxy_annotation/repository_annotations.dart#FoxyFilter',
);

/// Parses `@FoxyListViewModel`.
///
/// Query-layer methods are called directly by naming convention:
/// `getBrief<Base>s` / `count<Base>s` / `copy<Base>` / `destroy<Base>`.
/// These are fully generated by the Repository generator (query-layer
/// repositories); a hand-written shell's `@override` replaces the generated
/// version while the method name stays the same — signature mismatches
/// surface as compiler errors, the generator does no source-text matching.
final class ListReader {
  const ListReader();

  Future<ListGenerationModel> read(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) async {
    if (element is! ClassElement) {
      _fail(
        '@FoxyListViewModel 只能标注 ViewModel class。',
        element,
        '把注解移动到具体 List ViewModel class。',
      );
    }
    final className = element.name;
    if (className == null || !className.endsWith('ListViewModel')) {
      _fail(
        '@FoxyListViewModel 只能标注以 ListViewModel 结尾的 class。',
        element,
        '使用具体 List ViewModel class。',
      );
    }

    final inputFileName = buildStep.inputId.pathSegments.last;
    final expectedFileName = '${toSnakeCase(className)}.dart';
    if (inputFileName != expectedFileName) {
      _fail(
        '$className 必须位于 $expectedFileName，当前文件是 $inputFileName。',
        element,
        '让 ViewModel class 与文件名保持一致。',
      );
    }

    final entityElement = _readEntity(annotation, className, element);
    final repositoryElement = _readRepository(
      annotation,
      className,
      entityElement,
      element,
    );
    final repositoryClassName = repositoryElement.name!;

    final baseName = repositoryClassName.substring(
      0,
      repositoryClassName.length - 'Repository'.length,
    );
    final filterClassName = '${baseName}Filter';

    final fields = _readFilterFields(
      repositoryElement,
      filterClassName,
      element,
    );

    final keyType = _readEntityKeyType(entityElement, element);
    final mixinName = '_${className}Mixin';
    final source = await buildStep.readAsString(buildStep.inputId);
    final partName = inputFileName.replaceFirst(RegExp(r'\.dart$'), '.g.dart');
    if (!source.contains("part '$partName';") &&
        !source.contains('part "$partName";')) {
      _fail(
        '$className 缺少 part \'$partName\';。',
        element,
        '在 ViewModel imports 后声明生成 part。',
      );
    }
    if (!RegExp(
      'class\\s+$className\\s+with\\s+[^\\{;]*\\b$mixinName\\b',
    ).hasMatch(source)) {
      _fail(
        '$className 必须混入 $mixinName。',
        element,
        '把 $mixinName 添加到 ViewModel 的 with 列表末尾。',
      );
    }
    final withList = RegExp(
      'class\\s+$className\\s+with\\s+([^\\{;]*)',
    ).firstMatch(source)?.group(1);
    if (withList != null) {
      final parts = withList.split(',').map((part) => part.trim()).toList();
      final controllerIndex = parts.indexOf('FieldControllerMixin');
      final queryIndex = parts.indexOf('QueryVersionMixin');
      final mixinIndex = parts.indexOf(mixinName);
      if (controllerIndex < 0 || queryIndex < 0) {
        _fail(
          '$className 必须混入 FieldControllerMixin 与 QueryVersionMixin。',
          element,
          '把 FieldControllerMixin, QueryVersionMixin 添加到 with 列表。',
        );
      }
      if (controllerIndex > mixinIndex || queryIndex > mixinIndex) {
        _fail(
          'FieldControllerMixin / QueryVersionMixin 必须在 $mixinName 之前。',
          element,
          '调整 with 顺序：FieldControllerMixin, QueryVersionMixin, ..., $mixinName。',
        );
      }
    }

    return ListGenerationModel(
      className: className,
      entityClassName: entityElement.name!,
      briefEntityClassName: 'Brief${baseName}Entity',
      repositoryClassName: repositoryClassName,
      mixinName: mixinName,
      fields: List.unmodifiable(fields),
      getBriefMethodName: 'getBrief${pluralize(baseName)}',
      countMethodName: 'count${pluralize(baseName)}',
      copyMethodName: 'copy$baseName',
      keyType: keyType,
    );
  }

  InterfaceElement _readEntity(
    ConstantReader annotation,
    String className,
    Element element,
  ) {
    final entityType = annotation.read('entity').typeValue;
    if (entityType is! InterfaceType) {
      _fail(
        '$className 的 @FoxyListViewModel 参数不是 Entity class。',
        element,
        '传入具体的 Full Entity 类型。',
      );
    }
    final entityElement = entityType.element;
    if (!entityElement.name!.endsWith('Entity')) {
      _fail('$className 绑定的类型必须以 Entity 结尾。', element, '传入具体的 Full Entity 类型。');
    }
    final entityAnnotations = _fullEntityChecker
        .annotationsOf(entityElement)
        .toList();
    if (entityAnnotations.length != 1) {
      _fail(
        '${entityElement.name} 必须且只能声明一个 @FoxyFullEntity。',
        entityElement,
        '只绑定已迁移的生成型 Full Entity。',
      );
    }
    return entityElement;
  }

  InterfaceElement _readRepository(
    ConstantReader annotation,
    String className,
    InterfaceElement entityElement,
    Element element,
  ) {
    final repositoryType = annotation.read('repository').typeValue;
    if (repositoryType is! InterfaceType) {
      _fail(
        '$className 的 @FoxyListViewModel 参数不是 Repository class。',
        element,
        '传入具体的 Repository 类型。',
      );
    }
    final repositoryElement = repositoryType.element;
    final repositoryClassName = repositoryElement.name!;
    if (!repositoryClassName.endsWith('Repository')) {
      _fail(
        '$className 绑定的类型必须以 Repository 结尾。',
        element,
        '传入具体的 Repository 类型。',
      );
    }
    final entityBaseName = entityElement.name!.substring(
      0,
      entityElement.name!.length - 'Entity'.length,
    );
    final repositoryBaseName = repositoryClassName.substring(
      0,
      repositoryClassName.length - 'Repository'.length,
    );
    if (repositoryBaseName != entityBaseName) {
      _fail(
        '$repositoryClassName 与 ${entityElement.name} 不符合一对一命名约定。',
        element,
        'Repository 和 Entity 使用相同 base name。',
      );
    }
    final repositoryAnnotations = _repositoryChecker
        .annotationsOf(repositoryElement)
        .toList();
    if (repositoryAnnotations.length != 1) {
      _fail(
        '$repositoryClassName 必须且只能声明一个 @FoxyRepository。',
        repositoryElement,
        '只绑定已迁移的生成型 Repository。',
      );
    }
    final boundEntityName = ConstantReader(
      repositoryAnnotations.single,
    ).read('entity').typeValue.element?.name;
    if (boundEntityName != entityElement.name) {
      _fail(
        '$repositoryClassName 的 @FoxyRepository 绑定的实体是 '
            '$boundEntityName，与注解传入的 ${entityElement.name} 不一致。',
        element,
        '让 @FoxyListViewModel 的 repository 与 entity 匹配。',
      );
    }
    return repositoryElement;
  }

  List<ListFilterFieldModel> _readFilterFields(
    InterfaceElement repositoryElement,
    String filterClassName,
    Element element,
  ) {
    final fields = <ListFilterFieldModel>[];
    final names = <String>{};
    for (final object in _filterChecker.annotationsOf(repositoryElement)) {
      final reader = ConstantReader(object);
      final name = reader.read('name').stringValue;
      if (!names.add(name)) {
        _fail(
          '$filterClassName 重复声明字段 $name。',
          element,
          '确保每个 @FoxyFilter 字段名唯一。',
        );
      }
      if (!RegExp(r'^[a-z][A-Za-z0-9]*_?$').hasMatch(name)) {
        _fail(
          '$filterClassName 的字段名 $name 不是合法 lowerCamelCase 标识符。',
          element,
          '使用 lowerCamelCase；Dart 保留字允许追加单个下划线。',
        );
      }
      final typeIndex = reader
          .read('type')
          .objectValue
          .getField('index')
          ?.toIntValue();
      final type =
          typeIndex != null &&
              typeIndex >= 0 &&
              typeIndex < FoxyFilterType.values.length
          ? FoxyFilterType.values[typeIndex]
          : null;
      if (type != FoxyFilterType.text) {
        _fail(
          '$filterClassName.$name 的筛选类型是 ${type?.name ?? '未知'}。',
          element,
          'List ViewModel 当前只支持 @FoxyFilter.text 文本筛选字段；'
              '移除该筛选或改用 text。',
        );
      }
      fields.add(ListFilterFieldModel(name: name));
    }
    return fields;
  }

  /// Infers the Key type from the entity's `@FoxyFullField(key: true)`: a
  /// single key is the field type, a composite key is `XxxKey` (a generated
  /// class; only its name is inferable).
  String _readEntityKeyType(InterfaceElement entityElement, Element element) {
    final keyFieldTypes = <String>[];
    for (final field in entityElement.fields.where(
      (field) => !field.isStatic && !field.isSynthetic,
    )) {
      final annotations = _fullFieldChecker.annotationsOf(field).toList();
      if (annotations.length != 1) continue;
      if (!(ConstantReader(annotations.single).peek('key')?.boolValue ??
          false)) {
        continue;
      }
      keyFieldTypes.add(field.type.getDisplayString());
    }
    if (keyFieldTypes.isEmpty) {
      _fail(
        '${entityElement.name} 没有可用于列表操作的物理 Key。',
        element,
        '在至少一个 @FoxyFullField 上设置 key: true。',
      );
    }
    if (keyFieldTypes.length == 1) return keyFieldTypes.single;
    final baseName = entityElement.name!.substring(
      0,
      entityElement.name!.length - 'Entity'.length,
    );
    return '${baseName}Key';
  }

  Never _fail(String message, Element element, String correction) {
    throw InvalidGenerationSourceError(
      '$message\n修复方式：$correction',
      element: element,
    );
  }
}
