import 'package:foxy_generator/src/naming.dart';

/// List filter fields (all from the repository's `@FoxyFilter.text`).
final class ListFilterFieldModel {
  final String name;

  const ListFilterFieldModel({required this.name});

  /// Controller identifier: `class_` → `class` (reserved-word escape,
  /// matching FormEmitter).
  String get controllerName =>
      name.endsWith('_') ? name.substring(0, name.length - 1) : name;
}

final class ListGenerationModel {
  /// Hand-written List ViewModel class name, e.g.
  /// `CreatureTemplateListViewModel`.
  final String className;

  /// Full Entity class name the list maps to, e.g. `CreatureTemplateEntity`.
  final String entityClassName;

  /// Brief Entity class name shown on the list page, e.g.
  /// `BriefCreatureTemplateEntity`.
  final String briefEntityClassName;

  /// Repository class name providing the list methods.
  final String repositoryClassName;

  /// Generated part mixin name, e.g. `_CreatureTemplateListViewModelMixin`.
  final String mixinName;

  /// Text filter fields in the repository's `@FoxyFilter` declaration order.
  final List<ListFilterFieldModel> fields;

  /// Instance method on the repository returning the Brief list (naming
  /// convention, see ListReader).
  final String getBriefMethodName;

  /// Instance method on the repository counting the total.
  final String countMethodName;

  /// Method on the repository copying a record (fully generated by the
  /// query layer; always present).
  final String copyMethodName;

  /// Physical Key type: `int` or composite `XxxKey` (from the entity's key
  /// fields).
  final String keyType;

  const ListGenerationModel({
    required this.className,
    required this.entityClassName,
    required this.briefEntityClassName,
    required this.repositoryClassName,
    required this.mixinName,
    required this.fields,
    required this.getBriefMethodName,
    required this.countMethodName,
    required this.copyMethodName,
    required this.keyType,
  });

  /// `CreatureTemplateEntity` → `creatureTemplate` (matches the
  /// Repository's entity parameter naming; used as the entity name in logs
  /// and tooltips).
  String get entityCamelName => entityParameterName(entityClassName);

  /// Filter class name: `CreatureTemplateRepository` →
  /// `CreatureTemplateFilter`.
  String get filterClassName =>
      '${repositoryClassName.substring(0, repositoryClassName.length - 'Repository'.length)}Filter';

  /// Parameter type of the empty implementation hooks: `int key` when the
  /// key is an int, otherwise `XxxKey key`.
  String get keyParameter => keyType == 'int' ? 'int key' : '$keyType key';
}
