// ignore_for_file: depend_on_referenced_packages, experimental_member_use

import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'package:foxy_annotation/repository_annotations.dart';
import 'package:foxy_generator/src/convention.dart';
import 'package:foxy_generator/src/entity_resolver.dart';
import 'package:foxy_generator/src/list_model.dart';
import 'package:foxy_generator/src/naming.dart';

const _fullFieldChecker = TypeChecker.fromUrl(
  'package:foxy_annotation/entity_annotations.dart#FoxyFullField',
);
const _repositoryChecker = TypeChecker.fromUrl(
  'package:foxy_annotation/repository_annotations.dart#FoxyRepository',
);
const _filterChecker = TypeChecker.fromUrl(
  'package:foxy_annotation/repository_annotations.dart#FoxyFilter',
);

/// Parses `@FoxyListViewModel`.
///
/// Query-layer methods are called directly by naming convention:
/// `getBrief<Base>s` / `count<Base>s` / `copy<Base>` / `destroy<Base>`.
/// These are fully generated by the Repository generator (query-layer
/// repositories); a hand-written shell's `@override` replaces the generated
/// version while the method name stays the same — signature mismatches
/// surface as compiler errors, the generator does no source-text matching.
final class ListReader {
  const ListReader();

  Future<ListGenerationModel> read(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) async {
    if (element is! ClassElement) {
      _fail(
        '@FoxyListViewModel can only annotate a ViewModel class.',
        element,
        'Move the annotation to a concrete List ViewModel class.',
      );
    }
    final className = element.name;
    if (className == null || !className.endsWith('ListViewModel')) {
      _fail(
        '@FoxyListViewModel can only annotate a class ending in '
            'ListViewModel.',
        element,
        'Use a concrete List ViewModel class.',
      );
    }

    final inputFileName = buildStep.inputId.pathSegments.last;
    final expectedFileName = '${toSnakeCase(className)}.dart';
    if (inputFileName != expectedFileName) {
      _fail(
        '$className must be located in $expectedFileName; the current '
            'file is $inputFileName.',
        element,
        'Keep the ViewModel class name consistent with the file name.',
      );
    }

    final (ClassElement entityElement, String table) =
        await _readEntity(annotation, className, element, buildStep);
    final repositoryElement = await _readRepository(
      annotation,
      className,
      entityElement,
      element,
      buildStep,
    );
    final repositoryClassName = repositoryElement.name!;

    final baseName = repositoryClassName.substring(
      0,
      repositoryClassName.length - 'Repository'.length,
    );
    final filterClassName = '${baseName}Filter';

    final fields = _readFilterFields(
      repositoryElement,
      filterClassName,
      element,
    );

    final keyType = _readEntityKeyType(entityElement, element);
    final mixinName = '_${className}Mixin';
    final source = await buildStep.readAsString(buildStep.inputId);
    final partName = inputFileName.replaceFirst(RegExp(r'\.dart$'), '.g.dart');
    if (!source.contains("part '$partName';") &&
        !source.contains('part "$partName";')) {
      _fail(
        "$className is missing part '$partName';.",
        element,
        'Declare the generated part after the ViewModel imports.',
      );
    }
    if (!RegExp(
      'class\\s+$className\\s+with\\s+[^\\{;]*\\b$mixinName\\b',
    ).hasMatch(source)) {
      _fail(
        '$className must mix in $mixinName.',
        element,
        "Add $mixinName to the end of the ViewModel's with list.",
      );
    }
    final withList = RegExp(
      'class\\s+$className\\s+with\\s+([^\\{;]*)',
    ).firstMatch(source)?.group(1);
    if (withList != null) {
      final parts = withList.split(',').map((part) => part.trim()).toList();
      final controllerIndex = parts.indexOf('FieldControllerMixin');
      final queryIndex = parts.indexOf('QueryVersionMixin');
      final mixinIndex = parts.indexOf(mixinName);
      if (controllerIndex < 0 || queryIndex < 0) {
        _fail(
          '$className must mix in FieldControllerMixin and '
              'QueryVersionMixin.',
          element,
          'Add FieldControllerMixin, QueryVersionMixin to the with list.',
        );
      }
      if (controllerIndex > mixinIndex || queryIndex > mixinIndex) {
        _fail(
          'FieldControllerMixin / QueryVersionMixin must precede '
              '$mixinName.',
          element,
          'Reorder the with list: FieldControllerMixin, QueryVersionMixin, '
              '..., $mixinName.',
        );
      }
    }

    return ListGenerationModel(
      className: className,
      entityClassName: entityElement.name!,
      briefEntityClassName: 'Brief${baseName}Entity',
      repositoryClassName: repositoryClassName,
      mixinName: mixinName,
      fields: List.unmodifiable(fields),
      getBriefMethodName: 'getBrief${pluralize(baseName)}',
      countMethodName: 'count${pluralize(baseName)}',
      copyMethodName: 'copy$baseName',
      keyType: keyType,
      table: table,
    );
  }

  Future<(ClassElement, String)> _readEntity(
    ConstantReader annotation,
    String className,
    Element element,
    BuildStep buildStep,
  ) async {
    // Bound entity: explicit `entity:` wins; otherwise derived from the
    // class name (`XxxListViewModel` → `XxxEntity`).
    String entityClassName;
    final declaredEntity = annotation.peek('entity');
    if (declaredEntity != null && !declaredEntity.isNull) {
      final entityType = declaredEntity.typeValue;
      if (entityType is! InterfaceType) {
        _fail(
          "The entity parameter of $className's @FoxyListViewModel is not "
              'an Entity class.',
          element,
          'Pass a concrete Full Entity type.',
        );
      }
      entityClassName = entityType.element.name!;
      if (!entityClassName.endsWith('Entity')) {
        _fail(
          "The type bound by $className must end in Entity.",
          element,
          'Pass a concrete Full Entity type.',
        );
      }
    } else {
      entityClassName = entityClassNameOfViewModel(className) ??
          _fail(
            '$className cannot derive an entity class name.',
            element,
            'Use a class name ending in ListViewModel.',
          );
    }
    final resolved = await resolveFullEntity(
      buildStep,
      element,
      entityClassName,
      "$className's @FoxyListViewModel",
    );
    return (resolved.entityElement, resolved.table);
  }

  Future<ClassElement> _readRepository(
    ConstantReader annotation,
    String className,
    InterfaceElement entityElement,
    Element element,
    BuildStep buildStep,
  ) async {
    // Bound repository: explicit `repository:` wins (and must match the
    // entity's base name); otherwise derived from the class name
    // (`XxxListViewModel` → `XxxRepository`).
    String repositoryClassName;
    final declaredRepository = annotation.peek('repository');
    if (declaredRepository != null && !declaredRepository.isNull) {
      final repositoryType = declaredRepository.typeValue;
      if (repositoryType is! InterfaceType) {
        _fail(
          "The repository parameter of $className's @FoxyListViewModel is "
              'not a Repository class.',
          element,
          'Pass a concrete Repository type.',
        );
      }
      repositoryClassName = repositoryType.element.name!;
      if (!repositoryClassName.endsWith('Repository')) {
        _fail(
          "The type bound by $className must end in Repository.",
          element,
          'Pass a concrete Repository type.',
        );
      }
      if (stripSuffix(repositoryClassName, 'Repository') !=
          stripSuffix(entityElement.name!, 'Entity')) {
        _fail(
          '$repositoryClassName and ${entityElement.name} do not follow '
              'the one-to-one naming convention.',
          element,
          'Use the same base name for the Repository and the Entity.',
        );
      }
    } else {
      repositoryClassName = repositoryClassNameOfViewModel(className) ??
          _fail(
            '$className cannot derive a repository class name.',
            element,
            'Use a class name ending in ListViewModel.',
          );
    }

    // The derived repository must exist and be a migrated (annotated)
    // repository — otherwise the generated list has no query layer to call.
    final repositoryElement = await resolveClass(
      buildStep,
      element,
      repositoryClassName,
      'repository',
      "$className's @FoxyListViewModel",
    );
    final repositoryAnnotations = _repositoryChecker
        .annotationsOf(repositoryElement)
        .toList();
    if (repositoryAnnotations.length != 1) {
      _fail(
        '$repositoryClassName must declare exactly one @FoxyRepository.',
        repositoryElement,
        'Bind to a migrated generated Repository.',
      );
    }
    return repositoryElement;
  }

  List<ListFilterFieldModel> _readFilterFields(
    InterfaceElement repositoryElement,
    String filterClassName,
    Element element,
  ) {
    final fields = <ListFilterFieldModel>[];
    final names = <String>{};
    for (final object in _filterChecker.annotationsOf(repositoryElement)) {
      final reader = ConstantReader(object);
      final name = reader.read('name').stringValue;
      if (!names.add(name)) {
        _fail(
          '$filterClassName declares duplicate field $name.',
          element,
          'Ensure every @FoxyFilter field name is unique.',
        );
      }
      if (!RegExp(r'^[a-z][A-Za-z0-9]*_?$').hasMatch(name)) {
        _fail(
          "The field name $name of $filterClassName is not a valid "
              'lowerCamelCase identifier.',
          element,
          'Use lowerCamelCase; a trailing underscore is allowed for Dart '
              'reserved words.',
        );
      }
      final typeIndex = reader
          .read('type')
          .objectValue
          .getField('index')
          ?.toIntValue();
      final type =
          typeIndex != null &&
              typeIndex >= 0 &&
              typeIndex < FoxyFilterType.values.length
          ? FoxyFilterType.values[typeIndex]
          : null;
      if (type != FoxyFilterType.text) {
        _fail(
          'The filter type of $filterClassName.$name is '
              "${type?.name ?? 'unknown'}.",
          element,
          'List ViewModel currently supports only @FoxyFilter.text text '
              'filter fields; remove this filter or switch it to text.',
        );
      }
      fields.add(ListFilterFieldModel(name: name));
    }
    return fields;
  }

  /// Infers the Key type from the entity's `@FoxyFullField(key: true)`: a
  /// single key is the field type, a composite key is `XxxKey` (a generated
  /// class; only its name is inferable).
  String _readEntityKeyType(InterfaceElement entityElement, Element element) {
    final keyFieldTypes = <String>[];
    for (final field in entityElement.fields.where(
      (field) => !field.isStatic && !field.isSynthetic,
    )) {
      final annotations = _fullFieldChecker.annotationsOf(field).toList();
      if (annotations.length != 1) continue;
      if (!(ConstantReader(annotations.single).peek('key')?.boolValue ??
          false)) {
        continue;
      }
      keyFieldTypes.add(field.type.getDisplayString());
    }
    if (keyFieldTypes.isEmpty) {
      _fail(
        '${entityElement.name} has no physical key usable for list '
            'operations.',
        element,
        'Set key: true on at least one @FoxyFullField.',
      );
    }
    if (keyFieldTypes.length == 1) return keyFieldTypes.single;
    final baseName = entityElement.name!.substring(
      0,
      entityElement.name!.length - 'Entity'.length,
    );
    return '${baseName}Key';
  }

  Never _fail(String message, Element element, String correction) {
    throw InvalidGenerationSourceError(
      '$message\nFix: $correction',
      element: element,
    );
  }
}
