// global
export const STORE_MYSQL_CONFIG = "STORE_MYSQL_CONFIG";
export const STORE_DBC_CONFIG = "STORE_DBC_CONFIG";
export const STORE_CONFIG_CONFIG = "STORE_CONFIG_CONFIG";
export const STORE_DEVELOPER_CONFIG = "STORE_DEVELOPER_CONFIG";
export const SET_ACTIVE = "SET_ACTIVE";
export const GLOBAL_NOTICE = "GLOBAL_NOTICE";
export const SET_SETTING_ACTIVE = "SET_SETTING_ACTIVE";
export const INIT_MYSQL_CONNECTION = "INIT_MYSQL_CONNECTION";
export const TEST_MYSQL_CONNECTION = "TEST_MYSQL_CONNECTION";
export const INIT_DBC_CONFIG = "INIT_DBC_CONFIG";
// dbc
export const SEARCH_DBC_FACTIONS = "SEARCH_DBC_FACTIONS";
export const SEARCH_DBC_FACTION_TEMPLATES = "SEARCH_DBC_FACTION_TEMPLATES";
export const SEARCH_DBC_ITEM_DISPLAY_INFOS = "SEARCH_DBC_ITEM_DISPLAY_INFOS";
export const SEARCH_DBC_SPELLS = "SEARCH_DBC_SPELLS";
export const SEARCH_DBC_SPELL_DURATIONS = "SEARCH_DBC_SPELL_DURATIONS";
export const SEARCH_DBC_SCALING_STAT_DISTRIBUTIONS =
  "SEARCH_DBC_SCALING_STAT_DISTRIBUTIONS";
export const SEARCH_DBC_SCALING_STAT_VALUES = "SEARCH_DBC_SCALING_STAT_VALUES";
// creature
export const UPDATE_CREATURE_TEMPLATE_CREDENTIAL_ENTRY =
  "UPDATE_CREATURE_TEMPLATE_CREDENTIAL_ENTRY";
export const UPDATE_CREATURE_TEMPLATE_CREDENTIAL_NAME =
  "UPDATE_CREATURE_TEMPLATE_CREDENTIAL_NAME";
export const UPDATE_CREATURE_TEMPLATE_CREDENTIAL_SUBNAME =
  "UPDATE_CREATURE_TEMPLATE_CREDENTIAL_SUBNAME";
export const SEARCH_CREATURE_TEMPLATES = "SEARCH_CREATURE_TEMPLATES";
export const COUNT_CREATURE_TEMPLATES = "COUNT_CREATURE_TEMPLATES";
export const PAGINATE_CREATURE_TEMPLATES = "PAGINATE_CREATURE_TEMPLATES";
export const STORE_CREATURE_TEMPLATE = "STORE_CREATURE_TEMPLATE";
export const FIND_CREATURE_TEMPLATE = "FIND_CREATURE_TEMPLATE";
export const UPDATE_CREATURE_TEMPLATE = "UPDATE_CREATURE_TEMPLATE";
export const DESTROY_CREATURE_TEMPLATE = "DESTROY_CREATURE_TEMPLATE";
export const CREATE_CREATURE_TEMPLATE = "CREATE_CREATURE_TEMPLATE";
export const COPY_CREATURE_TEMPLATE = "COPY_CREATURE_TEMPLATE";
export const SEARCH_CREATURE_TEMPLATE_LOCALES =
  "SEARCH_CREATURE_TEMPLATE_LOCALES";
export const STORE_CREATURE_TEMPLATE_LOCALES =
  "STORE_CREATURE_TEMPLATE_LOCALES";

export const STORE_CREATURE_TEMPLATE_ADDON = "STORE_CREATURE_TEMPLATE_ADDON";
export const FIND_CREATURE_TEMPLATE_ADDON = "FIND_CREATURE_TEMPLATE_ADDON";
export const UPDATE_CREATURE_TEMPLATE_ADDON = "UPDATE_CREATURE_TEMPLATE_ADDON";
export const CREATE_CREATURE_TEMPLATE_ADDON = "CREATE_CREATURE_TEMPLATE_ADDON";

export const STORE_CREATURE_ONKILL_REPUTATION =
  "STORE_CREATURE_ONKILL_REPUTATION";
export const FIND_CREATURE_ONKILL_REPUTATION =
  "FIND_CREATURE_ONKILL_REPUTATION";
export const UPDATE_CREATURE_ONKILL_REPUTATION =
  "UPDATE_CREATURE_ONKILL_REPUTATION";
export const CREATE_CREATURE_ONKILL_REPUTATION =
  "CREATE_CREATURE_ONKILL_REPUTATION";

export const SEARCH_CREATURE_EQUIP_TEMPLATES =
  "SEARCH_CREATURE_EQUIP_TEMPLATES";
export const STORE_CREATURE_EQUIP_TEMPLATE = "STORE_CREATURE_EQUIP_TEMPLATE";
export const FIND_CREATURE_EQUIP_TEMPLATE = "FIND_CREATURE_EQUIP_TEMPLATE";
export const UPDATE_CREATURE_EQUIP_TEMPLATE = "UPDATE_CREATURE_EQUIP_TEMPLATE";
export const DESTROY_CREATURE_EQUIP_TEMPLATE =
  "DESTROY_CREATURE_EQUIP_TEMPLATE";
export const CREATE_CREATURE_EQUIP_TEMPLATE = "CREATE_CREATURE_EQUIP_TEMPLATE";
export const COPY_CREATURE_EQUIP_TEMPLATE = "COPY_CREATURE_EQUIP_TEMPLATE";

export const SEARCH_CREATURE_QUEST_ITEMS = "SEARCH_CREATURE_QUEST_ITEMS";
export const STORE_CREATURE_QUEST_ITEM = "STORE_CREATURE_QUEST_ITEM";
export const FIND_CREATURE_QUEST_ITEM = "FIND_CREATURE_QUEST_ITEM";
export const UPDATE_CREATURE_QUEST_ITEM = "UPDATE_CREATURE_QUEST_ITEM";
export const DESTROY_CREATURE_QUEST_ITEM = "DESTROY_CREATURE_QUEST_ITEM";
export const CREATE_CREATURE_QUEST_ITEM = "CREATE_CREATURE_QUEST_ITEM";
export const COPY_CREATURE_QUEST_ITEM = "COPY_CREATURE_QUEST_ITEM";

export const SEARCH_NPC_VENDORS = "SEARCH_NPC_VENDORS";
export const STORE_NPC_VENDOR = "STORE_NPC_VENDOR";
export const FIND_NPC_VENDOR = "FIND_NPC_VENDOR";
export const UPDATE_NPC_VENDOR = "UPDATE_NPC_VENDOR";
export const DESTROY_NPC_VENDOR = "DESTROY_NPC_VENDOR";
export const CREATE_NPC_VENDOR = "CREATE_NPC_VENDOR";
export const COPY_NPC_VENDOR = "COPY_NPC_VENDOR";

export const SEARCH_NPC_TRAINERS = "SEARCH_NPC_TRAINERS";
export const STORE_NPC_TRAINER = "STORE_NPC_TRAINER";
export const FIND_NPC_TRAINER = "FIND_NPC_TRAINER";
export const UPDATE_NPC_TRAINER = "UPDATE_NPC_TRAINER";
export const DESTROY_NPC_TRAINER = "DESTROY_NPC_TRAINER";
export const CREATE_NPC_TRAINER = "CREATE_NPC_TRAINER";
export const COPY_NPC_TRAINER = "COPY_NPC_TRAINER";

export const SEARCH_CREATURE_LOOT_TEMPLATES = "SEARCH_CREATURE_LOOT_TEMPLATES";
export const STORE_CREATURE_LOOT_TEMPLATE = "STORE_CREATURE_LOOT_TEMPLATE";
export const FIND_CREATURE_LOOT_TEMPLATE = "FIND_CREATURE_LOOT_TEMPLATE";
export const UPDATE_CREATURE_LOOT_TEMPLATE = "UPDATE_CREATURE_LOOT_TEMPLATE";
export const DESTROY_CREATURE_LOOT_TEMPLATE = "DESTROY_CREATURE_LOOT_TEMPLATE";
export const CREATE_CREATURE_LOOT_TEMPLATE = "CREATE_CREATURE_LOOT_TEMPLATE";
export const COPY_CREATURE_LOOT_TEMPLATE = "COPY_CREATURE_LOOT_TEMPLATE";

export const SEARCH_PICKPOCKETING_LOOT_TEMPLATES =
  "SEARCH_PICKPOCKETING_LOOT_TEMPLATES";
export const STORE_PICKPOCKETING_LOOT_TEMPLATE =
  "STORE_PICKPOCKETING_LOOT_TEMPLATE";
export const FIND_PICKPOCKETING_LOOT_TEMPLATE =
  "FIND_PICKPOCKETING_LOOT_TEMPLATE";
export const UPDATE_PICKPOCKETING_LOOT_TEMPLATE =
  "UPDATE_PICKPOCKETING_LOOT_TEMPLATE";
export const DESTROY_PICKPOCKETING_LOOT_TEMPLATE =
  "DESTROY_PICKPOCKETING_LOOT_TEMPLATE";
export const CREATE_PICKPOCKETING_LOOT_TEMPLATE =
  "CREATE_PICKPOCKETING_LOOT_TEMPLATE";
export const COPY_PICKPOCKETING_LOOT_TEMPLATE =
  "COPY_PICKPOCKETING_LOOT_TEMPLATE";

export const SEARCH_SKINNING_LOOT_TEMPLATES = "SEARCH_SKINNING_LOOT_TEMPLATES";
// game object
export const SEARCH_GAME_OBJECT_TEMPLATES = "SEARCH_GAME_OBJECT_TEMPLATES";
export const COUNT_GAME_OBJECT_TEMPLATES = "COUNT_GAME_OBJECT_TEMPLATES";
export const PAGINATE_GAME_OBJECT_TEMPLATES = "PAGINATE_GAME_OBJECT_TEMPLATES";
export const STORE_GAME_OBJECT_TEMPLATE = "STORE_GAME_OBJECT_TEMPLATE";
export const FIND_GAME_OBJECT_TEMPLATE = "FIND_GAME_OBJECT_TEMPLATE";
export const UPDATE_GAME_OBJECT_TEMPLATE = "UPDATE_GAME_OBJECT_TEMPLATE";
export const DESTROY_GAME_OBJECT_TEMPLATE = "DESTROY_GAME_OBJECT_TEMPLATE";
export const CREATE_GAME_OBJECT_TEMPLATE = "CREATE_GAME_OBJECT_TEMPLATE";
export const COPY_GAME_OBJECT_TEMPLATE = "COPY_GAME_OBJECT_TEMPLATE";
export const SEARCH_GAME_OBJECT_TEMPLATE_LOCALES =
  "SEARCH_GAME_OBJECT_TEMPLATE_LOCALES";
export const STORE_GAME_OBJECT_TEMPLATE_LOCALES =
  "STORE_GAME_OBJECT_TEMPLATE_LOCALES";
export const STORE_GAME_OBJECT_TEMPLATE_ADDON =
  "STORE_GAME_OBJECT_TEMPLATE_ADDON";
export const FIND_GAME_OBJECT_TEMPLATE_ADDON =
  "FIND_GAME_OBJECT_TEMPLATE_ADDON";
export const UPDATE_GAME_OBJECT_TEMPLATE_ADDON =
  "UPDATE_GAME_OBJECT_TEMPLATE_ADDON";
export const SEARCH_GAME_OBJECT_QUEST_ITEMS = "SEARCH_GAME_OBJECT_QUEST_ITEMS";
export const SEARCH_GAME_OBJECT_LOOT_TEMPLATES =
  "SEARCH_GAME_OBJECT_LOOT_TEMPLATES";
// item_template
export const SEARCH_ITEM_TEMPLATES = "SEARCH_ITEM_TEMPLATES";
export const COUNT_ITEM_TEMPLATES = "COUNT_ITEM_TEMPLATES";
export const PAGINATE_ITEM_TEMPLATES = "PAGINATE_ITEM_TEMPLATES";
export const STORE_ITEM_TEMPLATE = "STORE_ITEM_TEMPLATE";
export const FIND_ITEM_TEMPLATE = "FIND_ITEM_TEMPLATE";
export const UPDATE_ITEM_TEMPLATE = "UPDATE_ITEM_TEMPLATE";
export const DESTROY_ITEM_TEMPLATE = "DESTROY_ITEM_TEMPLATE";
export const CREATE_ITEM_TEMPLATE = "CREATE_ITEM_TEMPLATE";
export const COPY_ITEM_TEMPLATE = "COPY_ITEM_TEMPLATE";
export const SEARCH_ITEM_TEMPLATE_LOCALES = "SEARCH_ITEM_TEMPLATE_LOCALES";
export const STORE_ITEM_TEMPLATE_LOCALES = "STORE_ITEM_TEMPLATE_LOCALES";
export const SEARCH_ITEM_ENCHANTMENT_TEMPLATES =
  "SEARCH_ITEM_ENCHANTMENT_TEMPLATES";
export const STORE_ITEM_ENCHANTMENT_TEMPLATE =
  "STORE_ITEM_ENCHANTMENT_TEMPLATE";
export const FIND_ITEM_ENCHANTMENT_TEMPLATE = "FIND_ITEM_ENCHANTMENT_TEMPLATE";
export const UPDATE_ITEM_ENCHANTMENT_TEMPLATE =
  "UPDATE_ITEM_ENCHANTMENT_TEMPLATE";
export const DESTROY_ITEM_ENCHANTMENT_TEMPLATE =
  "DESTROY_ITEM_ENCHANTMENT_TEMPLATE";
export const CREATE_ITEM_ENCHANTMENT_TEMPLATE =
  "CREATE_ITEM_ENCHANTMENT_TEMPLATE";
export const COPY_ITEM_ENCHANTMENT_TEMPLATE = "COPY_ITEM_ENCHANTMENT_TEMPLATE";
export const SEARCH_ITEM_LOOT_TEMPLATES = "SEARCH_ITEM_LOOT_TEMPLATES";
export const STORE_ITEM_LOOT_TEMPLATE = "STORE_ITEM_LOOT_TEMPLATE";
export const FIND_ITEM_LOOT_TEMPLATE = "FIND_ITEM_LOOT_TEMPLATE";
export const UPDATE_ITEM_LOOT_TEMPLATE = "UPDATE_ITEM_LOOT_TEMPLATE";
export const DESTROY_ITEM_LOOT_TEMPLATE = "DESTROY_ITEM_LOOT_TEMPLATE";
export const CREATE_ITEM_LOOT_TEMPLATE = "CREATE_ITEM_LOOT_TEMPLATE";
export const COPY_ITEM_LOOT_TEMPLATE = "COPY_ITEM_LOOT_TEMPLATE";
export const SEARCH_DISENCHANT_LOOT_TEMPLATES =
  "SEARCH_DISENCHANT_LOOT_TEMPLATES";
export const SEARCH_PROSPECTING_LOOT_TEMPLATES =
  "SEARCH_PROSPECTING_LOOT_TEMPLATES";
export const SEARCH_MILLING_LOOT_TEMPLATES = "SEARCH_MILLING_LOOT_TEMPLATES";
// quest
export const SEARCH_QUEST_TEMPLATES = "SEARCH_QUEST_TEMPLATES";
export const COUNT_QUEST_TEMPLATES = "COUNT_QUEST_TEMPLATES";
export const PAGINATE_QUEST_TEMPLATES = "PAGINATE_QUEST_TEMPLATES";
export const STORE_QUEST_TEMPLATE = "STORE_QUEST_TEMPLATE";
export const FIND_QUEST_TEMPLATE = "FIND_QUEST_TEMPLATE";
export const UPDATE_QUEST_TEMPLATE = "UPDATE_QUEST_TEMPLATE";
export const DESTROY_QUEST_TEMPLATE = "DESTROY_QUEST_TEMPLATE";
export const CREATE_QUEST_TEMPLATE = "CREATE_QUEST_TEMPLATE";
export const COPY_QUEST_TEMPLATE = "COPY_QUEST_TEMPLATE";
export const SEARCH_QUEST_TEMPLATE_LOCALES = "SEARCH_QUEST_TEMPLATE_LOCALES";
export const STORE_QUEST_TEMPLATE_LOCALES = "STORE_QUEST_TEMPLATE_LOCALES";
// smart script
export const SEARCH_SMART_SCRIPTS = "SEARCH_SMART_SCRIPTS";
export const COUNT_SMART_SCRIPTS = "COUNT_SMART_SCRIPTS";
export const PAGINATE_SMART_SCRIPTS = "PAGINATE_SMART_SCRIPTS";
export const STORE_SMART_SCRIPT = "STORE_SMART_SCRIPT";
export const FIND_SMART_SCRIPT = "FIND_SMART_SCRIPT";
export const UPDATE_SMART_SCRIPT = "UPDATE_SMART_SCRIPT";
export const DESTROY_SMART_SCRIPT = "DESTROY_SMART_SCRIPT";
export const CREATE_SMART_SCRIPT = "CREATE_SMART_SCRIPT";
export const COPY_SMART_SCRIPT = "COPY_SMART_SCRIPT";
// spell
export const SEARCH_SPELLS = "SEARCH_SPELLS";
export const COUNT_SPELLS = "COUNT_SPELLS";
export const PAGINATE_SPELLS = "PAGINATE_SPELLS";
export const FIND_SPELL = "FIND_SPELL";
// gossip menu
export const SEARCH_GOSSIP_MENUS = "SEARCH_GOSSIP_MENUS";
export const COUNT_GOSSIP_MENUS = "COUNT_GOSSIP_MENUS";
export const PAGINATE_GOSSIP_MENUS = "PAGINATE_GOSSIP_MENUS";
export const STORE_GOSSIP_MENU = "STORE_GOSSIP_MENU";
export const FIND_GOSSIP_MENU = "FIND_GOSSIP_MENU";
export const UPDATE_GOSSIP_MENU = "UPDATE_GOSSIP_MENU";
export const DESTROY_GOSSIP_MENU = "DESTROY_GOSSIP_MENU";
export const CREATE_GOSSIP_MENU = "CREATE_GOSSIP_MENU";
export const COPY_GOSSIP_MENU = "COPY_GOSSIP_MENU";
export const STORE_NPC_TEXT = "STORE_NPC_TEXT";
export const FIND_NPC_TEXT = "FIND_NPC_TEXT";
export const UPDATE_NPC_TEXT = "UPDATE_NPC_TEXT";
export const SEARCH_NPC_TEXT_LOCALES = "SEARCH_NPC_TEXT_LOCALES";
export const STORE_NPC_TEXT_LOCALES = "STORE_NPC_TEXT_LOCALES";
export const SEARCH_GOSSIP_MENU_OPTIONS = "SEARCH_GOSSIP_MENU_OPTIONS";
export const STORE_GOSSIP_MENU_OPTION = "STORE_GOSSIP_MENU_OPTION";
export const FIND_GOSSIP_MENU_OPTION = "FIND_GOSSIP_MENU_OPTION";
export const UPDATE_GOSSIP_MENU_OPTION = "UPDATE_GOSSIP_MENU_OPTION";
export const DESTROY_GOSSIP_MENU_OPTION = "DESTROY_GOSSIP_MENU_OPTION";
export const CREATE_GOSSIP_MENU_OPTION = "CREATE_GOSSIP_MENU_OPTION";
export const COPY_GOSSIP_MENU_OPTION = "COPY_GOSSIP_MENU_OPTION";
