export const GLOBAL_MESSAGE = "GLOBAL_MESSAGE";
export const GLOBAL_MESSAGE_BOX = "GLOBAL_MESSAGE_BOX";
export const SET_ACTIVE = "SET_ACTIVE";
export const SET_SETTING_ACTIVE = "SET_SETTING_ACTIVE";

export const LOAD_DEVELOPER_CONFIG = "LOAD_DEVELOPER_CONFIG";
export const LOAD_ADVANCE_CONFIG = "LOAD_ADVANCE_CONFIG";
export const LOAD_MYSQL_CONFIG = "LOAD_MYSQL_CONFIG";
export const LOAD_DBC_CONFIG = "LOAD_DBC_CONFIG";
export const INITIALIZE_MYSQL_CONNECTION = "INITIALIZE_MYSQL_CONNECTION";
export const INITIALIZE_DBC_PATH = "INITIALIZE_DBC_PATH";

export const LOAD_DBC_ACHIEVEMENTS = "LOAD_DBC_ACHIEVEMENTS";
export const LOAD_DBC_ACHIEVEMENT_CATEGORIES =
  "LOAD_DBC_ACHIEVEMENT_CATEGORIES";
export const LOAD_DBC_ACHIEVEMENT_CRITERIAS = "LOAD_DBC_ACHIEVEMENT_CRITERIAS";
export const LOAD_DBC_AREA_TABLES = "LOAD_DBC_AREA_TABLES";
export const LOAD_DBC_CHAR_TITLES = "LOAD_DBC_CHAR_TITLES";
export const LOAD_DBC_CHR_CLASSES = "LOAD_DBC_CHR_CLASSES";
export const LOAD_DBC_CHR_RACES = "LOAD_DBC_CHR_RACES";
export const LOAD_DBC_CREATURE_DISPLAY_INFOS =
  "LOAD_DBC_CREATURE_DISPLAY_INFOS";
export const LOAD_DBC_CREATURE_MODEL_DATAS = "LOAD_DBC_CREATURE_MODEL_DATAS";
export const LOAD_DBC_CREATURE_SPELL_DATAS = "LOAD_DBC_CREATURE_SPELL_DATAS";
export const LOAD_DBC_CURRENCY_CATEGORIES = "LOAD_DBC_CURRENCY_CATEGORIES";
export const LOAD_DBC_CURRENCY_TYPES = "LOAD_DBC_CURRENCY_TYPES";
export const LOAD_DBC_EMOTES = "LOAD_DBC_EMOTES";
export const LOAD_DBC_EMOTES_TEXTS = "LOAD_DBC_EMOTES_TEXTS";
export const LOAD_DBC_FACTIONS = "LOAD_DBC_FACTIONS";
export const LOAD_DBC_FACTION_TEMPLATES = "LOAD_DBC_FACTION_TEMPLATES";
export const LOAD_DBC_GAME_OBJECT_DISPLAY_INFOS =
  "LOAD_DBC_GAME_OBJECT_DISPLAY_INFOS";
export const LOAD_DBC_ITEMS = "LOAD_DBC_ITEMS";
export const LOAD_DBC_ITEM_DISPLAY_INFOS = "LOAD_DBC_ITEM_DISPLAY_INFOS";
export const LOAD_DBC_ITEM_EXTENDED_COSTS = "LOAD_DBC_ITEM_EXTENDED_COSTS";
export const LOAD_DBC_ITEM_RANDOM_PROPERTITIES =
  "LOAD_DBC_ITEM_RANDOM_PROPERTITIES";
export const LOAD_DBC_ITEM_RANDOM_SUFFIXES = "LOAD_DBC_ITEM_RANDOM_SUFFIXES";
export const LOAD_DBC_ITEM_SETS = "LOAD_DBC_ITEM_SETS";
export const LOAD_DBC_LOCKS = "LOAD_DBC_LOCKS";
export const LOAD_DBC_LOCK_TYPES = "LOAD_DBC_LOCK_TYPES";
export const LOAD_DBC_MAPS = "LOAD_DBC_MAPS";
export const LOAD_DBC_QUEST_FACTION_REWARDS = "LOAD_DBC_QUEST_FACTION_REWARDS";
export const LOAD_DBC_QUEST_INFOS = "LOAD_DBC_QUEST_INFOS";
export const LOAD_DBC_QUEST_SORTS = "LOAD_DBC_QUEST_SORTS";
export const LOAD_DBC_SCALING_STAT_DISTRIBUTIONS =
  "LOAD_DBC_SCALING_STAT_DISTRIBUTIONS";
export const LOAD_DBC_SCALING_STAT_VALUES = "LOAD_DBC_SCALING_STAT_VALUES";
export const LOAD_DBC_SPELLS = "LOAD_DBC_SPELLS";
export const LOAD_DBC_SPELL_CAST_TIMES = "LOAD_DBC_SPELL_CAST_TIMES";
export const LOAD_DBC_SPELL_CATEGORIES = "LOAD_DBC_SPELL_CATEGORIES";
export const LOAD_DBC_SPELL_DESCRIPTION_VARIABLES =
  "LOAD_DBC_SPELL_DESCRIPTION_VARIABLES";
export const LOAD_DBC_SPELL_DIFFICULTIES = "LOAD_DBC_SPELL_DIFFICULTIES";
export const LOAD_DBC_SPELL_DISPEL_TYPES = "LOAD_DBC_SPELL_DISPEL_TYPES";
export const LOAD_DBC_SPELL_DURATIONS = "LOAD_DBC_SPELL_DURATIONS";
export const LOAD_DBC_SPELL_ICONS = "LOAD_DBC_SPELL_ICONS";
export const LOAD_DBC_SPELL_ITEM_ENCHANTMENTS =
  "LOAD_DBC_SPELL_ITEM_ENCHANTMENTS";
export const LOAD_DBC_SPELL_MECHANICS = "LOAD_DBC_SPELL_MECHANICS";
export const LOAD_DBC_SPELL_RANGES = "LOAD_DBC_SPELL_RANGES";
export const LOAD_DBC_TALENTS = "LOAD_DBC_TALENTS";
export const LOAD_DBC_TALENT_TABS = "LOAD_DBC_TALENT_TABS";

export const CHECK_VERSION = "CHECK_VERSION";
export const TEST_MYSQL_CONNECTION = "TEST_MYSQL_CONNECTION";
export const STORE_DEVELOPER_CONFIG = "STORE_DEVELOPER_CONFIG";
export const STORE_MYSQL_CONFIG = "STORE_MYSQL_CONFIG";
export const STORE_DBC_CONFIG = "STORE_DBC_CONFIG";

export const START_EXPORT = "START_EXPORT";
export const UPDATE_CHECKED_DBCS = "UPDATE_CHECKED_DBCS";

export const SEARCH_CREATURE_TEMPLATES = "SEARCH_CREATURE_TEMPLATES";
export const COUNT_CREATURE_TEMPLATES = "COUNT_CREATURE_TEMPLATES";
export const PAGINATE_CREATURE_TEMPLATES = "PAGINATE_CREATURE_TEMPLATES";
export const STORE_CREATURE_TEMPLATE = "STORE_CREATURE_TEMPLATE";
export const FIND_CREATURE_TEMPLATE = "FIND_CREATURE_TEMPLATE";
export const UPDATE_CREATURE_TEMPLATE = "UPDATE_CREATURE_TEMPLATE";
export const DESTROY_CREATURE_TEMPLATE = "DESTROY_CREATURE_TEMPLATE";
export const CREATE_CREATURE_TEMPLATE = "CREATE_CREATURE_TEMPLATE";
export const COPY_CREATURE_TEMPLATE = "COPY_CREATURE_TEMPLATE";

export const SEARCH_CREATURE_TEMPLATE_LOCALES =
  "SEARCH_CREATURE_TEMPLATE_LOCALES";
export const STORE_CREATURE_TEMPLATE_LOCALES =
  "STORE_CREATURE_TEMPLATE_LOCALES";

export const STORE_CREATURE_TEMPLATE_ADDON = "STORE_CREATURE_TEMPLATE_ADDON";
export const FIND_CREATURE_TEMPLATE_ADDON = "FIND_CREATURE_TEMPLATE_ADDON";
export const UPDATE_CREATURE_TEMPLATE_ADDON = "UPDATE_CREATURE_TEMPLATE_ADDON";
export const CREATE_CREATURE_TEMPLATE_ADDON = "CREATE_CREATURE_TEMPLATE_ADDON";

export const SEARCH_CREATURE_TEMPLATE_RESISTANCES =
  "SEARCH_CREATURE_TEMPLATE_RESISTANCES";
export const STORE_CREATURE_TEMPLATE_RESISTANCE =
  "STORE_CREATURE_TEMPLATE_RESISTANCE";
export const FIND_CREATURE_TEMPLATE_RESISTANCE =
  "FIND_CREATURE_TEMPLATE_RESISTANCE";
export const UPDATE_CREATURE_TEMPLATE_RESISTANCE =
  "UPDATE_CREATURE_TEMPLATE_RESISTANCE";
export const DESTROY_CREATURE_TEMPLATE_RESISTANCE =
  "DESTROY_CREATURE_TEMPLATE_RESISTANCE";
export const CREATE_CREATURE_TEMPLATE_RESISTANCE =
  "CREATE_CREATURE_TEMPLATE_RESISTANCE";
export const COPY_CREATURE_TEMPLATE_RESISTANCE =
  "COPY_CREATURE_TEMPLATE_RESISTANCE";

export const SEARCH_CREATURE_TEMPLATE_SPELLS =
  "SEARCH_CREATURE_TEMPLATE_SPELLS";
export const STORE_CREATURE_TEMPLATE_SPELL = "STORE_CREATURE_TEMPLATE_SPELL";
export const FIND_CREATURE_TEMPLATE_SPELL = "FIND_CREATURE_TEMPLATE_SPELL";
export const UPDATE_CREATURE_TEMPLATE_SPELL = "UPDATE_CREATURE_TEMPLATE_SPELL";
export const DESTROY_CREATURE_TEMPLATE_SPELL =
  "DESTROY_CREATURE_TEMPLATE_SPELL";
export const CREATE_CREATURE_TEMPLATE_SPELL = "CREATE_CREATURE_TEMPLATE_SPELL";
export const COPY_CREATURE_TEMPLATE_SPELL = "COPY_CREATURE_TEMPLATE_SPELL";

export const STORE_CREATURE_ONKILL_REPUTATION =
  "STORE_CREATURE_ONKILL_REPUTATION";
export const FIND_CREATURE_ONKILL_REPUTATION =
  "FIND_CREATURE_ONKILL_REPUTATION";
export const UPDATE_CREATURE_ONKILL_REPUTATION =
  "UPDATE_CREATURE_ONKILL_REPUTATION";
export const CREATE_CREATURE_ONKILL_REPUTATION =
  "CREATE_CREATURE_ONKILL_REPUTATION";

export const SEARCH_CREATURE_EQUIP_TEMPLATES =
  "SEARCH_CREATURE_EQUIP_TEMPLATES";
export const STORE_CREATURE_EQUIP_TEMPLATE = "STORE_CREATURE_EQUIP_TEMPLATE";
export const FIND_CREATURE_EQUIP_TEMPLATE = "FIND_CREATURE_EQUIP_TEMPLATE";
export const UPDATE_CREATURE_EQUIP_TEMPLATE = "UPDATE_CREATURE_EQUIP_TEMPLATE";
export const DESTROY_CREATURE_EQUIP_TEMPLATE =
  "DESTROY_CREATURE_EQUIP_TEMPLATE";
export const CREATE_CREATURE_EQUIP_TEMPLATE = "CREATE_CREATURE_EQUIP_TEMPLATE";
export const COPY_CREATURE_EQUIP_TEMPLATE = "COPY_CREATURE_EQUIP_TEMPLATE";

export const SEARCH_CREATURE_QUEST_ITEMS = "SEARCH_CREATURE_QUEST_ITEMS";
export const STORE_CREATURE_QUEST_ITEM = "STORE_CREATURE_QUEST_ITEM";
export const FIND_CREATURE_QUEST_ITEM = "FIND_CREATURE_QUEST_ITEM";
export const UPDATE_CREATURE_QUEST_ITEM = "UPDATE_CREATURE_QUEST_ITEM";
export const DESTROY_CREATURE_QUEST_ITEM = "DESTROY_CREATURE_QUEST_ITEM";
export const CREATE_CREATURE_QUEST_ITEM = "CREATE_CREATURE_QUEST_ITEM";
export const COPY_CREATURE_QUEST_ITEM = "COPY_CREATURE_QUEST_ITEM";

export const SEARCH_NPC_VENDORS = "SEARCH_NPC_VENDORS";
export const STORE_NPC_VENDOR = "STORE_NPC_VENDOR";
export const FIND_NPC_VENDOR = "FIND_NPC_VENDOR";
export const UPDATE_NPC_VENDOR = "UPDATE_NPC_VENDOR";
export const DESTROY_NPC_VENDOR = "DESTROY_NPC_VENDOR";
export const CREATE_NPC_VENDOR = "CREATE_NPC_VENDOR";
export const COPY_NPC_VENDOR = "COPY_NPC_VENDOR";

export const SEARCH_NPC_TRAINERS = "SEARCH_NPC_TRAINERS";
export const STORE_NPC_TRAINER = "STORE_NPC_TRAINER";
export const FIND_NPC_TRAINER = "FIND_NPC_TRAINER";
export const UPDATE_NPC_TRAINER = "UPDATE_NPC_TRAINER";
export const DESTROY_NPC_TRAINER = "DESTROY_NPC_TRAINER";
export const CREATE_NPC_TRAINER = "CREATE_NPC_TRAINER";
export const COPY_NPC_TRAINER = "COPY_NPC_TRAINER";

export const SEARCH_CREATURE_LOOT_TEMPLATES = "SEARCH_CREATURE_LOOT_TEMPLATES";
export const STORE_CREATURE_LOOT_TEMPLATE = "STORE_CREATURE_LOOT_TEMPLATE";
export const FIND_CREATURE_LOOT_TEMPLATE = "FIND_CREATURE_LOOT_TEMPLATE";
export const UPDATE_CREATURE_LOOT_TEMPLATE = "UPDATE_CREATURE_LOOT_TEMPLATE";
export const DESTROY_CREATURE_LOOT_TEMPLATE = "DESTROY_CREATURE_LOOT_TEMPLATE";
export const CREATE_CREATURE_LOOT_TEMPLATE = "CREATE_CREATURE_LOOT_TEMPLATE";
export const COPY_CREATURE_LOOT_TEMPLATE = "COPY_CREATURE_LOOT_TEMPLATE";

export const SEARCH_PICKPOCKETING_LOOT_TEMPLATES =
  "SEARCH_PICKPOCKETING_LOOT_TEMPLATES";
export const STORE_PICKPOCKETING_LOOT_TEMPLATE =
  "STORE_PICKPOCKETING_LOOT_TEMPLATE";
export const FIND_PICKPOCKETING_LOOT_TEMPLATE =
  "FIND_PICKPOCKETING_LOOT_TEMPLATE";
export const UPDATE_PICKPOCKETING_LOOT_TEMPLATE =
  "UPDATE_PICKPOCKETING_LOOT_TEMPLATE";
export const DESTROY_PICKPOCKETING_LOOT_TEMPLATE =
  "DESTROY_PICKPOCKETING_LOOT_TEMPLATE";
export const CREATE_PICKPOCKETING_LOOT_TEMPLATE =
  "CREATE_PICKPOCKETING_LOOT_TEMPLATE";
export const COPY_PICKPOCKETING_LOOT_TEMPLATE =
  "COPY_PICKPOCKETING_LOOT_TEMPLATE";

export const SEARCH_SKINNING_LOOT_TEMPLATES = "SEARCH_SKINNING_LOOT_TEMPLATES";
export const STORE_SKINNING_LOOT_TEMPLATE = "STORE_SKINNING_LOOT_TEMPLATE";
export const FIND_SKINNING_LOOT_TEMPLATE = "FIND_SKINNING_LOOT_TEMPLATE";
export const UPDATE_SKINNING_LOOT_TEMPLATE = "UPDATE_SKINNING_LOOT_TEMPLATE";
export const DESTROY_SKINNING_LOOT_TEMPLATE = "DESTROY_SKINNING_LOOT_TEMPLATE";
export const CREATE_SKINNING_LOOT_TEMPLATE = "CREATE_SKINNING_LOOT_TEMPLATE";
export const COPY_SKINNING_LOOT_TEMPLATE = "COPY_SKINNING_LOOT_TEMPLATE";

export const SEARCH_ITEM_TEMPLATES = "SEARCH_ITEM_TEMPLATES";
export const COUNT_ITEM_TEMPLATES = "COUNT_ITEM_TEMPLATES";
export const PAGINATE_ITEM_TEMPLATES = "PAGINATE_ITEM_TEMPLATES";
export const STORE_ITEM_TEMPLATE = "STORE_ITEM_TEMPLATE";
export const FIND_ITEM_TEMPLATE = "FIND_ITEM_TEMPLATE";
export const UPDATE_ITEM_TEMPLATE = "UPDATE_ITEM_TEMPLATE";
export const DESTROY_ITEM_TEMPLATE = "DESTROY_ITEM_TEMPLATE";
export const CREATE_ITEM_TEMPLATE = "CREATE_ITEM_TEMPLATE";
export const COPY_ITEM_TEMPLATE = "COPY_ITEM_TEMPLATE";

export const SEARCH_ITEM_TEMPLATE_LOCALES = "SEARCH_ITEM_TEMPLATE_LOCALES";
export const STORE_ITEM_TEMPLATE_LOCALES = "STORE_ITEM_TEMPLATE_LOCALES";

export const SEARCH_ITEM_ENCHANTMENT_TEMPLATES =
  "SEARCH_ITEM_ENCHANTMENT_TEMPLATES";
export const STORE_ITEM_ENCHANTMENT_TEMPLATE =
  "STORE_ITEM_ENCHANTMENT_TEMPLATE";
export const FIND_ITEM_ENCHANTMENT_TEMPLATE = "FIND_ITEM_ENCHANTMENT_TEMPLATE";
export const UPDATE_ITEM_ENCHANTMENT_TEMPLATE =
  "UPDATE_ITEM_ENCHANTMENT_TEMPLATE";
export const DESTROY_ITEM_ENCHANTMENT_TEMPLATE =
  "DESTROY_ITEM_ENCHANTMENT_TEMPLATE";
export const CREATE_ITEM_ENCHANTMENT_TEMPLATE =
  "CREATE_ITEM_ENCHANTMENT_TEMPLATE";
export const COPY_ITEM_ENCHANTMENT_TEMPLATE = "COPY_ITEM_ENCHANTMENT_TEMPLATE";

export const SEARCH_ITEM_LOOT_TEMPLATES = "SEARCH_ITEM_LOOT_TEMPLATES";
export const STORE_ITEM_LOOT_TEMPLATE = "STORE_ITEM_LOOT_TEMPLATE";
export const FIND_ITEM_LOOT_TEMPLATE = "FIND_ITEM_LOOT_TEMPLATE";
export const UPDATE_ITEM_LOOT_TEMPLATE = "UPDATE_ITEM_LOOT_TEMPLATE";
export const DESTROY_ITEM_LOOT_TEMPLATE = "DESTROY_ITEM_LOOT_TEMPLATE";
export const CREATE_ITEM_LOOT_TEMPLATE = "CREATE_ITEM_LOOT_TEMPLATE";
export const COPY_ITEM_LOOT_TEMPLATE = "COPY_ITEM_LOOT_TEMPLATE";

export const SEARCH_DISENCHANT_LOOT_TEMPLATES =
  "SEARCH_DISENCHANT_LOOT_TEMPLATES";
export const STORE_DISENCHANT_LOOT_TEMPLATE = "STORE_DISENCHANT_LOOT_TEMPLATE";
export const FIND_DISENCHANT_LOOT_TEMPLATE = "FIND_DISENCHANT_LOOT_TEMPLATE";
export const UPDATE_DISENCHANT_LOOT_TEMPLATE =
  "UPDATE_DISENCHANT_LOOT_TEMPLATE";
export const DESTROY_DISENCHANT_LOOT_TEMPLATE =
  "DESTROY_DISENCHANT_LOOT_TEMPLATE";
export const CREATE_DISENCHANT_LOOT_TEMPLATE =
  "CREATE_DISENCHANT_LOOT_TEMPLATE";
export const COPY_DISENCHANT_LOOT_TEMPLATE = "COPY_DISENCHANT_LOOT_TEMPLATE";

export const SEARCH_PROSPECTING_LOOT_TEMPLATES =
  "SEARCH_PROSPECTING_LOOT_TEMPLATES";
export const STORE_PROSPECTING_LOOT_TEMPLATE =
  "STORE_PROSPECTING_LOOT_TEMPLATE";
export const FIND_PROSPECTING_LOOT_TEMPLATE = "FIND_PROSPECTING_LOOT_TEMPLATE";
export const UPDATE_PROSPECTING_LOOT_TEMPLATE =
  "UPDATE_PROSPECTING_LOOT_TEMPLATE";
export const DESTROY_PROSPECTING_LOOT_TEMPLATE =
  "DESTROY_PROSPECTING_LOOT_TEMPLATE";
export const CREATE_PROSPECTING_LOOT_TEMPLATE =
  "CREATE_PROSPECTING_LOOT_TEMPLATE";
export const COPY_PROSPECTING_LOOT_TEMPLATE = "COPY_PROSPECTING_LOOT_TEMPLATE";

export const SEARCH_MILLING_LOOT_TEMPLATES = "SEARCH_MILLING_LOOT_TEMPLATES";
export const STORE_MILLING_LOOT_TEMPLATE = "STORE_MILLING_LOOT_TEMPLATE";
export const FIND_MILLING_LOOT_TEMPLATE = "FIND_MILLING_LOOT_TEMPLATE";
export const UPDATE_MILLING_LOOT_TEMPLATE = "UPDATE_MILLING_LOOT_TEMPLATE";
export const DESTROY_MILLING_LOOT_TEMPLATE = "DESTROY_MILLING_LOOT_TEMPLATE";
export const CREATE_MILLING_LOOT_TEMPLATE = "CREATE_MILLING_LOOT_TEMPLATE";
export const COPY_MILLING_LOOT_TEMPLATE = "COPY_MILLING_LOOT_TEMPLATE";

export const SEARCH_REFERENCE_LOOT_TEMPLATES =
  "SEARCH_REFERENCE_LOOT_TEMPLATES";
export const COUNT_REFERENCE_LOOT_TEMPLATES = "COUNT_REFERENCE_LOOT_TEMPLATES";
export const PAGINATE_REFERENCE_LOOT_TEMPLATES =
  "PAGINATE_REFERENCE_LOOT_TEMPLATES";
export const STORE_REFERENCE_LOOT_TEMPLATE = "STORE_REFERENCE_LOOT_TEMPLATE";
export const FIND_REFERENCE_LOOT_TEMPLATE = "FIND_REFERENCE_LOOT_TEMPLATE";
export const UPDATE_REFERENCE_LOOT_TEMPLATE = "UPDATE_REFERENCE_LOOT_TEMPLATE";
export const DESTROY_REFERENCE_LOOT_TEMPLATE =
  "DESTROY_REFERENCE_LOOT_TEMPLATE";
export const CREATE_REFERENCE_LOOT_TEMPLATE = "CREATE_REFERENCE_LOOT_TEMPLATE";
export const COPY_REFERENCE_LOOT_TEMPLATE = "COPY_REFERENCE_LOOT_TEMPLATE";

export const SEARCH_GAME_OBJECT_TEMPLATES = "SEARCH_GAME_OBJECT_TEMPLATES";
export const COUNT_GAME_OBJECT_TEMPLATES = "COUNT_GAME_OBJECT_TEMPLATES";
export const PAGINATE_GAME_OBJECT_TEMPLATES = "PAGINATE_GAME_OBJECT_TEMPLATES";
export const STORE_GAME_OBJECT_TEMPLATE = "STORE_GAME_OBJECT_TEMPLATE";
export const FIND_GAME_OBJECT_TEMPLATE = "FIND_GAME_OBJECT_TEMPLATE";
export const UPDATE_GAME_OBJECT_TEMPLATE = "UPDATE_GAME_OBJECT_TEMPLATE";
export const DESTROY_GAME_OBJECT_TEMPLATE = "DESTROY_GAME_OBJECT_TEMPLATE";
export const CREATE_GAME_OBJECT_TEMPLATE = "CREATE_GAME_OBJECT_TEMPLATE";
export const COPY_GAME_OBJECT_TEMPLATE = "COPY_GAME_OBJECT_TEMPLATE";

export const SEARCH_GAME_OBJECT_TEMPLATE_LOCALES =
  "SEARCH_GAME_OBJECT_TEMPLATE_LOCALES";
export const STORE_GAME_OBJECT_TEMPLATE_LOCALES =
  "STORE_GAME_OBJECT_TEMPLATE_LOCALES";

export const STORE_GAME_OBJECT_TEMPLATE_ADDON =
  "STORE_GAME_OBJECT_TEMPLATE_ADDON";
export const FIND_GAME_OBJECT_TEMPLATE_ADDON =
  "FIND_GAME_OBJECT_TEMPLATE_ADDON";
export const UPDATE_GAME_OBJECT_TEMPLATE_ADDON =
  "UPDATE_GAME_OBJECT_TEMPLATE_ADDON";
export const CREATE_GAME_OBJECT_TEMPLATE_ADDON =
  "CREATE_GAME_OBJECT_TEMPLATE_ADDON";

export const SEARCH_GAME_OBJECT_QUEST_ITEMS = "SEARCH_GAME_OBJECT_QUEST_ITEMS";
export const STORE_GAME_OBJECT_QUEST_ITEM = "STORE_GAME_OBJECT_QUEST_ITEM";
export const FIND_GAME_OBJECT_QUEST_ITEM = "FIND_GAME_OBJECT_QUEST_ITEM";
export const UPDATE_GAME_OBJECT_QUEST_ITEM = "UPDATE_GAME_OBJECT_QUEST_ITEM";
export const DESTROY_GAME_OBJECT_QUEST_ITEM = "DESTROY_GAME_OBJECT_QUEST_ITEM";
export const CREATE_GAME_OBJECT_QUEST_ITEM = "CREATE_GAME_OBJECT_QUEST_ITEM";
export const COPY_GAME_OBJECT_QUEST_ITEM = "COPY_GAME_OBJECT_QUEST_ITEM";

export const SEARCH_GAME_OBJECT_LOOT_TEMPLATES =
  "SEARCH_GAME_OBJECT_LOOT_TEMPLATES";
export const STORE_GAME_OBJECT_LOOT_TEMPLATE =
  "STORE_GAME_OBJECT_LOOT_TEMPLATE";
export const FIND_GAME_OBJECT_LOOT_TEMPLATE = "FIND_GAME_OBJECT_LOOT_TEMPLATE";
export const UPDATE_GAME_OBJECT_LOOT_TEMPLATE =
  "UPDATE_GAME_OBJECT_LOOT_TEMPLATE";
export const DESTROY_GAME_OBJECT_LOOT_TEMPLATE =
  "DESTROY_GAME_OBJECT_LOOT_TEMPLATE";
export const CREATE_GAME_OBJECT_LOOT_TEMPLATE =
  "CREATE_GAME_OBJECT_LOOT_TEMPLATE";
export const COPY_GAME_OBJECT_LOOT_TEMPLATE = "COPY_GAME_OBJECT_LOOT_TEMPLATE";

export const SEARCH_QUEST_TEMPLATES = "SEARCH_QUEST_TEMPLATES";
export const COUNT_QUEST_TEMPLATES = "COUNT_QUEST_TEMPLATES";
export const PAGINATE_QUEST_TEMPLATES = "PAGINATE_QUEST_TEMPLATES";
export const STORE_QUEST_TEMPLATE = "STORE_QUEST_TEMPLATE";
export const FIND_QUEST_TEMPLATE = "FIND_QUEST_TEMPLATE";
export const UPDATE_QUEST_TEMPLATE = "UPDATE_QUEST_TEMPLATE";
export const DESTROY_QUEST_TEMPLATE = "DESTROY_QUEST_TEMPLATE";
export const CREATE_QUEST_TEMPLATE = "CREATE_QUEST_TEMPLATE";
export const COPY_QUEST_TEMPLATE = "COPY_QUEST_TEMPLATE";

export const SEARCH_QUEST_TEMPLATE_LOCALES = "SEARCH_QUEST_TEMPLATE_LOCALES";
export const STORE_QUEST_TEMPLATE_LOCALES = "STORE_QUEST_TEMPLATE_LOCALES";

export const SEARCH_QUEST_OFFER_REWARD_LOCALES =
  "SEARCH_QUEST_OFFER_REWARD_LOCALES";
export const STORE_QUEST_OFFER_REWARD_LOCALES =
  "STORE_QUEST_OFFER_REWARD_LOCALES";

export const SEARCH_QUEST_REQUEST_ITEMS_LOCALES =
  "SEARCH_QUEST_REQUEST_ITEMS_LOCALES";
export const STORE_QUEST_REQUEST_ITEMS_LOCALES =
  "STORE_QUEST_REQUEST_ITEMS_LOCALES";

export const STORE_QUEST_TEMPLATE_ADDON = "STORE_QUEST_TEMPLATE_ADDON";
export const FIND_QUEST_TEMPLATE_ADDON = "FIND_QUEST_TEMPLATE_ADDON";
export const UPDATE_QUEST_TEMPLATE_ADDON = "UPDATE_QUEST_TEMPLATE_ADDON";
export const CREATE_QUEST_TEMPLATE_ADDON = "CREATE_QUEST_TEMPLATE_ADDON";

export const STORE_QUEST_OFFER_REWARD = "STORE_QUEST_OFFER_REWARD";
export const FIND_QUEST_OFFER_REWARD = "FIND_QUEST_OFFER_REWARD";
export const UPDATE_QUEST_OFFER_REWARD = "UPDATE_QUEST_OFFER_REWARD";
export const CREATE_QUEST_OFFER_REWARD = "CREATE_QUEST_OFFER_REWARD";

export const STORE_QUEST_REQUEST_ITEMS = "STORE_QUEST_REQUEST_ITEMS";
export const FIND_QUEST_REQUEST_ITEMS = "FIND_QUEST_REQUEST_ITEMS";
export const UPDATE_QUEST_REQUEST_ITEMS = "UPDATE_QUEST_REQUEST_ITEMS";
export const CREATE_QUEST_REQUEST_ITEMS = "CREATE_QUEST_REQUEST_ITEMS";

export const SEARCH_CREATURE_QUEST_STARTERS = "SEARCH_CREATURE_QUEST_STARTERS";
export const STORE_CREATURE_QUEST_STARTER = "STORE_CREATURE_QUEST_STARTER";
export const FIND_CREATURE_QUEST_STARTER = "FIND_CREATURE_QUEST_STARTER";
export const UPDATE_CREATURE_QUEST_STARTER = "UPDATE_CREATURE_QUEST_STARTER";
export const DESTROY_CREATURE_QUEST_STARTER = "DESTROY_CREATURE_QUEST_STARTER";
export const CREATE_CREATURE_QUEST_STARTER = "CREATE_CREATURE_QUEST_STARTER";
export const COPY_CREATURE_QUEST_STARTER = "COPY_CREATURE_QUEST_STARTER";

export const SEARCH_CREATURE_QUEST_ENDERS = "SEARCH_CREATURE_QUEST_ENDERS";
export const STORE_CREATURE_QUEST_ENDER = "STORE_CREATURE_QUEST_ENDER";
export const FIND_CREATURE_QUEST_ENDER = "FIND_CREATURE_QUEST_ENDER";
export const UPDATE_CREATURE_QUEST_ENDER = "UPDATE_CREATURE_QUEST_ENDER";
export const DESTROY_CREATURE_QUEST_ENDER = "DESTROY_CREATURE_QUEST_ENDER";
export const CREATE_CREATURE_QUEST_ENDER = "CREATE_CREATURE_QUEST_ENDER";
export const COPY_CREATURE_QUEST_ENDER = "COPY_CREATURE_QUEST_ENDER";

export const SEARCH_GAME_OBJECT_QUEST_STARTERS =
  "SEARCH_GAME_OBJECT_QUEST_STARTERS";
export const STORE_GAME_OBJECT_QUEST_STARTER =
  "STORE_GAME_OBJECT_QUEST_STARTER";
export const FIND_GAME_OBJECT_QUEST_STARTER = "FIND_GAME_OBJECT_QUEST_STARTER";
export const UPDATE_GAME_OBJECT_QUEST_STARTER =
  "UPDATE_GAME_OBJECT_QUEST_STARTER";
export const DESTROY_GAME_OBJECT_QUEST_STARTER =
  "DESTROY_GAME_OBJECT_QUEST_STARTER";
export const CREATE_GAME_OBJECT_QUEST_STARTER =
  "CREATE_GAME_OBJECT_QUEST_STARTER";
export const COPY_GAME_OBJECT_QUEST_STARTER = "COPY_GAME_OBJECT_QUEST_STARTER";

export const SEARCH_GAME_OBJECT_QUEST_ENDERS =
  "SEARCH_GAME_OBJECT_QUEST_ENDERS";
export const STORE_GAME_OBJECT_QUEST_ENDER = "STORE_GAME_OBJECT_QUEST_ENDER";
export const FIND_GAME_OBJECT_QUEST_ENDER = "FIND_GAME_OBJECT_QUEST_ENDER";
export const UPDATE_GAME_OBJECT_QUEST_ENDER = "UPDATE_GAME_OBJECT_QUEST_ENDER";
export const DESTROY_GAME_OBJECT_QUEST_ENDER =
  "DESTROY_GAME_OBJECT_QUEST_ENDER";
export const CREATE_GAME_OBJECT_QUEST_ENDER = "CREATE_GAME_OBJECT_QUEST_ENDER";
export const COPY_GAME_OBJECT_QUEST_ENDER = "COPY_GAME_OBJECT_QUEST_ENDER";

export const SEARCH_SMART_SCRIPTS = "SEARCH_SMART_SCRIPTS";
export const COUNT_SMART_SCRIPTS = "COUNT_SMART_SCRIPTS";
export const PAGINATE_SMART_SCRIPTS = "PAGINATE_SMART_SCRIPTS";
export const STORE_SMART_SCRIPT = "STORE_SMART_SCRIPT";
export const FIND_SMART_SCRIPT = "FIND_SMART_SCRIPT";
export const UPDATE_SMART_SCRIPT = "UPDATE_SMART_SCRIPT";
export const DESTROY_SMART_SCRIPT = "DESTROY_SMART_SCRIPT";
export const CREATE_SMART_SCRIPT = "CREATE_SMART_SCRIPT";
export const COPY_SMART_SCRIPT = "COPY_SMART_SCRIPT";

export const SEARCH_SPELLS = "SEARCH_SPELLS";
export const COUNT_SPELLS = "COUNT_SPELLS";
export const PAGINATE_SPELLS = "PAGINATE_SPELLS";
export const STORE_SPELL = "STORE_SPELL";
export const FIND_SPELL = "FIND_SPELL";
export const UPDATE_SPELL = "UPDATE_SPELL";
export const DESTROY_SPELL = "DESTROY_SPELL";
export const CREATE_SPELL = "CREATE_SPELL";
export const COPY_SPELL = "COPY_SPELL";

export const SEARCH_GOSSIP_MENUS = "SEARCH_GOSSIP_MENUS";
export const COUNT_GOSSIP_MENUS = "COUNT_GOSSIP_MENUS";
export const PAGINATE_GOSSIP_MENUS = "PAGINATE_GOSSIP_MENUS";
export const STORE_GOSSIP_MENU = "STORE_GOSSIP_MENU";
export const FIND_GOSSIP_MENU = "FIND_GOSSIP_MENU";
export const UPDATE_GOSSIP_MENU = "UPDATE_GOSSIP_MENU";
export const DESTROY_GOSSIP_MENU = "DESTROY_GOSSIP_MENU";
export const CREATE_GOSSIP_MENU = "CREATE_GOSSIP_MENU";
export const COPY_GOSSIP_MENU = "COPY_GOSSIP_MENU";

export const STORE_NPC_TEXT = "STORE_NPC_TEXT";
export const FIND_NPC_TEXT = "FIND_NPC_TEXT";
export const UPDATE_NPC_TEXT = "UPDATE_NPC_TEXT";
export const CREATE_NPC_TEXT = "CREATE_NPC_TEXT";

export const SEARCH_NPC_TEXT_LOCALES = "SEARCH_NPC_TEXT_LOCALES";
export const STORE_NPC_TEXT_LOCALES = "STORE_NPC_TEXT_LOCALES";

export const SEARCH_GOSSIP_MENU_OPTIONS = "SEARCH_GOSSIP_MENU_OPTIONS";
export const STORE_GOSSIP_MENU_OPTION = "STORE_GOSSIP_MENU_OPTION";
export const FIND_GOSSIP_MENU_OPTION = "FIND_GOSSIP_MENU_OPTION";
export const UPDATE_GOSSIP_MENU_OPTION = "UPDATE_GOSSIP_MENU_OPTION";
export const DESTROY_GOSSIP_MENU_OPTION = "DESTROY_GOSSIP_MENU_OPTION";
export const CREATE_GOSSIP_MENU_OPTION = "CREATE_GOSSIP_MENU_OPTION";
export const COPY_GOSSIP_MENU_OPTION = "COPY_GOSSIP_MENU_OPTION";

export const SEARCH_REFERENCE_LOOT_TEMPLATES_FOR_CARD =
  "SEARCH_REFERENCE_LOOT_TEMPLATES_FOR_CARD";
export const STORE_REFERENCE_LOOT_TEMPLATE_FOR_CARD =
  "STORE_REFERENCE_LOOT_TEMPLATE_FOR_CARD";
export const FIND_REFERENCE_LOOT_TEMPLATE_FOR_CARD =
  "FIND_REFERENCE_LOOT_TEMPLATE_FOR_CARD";
export const UPDATE_REFERENCE_LOOT_TEMPLATE_FOR_CARD =
  "UPDATE_REFERENCE_LOOT_TEMPLATE_FOR_CARD";
export const DESTROY_REFERENCE_LOOT_TEMPLATE_FOR_CARD =
  "DESTROY_REFERENCE_LOOT_TEMPLATE_FOR_CARD";
export const CREATE_REFERENCE_LOOT_TEMPLATE_FOR_CARD =
  "CREATE_REFERENCE_LOOT_TEMPLATE_FOR_CARD";
export const COPY_REFERENCE_LOOT_TEMPLATE_FOR_CARD =
  "COPY_REFERENCE_LOOT_TEMPLATE_FOR_CARD";

export const SEARCH_ACHIEVEMENT_CATEGORIES_FOR_SELECTOR =
  "SEARCH_ACHIEVEMENT_CATEGORIES_FOR_SELECTOR";
export const COUNT_ACHIEVEMENT_CATEGORIES_FOR_SELECTOR =
  "COUNT_ACHIEVEMENT_CATEGORIES_FOR_SELECTOR";
export const PAGINATE_ACHIEVEMENT_CATEGORIES_FOR_SELECTOR =
  "PAGINATE_ACHIEVEMENT_CATEGORIES_FOR_SELECTOR";

export const SEARCH_CURRENCY_CATEGORIES_FOR_SELECTOR =
  "SEARCH_CURRENCY_CATEGORIES_FOR_SELECTOR";
export const COUNT_CURRENCY_CATEGORIES_FOR_SELECTOR =
  "COUNT_CURRENCY_CATEGORIES_FOR_SELECTOR";
export const PAGINATE_CURRENCY_CATEGORIES_FOR_SELECTOR =
  "PAGINATE_CURRENCY_CATEGORIES_FOR_SELECTOR";

export const SEARCH_FACTIONS_FOR_SELECTOR = "SEARCH_FACTIONS_FOR_SELECTOR";
export const COUNT_FACTIONS_FOR_SELECTOR = "COUNT_FACTIONS_FOR_SELECTOR";
export const PAGINATE_FACTIONS_FOR_SELECTOR = "PAGINATE_FACTIONS_FOR_SELECTOR";

export const SEARCH_FACTION_TEMPLATES_FOR_SELECTOR =
  "SEARCH_FACTION_TEMPLATES_FOR_SELECTOR";
export const COUNT_FACTION_TEMPLATES_FOR_SELECTOR =
  "COUNT_FACTION_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_FACTION_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_FACTION_TEMPLATES_FOR_SELECTOR";

export const SEARCH_BROADCAST_TEXTS_FOR_SELECTOR =
  "SEARCH_BROADCAST_TEXTS_FOR_SELECTOR";
export const COUNT_BROADCAST_TEXTS_FOR_SELECTOR =
  "COUNT_BROADCAST_TEXTS_FOR_SELECTOR";
export const PAGINATE_BROADCAST_TEXTS_FOR_SELECTOR =
  "PAGINATE_BROADCAST_TEXTS_FOR_SELECTOR";

export const SEARCH_CREATURE_SPELL_DATAS_FOR_SELECTOR =
  "SEARCH_CREATURE_SPELL_DATAS_FOR_SELECTOR";
export const COUNT_CREATURE_SPELL_DATAS_FOR_SELECTOR =
  "COUNT_CREATURE_SPELL_DATAS_FOR_SELECTOR";
export const PAGINATE_CREATURE_SPELL_DATAS_FOR_SELECTOR =
  "PAGINATE_CREATURE_SPELL_DATAS_FOR_SELECTOR";

export const SEARCH_CREATURE_MODEL_INFOS_FOR_SELECTOR =
  "SEARCH_CREATURE_MODEL_INFOS_FOR_SELECTOR";
export const COUNT_CREATURE_MODEL_INFOS_FOR_SELECTOR =
  "COUNT_CREATURE_MODEL_INFOS_FOR_SELECTOR";
export const PAGINATE_CREATURE_MODEL_INFOS_FOR_SELECTOR =
  "PAGINATE_CREATURE_MODEL_INFOS_FOR_SELECTOR";

export const SEARCH_CREATURE_TEMPLATES_FOR_SELECTOR =
  "SEARCH_CREATURE_TEMPLATES_FOR_SELECTOR";
export const COUNT_CREATURE_TEMPLATES_FOR_SELECTOR =
  "COUNT_CREATURE_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_CREATURE_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_CREATURE_TEMPLATES_FOR_SELECTOR";

export const SEARCH_ITEM_EXTENDED_COSTS_FOR_SELECTOR =
  "SEARCH_ITEM_EXTENDED_COSTS_FOR_SELECTOR";
export const COUNT_ITEM_EXTENDED_COSTS_FOR_SELECTOR =
  "COUNT_ITEM_EXTENDED_COSTS_FOR_SELECTOR";
export const PAGINATE_ITEM_EXTENDED_COSTS_FOR_SELECTOR =
  "PAGINATE_ITEM_EXTENDED_COSTS_FOR_SELECTOR";

export const SEARCH_SPELLS_FOR_SELECTOR = "SEARCH_SPELLS_FOR_SELECTOR";
export const COUNT_SPELLS_FOR_SELECTOR = "COUNT_SPELLS_FOR_SELECTOR";
export const PAGINATE_SPELLS_FOR_SELECTOR = "PAGINATE_SPELLS_FOR_SELECTOR";

export const SEARCH_SPELL_CAST_TIMES_FOR_SELECTOR =
  "SEARCH_SPELL_CAST_TIMES_FOR_SELECTOR";
export const COUNT_SPELL_CAST_TIMES_FOR_SELECTOR =
  "COUNT_SPELL_CAST_TIMES_FOR_SELECTOR";
export const PAGINATE_SPELL_CAST_TIMES_FOR_SELECTOR =
  "PAGINATE_SPELL_CAST_TIMES_FOR_SELECTOR";

export const SEARCH_SPELL_CATEGORIES_FOR_SELECTOR =
  "SEARCH_SPELL_CATEGORIES_FOR_SELECTOR";
export const COUNT_SPELL_CATEGORIES_FOR_SELECTOR =
  "COUNT_SPELL_CATEGORIES_FOR_SELECTOR";
export const PAGINATE_SPELL_CATEGORIES_FOR_SELECTOR =
  "PAGINATE_SPELL_CATEGORIES_FOR_SELECTOR";

export const SEARCH_SPELL_DESCRIPTION_VARIABLES_FOR_SELECTOR =
  "SEARCH_SPELL_DESCRIPTION_VARIABLES_FOR_SELECTOR";
export const COUNT_SPELL_DESCRIPTION_VARIABLES_FOR_SELECTOR =
  "COUNT_SPELL_DESCRIPTION_VARIABLES_FOR_SELECTOR";
export const PAGINATE_SPELL_DESCRIPTION_VARIABLES_FOR_SELECTOR =
  "PAGINATE_SPELL_DESCRIPTION_VARIABLES_FOR_SELECTOR";

export const SEARCH_SPELL_DIFFICULTIES_FOR_SELECTOR =
  "SEARCH_SPELL_DIFFICULTIES_FOR_SELECTOR";
export const COUNT_SPELL_DIFFICULTIES_FOR_SELECTOR =
  "COUNT_SPELL_DIFFICULTIES_FOR_SELECTOR";
export const PAGINATE_SPELL_DIFFICULTIES_FOR_SELECTOR =
  "PAGINATE_SPELL_DIFFICULTIES_FOR_SELECTOR";

export const SEARCH_SPELL_DURATIONS_FOR_SELECTOR =
  "SEARCH_SPELL_DURATIONS_FOR_SELECTOR";
export const COUNT_SPELL_DURATIONS_FOR_SELECTOR =
  "COUNT_SPELL_DURATIONS_FOR_SELECTOR";
export const PAGINATE_SPELL_DURATIONS_FOR_SELECTOR =
  "PAGINATE_SPELL_DURATIONS_FOR_SELECTOR";

export const SEARCH_SPELL_RANGES_FOR_SELECTOR =
  "SEARCH_SPELL_RANGES_FOR_SELECTOR";
export const COUNT_SPELL_RANGES_FOR_SELECTOR =
  "COUNT_SPELL_RANGES_FOR_SELECTOR";
export const PAGINATE_SPELL_RANGES_FOR_SELECTOR =
  "PAGINATE_SPELL_RANGES_FOR_SELECTOR";

export const SEARCH_SPELL_AREAS = "SEARCH_SPELL_AREAS";
export const STORE_SPELL_AREA = "STORE_SPELL_AREA";
export const FIND_SPELL_AREA = "FIND_SPELL_AREA";
export const UPDATE_SPELL_AREA = "UPDATE_SPELL_AREA";
export const DESTROY_SPELL_AREA = "DESTROY_SPELL_AREA";
export const CREATE_SPELL_AREA = "CREATE_SPELL_AREA";
export const COPY_SPELL_AREA = "COPY_SPELL_AREA";

export const STORE_SPELL_BONUS_DATA = "STORE_SPELL_BONUS_DATA";
export const FIND_SPELL_BONUS_DATA = "FIND_SPELL_BONUS_DATA";
export const UPDATE_SPELL_BONUS_DATA = "UPDATE_SPELL_BONUS_DATA";
export const CREATE_SPELL_BONUS_DATA = "CREATE_SPELL_BONUS_DATA";

export const STORE_SPELL_CUSTOM_ATTR = "STORE_SPELL_CUSTOM_ATTR";
export const FIND_SPELL_CUSTOM_ATTR = "FIND_SPELL_CUSTOM_ATTR";
export const UPDATE_SPELL_CUSTOM_ATTR = "UPDATE_SPELL_CUSTOM_ATTR";
export const CREATE_SPELL_CUSTOM_ATTR = "CREATE_SPELL_CUSTOM_ATTR";

export const SEARCH_SPELL_GROUPS = "SEARCH_SPELL_GROUPS";
export const STORE_SPELL_GROUP = "STORE_SPELL_GROUP";
export const FIND_SPELL_GROUP = "FIND_SPELL_GROUP";
export const UPDATE_SPELL_GROUP = "UPDATE_SPELL_GROUP";
export const DESTROY_SPELL_GROUP = "DESTROY_SPELL_GROUP";
export const CREATE_SPELL_GROUP = "CREATE_SPELL_GROUP";
export const COPY_SPELL_GROUP = "COPY_SPELL_GROUP";

export const SEARCH_SPELL_LINKED_SPELLS = "SEARCH_SPELL_LINKED_SPELLS";
export const STORE_SPELL_LINKED_SPELL = "STORE_SPELL_LINKED_SPELL";
export const FIND_SPELL_LINKED_SPELL = "FIND_SPELL_LINKED_SPELL";
export const UPDATE_SPELL_LINKED_SPELL = "UPDATE_SPELL_LINKED_SPELL";
export const DESTROY_SPELL_LINKED_SPELL = "DESTROY_SPELL_LINKED_SPELL";
export const CREATE_SPELL_LINKED_SPELL = "CREATE_SPELL_LINKED_SPELL";
export const COPY_SPELL_LINKED_SPELL = "COPY_SPELL_LINKED_SPELL";

export const SEARCH_SPELL_LOOT_TEMPLATES = "SEARCH_SPELL_LOOT_TEMPLATES";
export const STORE_SPELL_LOOT_TEMPLATE = "STORE_SPELL_LOOT_TEMPLATE";
export const FIND_SPELL_LOOT_TEMPLATE = "FIND_SPELL_LOOT_TEMPLATE";
export const UPDATE_SPELL_LOOT_TEMPLATE = "UPDATE_SPELL_LOOT_TEMPLATE";
export const DESTROY_SPELL_LOOT_TEMPLATE = "DESTROY_SPELL_LOOT_TEMPLATE";
export const CREATE_SPELL_LOOT_TEMPLATE = "CREATE_SPELL_LOOT_TEMPLATE";
export const COPY_SPELL_LOOT_TEMPLATE = "COPY_SPELL_LOOT_TEMPLATE";

export const SEARCH_SCALING_STAT_DISTRIBUTIONS =
  "SEARCH_SCALING_STAT_DISTRIBUTIONS";
export const COUNT_SCALING_STAT_DISTRIBUTIONS =
  "COUNT_SCALING_STAT_DISTRIBUTIONS";
export const PAGINATE_SCALING_STAT_DISTRIBUTIONS =
  "PAGINATE_SCALING_STAT_DISTRIBUTIONS";
export const STORE_SCALING_STAT_DISTRIBUTION =
  "STORE_SCALING_STAT_DISTRIBUTION";
export const FIND_SCALING_STAT_DISTRIBUTION = "FIND_SCALING_STAT_DISTRIBUTION";
export const UPDATE_SCALING_STAT_DISTRIBUTION =
  "UPDATE_SCALING_STAT_DISTRIBUTION";
export const DESTROY_SCALING_STAT_DISTRIBUTION =
  "DESTROY_SCALING_STAT_DISTRIBUTION";
export const CREATE_SCALING_STAT_DISTRIBUTION =
  "CREATE_SCALING_STAT_DISTRIBUTION";
export const COPY_SCALING_STAT_DISTRIBUTION = "COPY_SCALING_STAT_DISTRIBUTION";

export const SEARCH_SCALING_STAT_VALUES = "SEARCH_SCALING_STAT_VALUES";
export const COUNT_SCALING_STAT_VALUES = "COUNT_SCALING_STAT_VALUES";
export const PAGINATE_SCALING_STAT_VALUES = "PAGINATE_SCALING_STAT_VALUES";
export const STORE_SCALING_STAT_VALUE = "STORE_SCALING_STAT_VALUE";
export const FIND_SCALING_STAT_VALUE = "FIND_SCALING_STAT_VALUE";
export const UPDATE_SCALING_STAT_VALUE = "UPDATE_SCALING_STAT_VALUE";
export const DESTROY_SCALING_STAT_VALUE = "DESTROY_SCALING_STAT_VALUE";
export const CREATE_SCALING_STAT_VALUE = "CREATE_SCALING_STAT_VALUE";
export const COPY_SCALING_STAT_VALUE = "COPY_SCALING_STAT_VALUE";

export const SEARCH_ACHIEVEMENTS = "SEARCH_ACHIEVEMENTS";
export const COUNT_ACHIEVEMENTS = "COUNT_ACHIEVEMENTS";
export const PAGINATE_ACHIEVEMENTS = "PAGINATE_ACHIEVEMENTS";
export const STORE_ACHIEVEMENT = "STORE_ACHIEVEMENT";
export const FIND_ACHIEVEMENT = "FIND_ACHIEVEMENT";
export const UPDATE_ACHIEVEMENT = "UPDATE_ACHIEVEMENT";
export const DESTROY_ACHIEVEMENT = "DESTROY_ACHIEVEMENT";
export const CREATE_ACHIEVEMENT = "CREATE_ACHIEVEMENT";
export const COPY_ACHIEVEMENT = "COPY_ACHIEVEMENT";

export const STORE_ACHIEVEMENT_CRITERIA = "STORE_ACHIEVEMENT_CRITERIA";
export const FIND_ACHIEVEMENT_CRITERIA = "FIND_ACHIEVEMENT_CRITERIA";
export const UPDATE_ACHIEVEMENT_CRITERIA = "UPDATE_ACHIEVEMENT_CRITERIA";
export const CREATE_ACHIEVEMENT_CRITERIA = "CREATE_ACHIEVEMENT_CRITERIA";

export const SEARCH_AREA_TABLES = "SEARCH_AREA_TABLES";
export const COUNT_AREA_TABLES = "COUNT_AREA_TABLES";
export const PAGINATE_AREA_TABLES = "PAGINATE_AREA_TABLES";
export const STORE_AREA_TABLE = "STORE_AREA_TABLE";
export const FIND_AREA_TABLE = "FIND_AREA_TABLE";
export const UPDATE_AREA_TABLE = "UPDATE_AREA_TABLE";
export const DESTROY_AREA_TABLE = "DESTROY_AREA_TABLE";
export const CREATE_AREA_TABLE = "CREATE_AREA_TABLE";
export const COPY_AREA_TABLE = "COPY_AREA_TABLE";

export const SEARCH_AREA_TABLES_FOR_SELECTOR =
  "SEARCH_AREA_TABLES_FOR_SELECTOR";
export const COUNT_AREA_TABLES_FOR_SELECTOR = "COUNT_AREA_TABLES_FOR_SELECTOR";
export const PAGINATE_AREA_TABLES_FOR_SELECTOR =
  "PAGINATE_AREA_TABLES_FOR_SELECTOR";

export const SEARCH_CONDITIONS = "SEARCH_CONDITIONS";
export const COUNT_CONDITIONS = "COUNT_CONDITIONS";
export const PAGINATE_CONDITIONS = "PAGINATE_CONDITIONS";
export const STORE_CONDITION = "STORE_CONDITION";
export const FIND_CONDITION = "FIND_CONDITION";
export const UPDATE_CONDITION = "UPDATE_CONDITION";
export const DESTROY_CONDITION = "DESTROY_CONDITION";
export const CREATE_CONDITION = "CREATE_CONDITION";
export const COPY_CONDITION = "COPY_CONDITION";

export const SEARCH_CURRENCY_TYPES = "SEARCH_CURRENCY_TYPES";
export const COUNT_CURRENCY_TYPES = "COUNT_CURRENCY_TYPES";
export const PAGINATE_CURRENCY_TYPES = "PAGINATE_CURRENCY_TYPES";
export const STORE_CURRENCY_TYPE = "STORE_CURRENCY_TYPE";
export const FIND_CURRENCY_TYPE = "FIND_CURRENCY_TYPE";
export const UPDATE_CURRENCY_TYPE = "UPDATE_CURRENCY_TYPE";
export const DESTROY_CURRENCY_TYPE = "DESTROY_CURRENCY_TYPE";
export const CREATE_CURRENCY_TYPE = "CREATE_CURRENCY_TYPE";
export const COPY_CURRENCY_TYPE = "COPY_CURRENCY_TYPE";

export const STORE_CURRENCY_CATEGORY = "STORE_CURRENCY_CATEGORY";
export const FIND_CURRENCY_CATEGORY = "FIND_CURRENCY_CATEGORY";
export const UPDATE_CURRENCY_CATEGORY = "UPDATE_CURRENCY_CATEGORY";
export const CREATE_CURRENCY_CATEGORY = "CREATE_CURRENCY_CATEGORY";

export const SEARCH_ITEM_EXTENDED_COSTS = "SEARCH_ITEM_EXTENDED_COSTS";
export const COUNT_ITEM_EXTENDED_COSTS = "COUNT_ITEM_EXTENDED_COSTS";
export const PAGINATE_ITEM_EXTENDED_COSTS = "PAGINATE_ITEM_EXTENDED_COSTS";
export const STORE_ITEM_EXTENDED_COST = "STORE_ITEM_EXTENDED_COST";
export const FIND_ITEM_EXTENDED_COST = "FIND_ITEM_EXTENDED_COST";
export const UPDATE_ITEM_EXTENDED_COST = "UPDATE_ITEM_EXTENDED_COST";
export const DESTROY_ITEM_EXTENDED_COST = "DESTROY_ITEM_EXTENDED_COST";
export const CREATE_ITEM_EXTENDED_COST = "CREATE_ITEM_EXTENDED_COST";
export const COPY_ITEM_EXTENDED_COST = "COPY_ITEM_EXTENDED_COST";

export const SEARCH_ITEM_SETS = "SEARCH_ITEM_SETS";
export const COUNT_ITEM_SETS = "COUNT_ITEM_SETS";
export const PAGINATE_ITEM_SETS = "PAGINATE_ITEM_SETS";
export const STORE_ITEM_SET = "STORE_ITEM_SET";
export const FIND_ITEM_SET = "FIND_ITEM_SET";
export const UPDATE_ITEM_SET = "UPDATE_ITEM_SET";
export const DESTROY_ITEM_SET = "DESTROY_ITEM_SET";
export const CREATE_ITEM_SET = "CREATE_ITEM_SET";
export const COPY_ITEM_SET = "COPY_ITEM_SET";

export const SEARCH_PAGE_TEXTS = "SEARCH_PAGE_TEXTS";
export const COUNT_PAGE_TEXTS = "COUNT_PAGE_TEXTS";
export const PAGINATE_PAGE_TEXTS = "PAGINATE_PAGE_TEXTS";
export const STORE_PAGE_TEXT = "STORE_PAGE_TEXT";
export const FIND_PAGE_TEXT = "FIND_PAGE_TEXT";
export const UPDATE_PAGE_TEXT = "UPDATE_PAGE_TEXT";
export const DESTROY_PAGE_TEXT = "DESTROY_PAGE_TEXT";
export const CREATE_PAGE_TEXT = "CREATE_PAGE_TEXT";
export const COPY_PAGE_TEXT = "COPY_PAGE_TEXT";

export const SEARCH_PAGE_TEXT_LOCALES = "SEARCH_PAGE_TEXT_LOCALES";
export const STORE_PAGE_TEXT_LOCALES = "STORE_PAGE_TEXT_LOCALES";

export const SEARCH_PAGE_TEXTS_FOR_SELECTOR = "SEARCH_PAGE_TEXTS_FOR_SELECTOR";
export const COUNT_PAGE_TEXTS_FOR_SELECTOR = "COUNT_PAGE_TEXTS_FOR_SELECTOR";
export const PAGINATE_PAGE_TEXTS_FOR_SELECTOR =
  "PAGINATE_PAGE_TEXTS_FOR_SELECTOR";

export const SEARCH_PLAYER_CREATE_INFOS = "SEARCH_PLAYER_CREATE_INFOS";
export const COUNT_PLAYER_CREATE_INFOS = "COUNT_PLAYER_CREATE_INFOS";
export const PAGINATE_PLAYER_CREATE_INFOS = "PAGINATE_PLAYER_CREATE_INFOS";
export const STORE_PLAYER_CREATE_INFO = "STORE_PLAYER_CREATE_INFO";
export const FIND_PLAYER_CREATE_INFO = "FIND_PLAYER_CREATE_INFO";
export const UPDATE_PLAYER_CREATE_INFO = "UPDATE_PLAYER_CREATE_INFO";
export const DESTROY_PLAYER_CREATE_INFO = "DESTROY_PLAYER_CREATE_INFO";
export const CREATE_PLAYER_CREATE_INFO = "CREATE_PLAYER_CREATE_INFO";
export const COPY_PLAYER_CREATE_INFO = "COPY_PLAYER_CREATE_INFO";

export const SEARCH_PLAYER_CREATE_INFO_ACTIONS =
  "SEARCH_PLAYER_CREATE_INFO_ACTIONS";
export const STORE_PLAYER_CREATE_INFO_ACTION =
  "STORE_PLAYER_CREATE_INFO_ACTION";
export const FIND_PLAYER_CREATE_INFO_ACTION = "FIND_PLAYER_CREATE_INFO_ACTION";
export const UPDATE_PLAYER_CREATE_INFO_ACTION =
  "UPDATE_PLAYER_CREATE_INFO_ACTION";
export const DESTROY_PLAYER_CREATE_INFO_ACTION =
  "DESTROY_PLAYER_CREATE_INFO_ACTION";
export const CREATE_PLAYER_CREATE_INFO_ACTION =
  "CREATE_PLAYER_CREATE_INFO_ACTION";
export const COPY_PLAYER_CREATE_INFO_ACTION = "COPY_PLAYER_CREATE_INFO_ACTION";

export const SEARCH_PLAYER_CREATE_INFO_ITEMS =
  "SEARCH_PLAYER_CREATE_INFO_ITEMS";
export const STORE_PLAYER_CREATE_INFO_ITEM = "STORE_PLAYER_CREATE_INFO_ITEM";
export const FIND_PLAYER_CREATE_INFO_ITEM = "FIND_PLAYER_CREATE_INFO_ITEM";
export const UPDATE_PLAYER_CREATE_INFO_ITEM = "UPDATE_PLAYER_CREATE_INFO_ITEM";
export const DESTROY_PLAYER_CREATE_INFO_ITEM =
  "DESTROY_PLAYER_CREATE_INFO_ITEM";
export const CREATE_PLAYER_CREATE_INFO_ITEM = "CREATE_PLAYER_CREATE_INFO_ITEM";
export const COPY_PLAYER_CREATE_INFO_ITEM = "COPY_PLAYER_CREATE_INFO_ITEM";

export const SEARCH_PLAYER_CREATE_INFO_SPELL_CUSTOMS =
  "SEARCH_PLAYER_CREATE_INFO_SPELL_CUSTOMS";
export const STORE_PLAYER_CREATE_INFO_SPELL_CUSTOM =
  "STORE_PLAYER_CREATE_INFO_SPELL_CUSTOM";
export const FIND_PLAYER_CREATE_INFO_SPELL_CUSTOM =
  "FIND_PLAYER_CREATE_INFO_SPELL_CUSTOM";
export const UPDATE_PLAYER_CREATE_INFO_SPELL_CUSTOM =
  "UPDATE_PLAYER_CREATE_INFO_SPELL_CUSTOM";
export const DESTROY_PLAYER_CREATE_INFO_SPELL_CUSTOM =
  "DESTROY_PLAYER_CREATE_INFO_SPELL_CUSTOM";
export const CREATE_PLAYER_CREATE_INFO_SPELL_CUSTOM =
  "CREATE_PLAYER_CREATE_INFO_SPELL_CUSTOM";
export const COPY_PLAYER_CREATE_INFO_SPELL_CUSTOM =
  "COPY_PLAYER_CREATE_INFO_SPELL_CUSTOM";

export const SEARCH_EMOTE_TEXTS = "SEARCH_EMOTE_TEXTS";
export const COUNT_EMOTE_TEXTS = "COUNT_EMOTE_TEXTS";
export const PAGINATE_EMOTE_TEXTS = "PAGINATE_EMOTE_TEXTS";
export const STORE_EMOTE_TEXT = "STORE_EMOTE_TEXT";
export const FIND_EMOTE_TEXT = "FIND_EMOTE_TEXT";
export const UPDATE_EMOTE_TEXT = "UPDATE_EMOTE_TEXT";
export const DESTROY_EMOTE_TEXT = "DESTROY_EMOTE_TEXT";
export const CREATE_EMOTE_TEXT = "CREATE_EMOTE_TEXT";
export const COPY_EMOTE_TEXT = "COPY_EMOTE_TEXT";

export const SEARCH_QUEST_FACTION_REWARDS = "SEARCH_QUEST_FACTION_REWARDS";
export const COUNT_QUEST_FACTION_REWARDS = "COUNT_QUEST_FACTION_REWARDS";
export const PAGINATE_QUEST_FACTION_REWARDS = "PAGINATE_QUEST_FACTION_REWARDS";
export const STORE_QUEST_FACTION_REWARD = "STORE_QUEST_FACTION_REWARD";
export const FIND_QUEST_FACTION_REWARD = "FIND_QUEST_FACTION_REWARD";
export const UPDATE_QUEST_FACTION_REWARD = "UPDATE_QUEST_FACTION_REWARD";
export const DESTROY_QUEST_FACTION_REWARD = "DESTROY_QUEST_FACTION_REWARD";
export const CREATE_QUEST_FACTION_REWARD = "CREATE_QUEST_FACTION_REWARD";
export const COPY_QUEST_FACTION_REWARD = "COPY_QUEST_FACTION_REWARD";

export const SEARCH_TALENTS = "SEARCH_TALENTS";
export const COUNT_TALENTS = "COUNT_TALENTS";
export const PAGINATE_TALENTS = "PAGINATE_TALENTS";
export const STORE_TALENT = "STORE_TALENT";
export const FIND_TALENT = "FIND_TALENT";
export const UPDATE_TALENT = "UPDATE_TALENT";
export const DESTROY_TALENT = "DESTROY_TALENT";
export const CREATE_TALENT = "CREATE_TALENT";
export const COPY_TALENT = "COPY_TALENT";

export const SEARCH_TALENT_TABS = "SEARCH_TALENT_TABS";
export const COUNT_TALENT_TABS = "COUNT_TALENT_TABS";
export const PAGINATE_TALENT_TABS = "PAGINATE_TALENT_TABS";
export const STORE_TALENT_TAB = "STORE_TALENT_TAB";
export const FIND_TALENT_TAB = "FIND_TALENT_TAB";
export const UPDATE_TALENT_TAB = "UPDATE_TALENT_TAB";
export const DESTROY_TALENT_TAB = "DESTROY_TALENT_TAB";
export const CREATE_TALENT_TAB = "CREATE_TALENT_TAB";
export const COPY_TALENT_TAB = "COPY_TALENT_TAB";

export const SEARCH_GOSSIP_MENUS_FOR_SELECTOR =
  "SEARCH_GOSSIP_MENUS_FOR_SELECTOR";
export const COUNT_GOSSIP_MENUS_FOR_SELECTOR =
  "COUNT_GOSSIP_MENUS_FOR_SELECTOR";
export const PAGINATE_GOSSIP_MENUS_FOR_SELECTOR =
  "PAGINATE_GOSSIP_MENUS_FOR_SELECTOR";

export const SEARCH_ITEM_TEMPLATES_FOR_SELECTOR =
  "SEARCH_ITEM_TEMPLATES_FOR_SELECTOR";
export const COUNT_ITEM_TEMPLATES_FOR_SELECTOR =
  "COUNT_ITEM_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_ITEM_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_ITEM_TEMPLATES_FOR_SELECTOR";

export const SEARCH_GAME_OBJECT_DISPLAY_INFOS_FOR_SELECTOR =
  "SEARCH_GAME_OBJECT_DISPLAY_INFOS_FOR_SELECTOR";
export const COUNT_GAME_OBJECT_DISPLAY_INFOS_FOR_SELECTOR =
  "COUNT_GAME_OBJECT_DISPLAY_INFOS_FOR_SELECTOR";
export const PAGINATE_GAME_OBJECT_DISPLAY_INFOS_FOR_SELECTOR =
  "PAGINATE_GAME_OBJECT_DISPLAY_INFOS_FOR_SELECTOR";

export const SEARCH_MAPS_FOR_SELECTOR = "SEARCH_MAPS_FOR_SELECTOR";
export const COUNT_MAPS_FOR_SELECTOR = "COUNT_MAPS_FOR_SELECTOR";
export const PAGINATE_MAPS_FOR_SELECTOR = "PAGINATE_MAPS_FOR_SELECTOR";

export const SEARCH_ITEM_SETS_FOR_SELECTOR = "SEARCH_ITEM_SETS_FOR_SELECTOR";
export const COUNT_ITEM_SETS_FOR_SELECTOR = "COUNT_ITEM_SETS_FOR_SELECTOR";
export const PAGINATE_ITEM_SETS_FOR_SELECTOR =
  "PAGINATE_ITEM_SETS_FOR_SELECTOR";

export const SEARCH_AREA_TABLES_FOR_ATOQS_SELECTOR =
  "SEARCH_AREA_TABLES_FOR_ATOQS_SELECTOR";
export const COUNT_AREA_TABLES_FOR_ATOQS_SELECTOR =
  "COUNT_AREA_TABLES_FOR_ATOQS_SELECTOR";
export const PAGINATE_AREA_TABLES_FOR_ATOQS_SELECTOR =
  "PAGINATE_AREA_TABLES_FOR_ATOQS_SELECTOR";

export const SEARCH_QUEST_SORTS_FOR_ATOQS_SELECTOR =
  "SEARCH_QUEST_SORTS_FOR_ATOQS_SELECTOR";
export const COUNT_QUEST_SORTS_FOR_ATOQS_SELECTOR =
  "COUNT_QUEST_SORTS_FOR_ATOQS_SELECTOR";
export const PAGINATE_QUEST_SORTS_FOR_ATOQS_SELECTOR =
  "PAGINATE_QUEST_SORTS_FOR_ATOQS_SELECTOR";

export const SEARCH_EMOTES_FOR_SELECTOR = "SEARCH_EMOTES_FOR_SELECTOR";
export const COUNT_EMOTES_FOR_SELECTOR = "COUNT_EMOTES_FOR_SELECTOR";
export const PAGINATE_EMOTES_FOR_SELECTOR = "PAGINATE_EMOTES_FOR_SELECTOR";

export const SEARCH_CHAR_TITLES_FOR_SELECTOR =
  "SEARCH_CHAR_TITLES_FOR_SELECTOR";
export const COUNT_CHAR_TITLES_FOR_SELECTOR = "COUNT_CHAR_TITLES_FOR_SELECTOR";
export const PAGINATE_CHAR_TITLES_FOR_SELECTOR =
  "PAGINATE_CHAR_TITLES_FOR_SELECTOR";

export const SEARCH_LOCKS_FOR_SELECTOR = "SEARCH_LOCKS_FOR_SELECTOR";
export const COUNT_LOCKS_FOR_SELECTOR = "COUNT_LOCKS_FOR_SELECTOR";
export const PAGINATE_LOCKS_FOR_SELECTOR = "PAGINATE_LOCKS_FOR_SELECTOR";

export const SEARCH_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR =
  "SEARCH_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR";
export const COUNT_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR =
  "COUNT_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR";
export const PAGINATE_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR =
  "PAGINATE_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR";

export const SEARCH_WAYPOINT_DATAS_FOR_SELECTOR =
  "SEARCH_WAYPOINT_DATAS_FOR_SELECTOR";
export const COUNT_WAYPOINT_DATAS_FOR_SELECTOR =
  "COUNT_WAYPOINT_DATAS_FOR_SELECTOR";
export const PAGINATE_WAYPOINT_DATAS_FOR_SELECTOR =
  "PAGINATE_WAYPOINT_DATAS_FOR_SELECTOR";

export const SEARCH_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR =
  "SEARCH_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR";
export const COUNT_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR =
  "COUNT_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR";

export const SEARCH_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR =
  "SEARCH_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR";
export const COUNT_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR =
  "COUNT_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR";
export const PAGINATE_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR =
  "PAGINATE_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR";

export const SEARCH_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR =
  "SEARCH_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR";
export const COUNT_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR =
  "COUNT_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR";
export const PAGINATE_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR =
  "PAGINATE_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR";

export const SEARCH_ITEM_DISPLAY_INFOS_FOR_SELECTOR =
  "SEARCH_ITEM_DISPLAY_INFOS_FOR_SELECTOR";
export const COUNT_ITEM_DISPLAY_INFOS_FOR_SELECTOR =
  "COUNT_ITEM_DISPLAY_INFOS_FOR_SELECTOR";
export const PAGINATE_ITEM_DISPLAY_INFOS_FOR_SELECTOR =
  "PAGINATE_ITEM_DISPLAY_INFOS_FOR_SELECTOR";

export const SEARCH_QUEST_INFOS = "SEARCH_QUEST_INFOS";
export const COUNT_QUEST_INFOS = "COUNT_QUEST_INFOS";
export const PAGINATE_QUEST_INFOS = "PAGINATE_QUEST_INFOS";
export const STORE_QUEST_INFO = "STORE_QUEST_INFO";
export const FIND_QUEST_INFO = "FIND_QUEST_INFO";
export const UPDATE_QUEST_INFO = "UPDATE_QUEST_INFO";
export const DESTROY_QUEST_INFO = "DESTROY_QUEST_INFO";
export const CREATE_QUEST_INFO = "CREATE_QUEST_INFO";
export const COPY_QUEST_INFO = "COPY_QUEST_INFO";

export const SEARCH_QUEST_SORTS = "SEARCH_QUEST_SORTS";
export const COUNT_QUEST_SORTS = "COUNT_QUEST_SORTS";
export const PAGINATE_QUEST_SORTS = "PAGINATE_QUEST_SORTS";
export const STORE_QUEST_SORT = "STORE_QUEST_SORT";
export const FIND_QUEST_SORT = "FIND_QUEST_SORT";
export const UPDATE_QUEST_SORT = "UPDATE_QUEST_SORT";
export const DESTROY_QUEST_SORT = "DESTROY_QUEST_SORT";
export const CREATE_QUEST_SORT = "CREATE_QUEST_SORT";
export const COPY_QUEST_SORT = "COPY_QUEST_SORT";

export const SEARCH_QUEST_INFOS_FOR_SELECTOR =
  "SEARCH_QUEST_INFOS_FOR_SELECTOR";
export const COUNT_QUEST_INFOS_FOR_SELECTOR = "COUNT_QUEST_INFOS_FOR_SELECTOR";
export const PAGINATE_QUEST_INFOS_FOR_SELECTOR =
  "PAGINATE_QUEST_INFOS_FOR_SELECTOR";

export const SEARCH_QUEST_TEMPLATES_FOR_SELECTOR =
  "SEARCH_QUEST_TEMPLATES_FOR_SELECTOR";
export const COUNT_QUEST_TEMPLATES_FOR_SELECTOR =
  "COUNT_QUEST_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_QUEST_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_QUEST_TEMPLATES_FOR_SELECTOR";

export const SEARCH_SPELL_ICONS_FOR_SELECTOR =
  "SEARCH_SPELL_ICONS_FOR_SELECTOR";
export const COUNT_SPELL_ICONS_FOR_SELECTOR = "COUNT_SPELL_ICONS_FOR_SELECTOR";
export const PAGINATE_SPELL_ICONS_FOR_SELECTOR =
  "PAGINATE_SPELL_ICONS_FOR_SELECTOR";

export const SEARCH_SPELL_ITEM_ENCHANTMENTS = "SEARCH_SPELL_ITEM_ENCHANTMENTS";
export const COUNT_SPELL_ITEM_ENCHANTMENTS = "COUNT_SPELL_ITEM_ENCHANTMENTS";
export const PAGINATE_SPELL_ITEM_ENCHANTMENTS =
  "PAGINATE_SPELL_ITEM_ENCHANTMENTS";
export const STORE_SPELL_ITEM_ENCHANTMENT = "STORE_SPELL_ITEM_ENCHANTMENT";
export const FIND_SPELL_ITEM_ENCHANTMENT = "FIND_SPELL_ITEM_ENCHANTMENT";
export const UPDATE_SPELL_ITEM_ENCHANTMENT = "UPDATE_SPELL_ITEM_ENCHANTMENT";
export const DESTROY_SPELL_ITEM_ENCHANTMENT = "DESTROY_SPELL_ITEM_ENCHANTMENT";
export const CREATE_SPELL_ITEM_ENCHANTMENT = "CREATE_SPELL_ITEM_ENCHANTMENT";
export const COPY_SPELL_ITEM_ENCHANTMENT = "COPY_SPELL_ITEM_ENCHANTMENT";

export const FIND_VERSION = "FIND_VERSION";
