export const FIND_LATEST_VERSION = "FIND_LATEST_VERSION";
export const STORE_MYSQL_CONFIG = "STORE_MYSQL_CONFIG";
export const STORE_DBC_CONFIG = "STORE_DBC_CONFIG";
export const STORE_CONFIG_CONFIG = "STORE_CONFIG_CONFIG";
export const STORE_DEVELOPER_CONFIG = "STORE_DEVELOPER_CONFIG";
export const SET_ACTIVE = "SET_ACTIVE";
export const GLOBAL_MESSAGE = "GLOBAL_MESSAGE";
export const GLOBAL_MESSAGE_BOX = "GLOBAL_MESSAGE_BOX";
export const SET_SETTING_ACTIVE = "SET_SETTING_ACTIVE";
export const INIT_MYSQL_CONNECTION = "INIT_MYSQL_CONNECTION";
export const TEST_MYSQL_CONNECTION = "TEST_MYSQL_CONNECTION";
export const INIT_DBC_CONFIG = "INIT_DBC_CONFIG";
export const START_IMPORT = "START_EXPORT";
export const START_EXPORT = "START_EXPORT";
export const EXPORT_ITEM_DBC = "EXPORT_ITEM_DBC";
export const EXPORT_SPELL_DBC = "EXPORT_SPELL_DBC";
export const EXPORT_SCALING_STAT_DISTRIBUTION_DBC =
  "EXPORT_SCALING_STAT_DISTRIBUTION_DBC";

export const SEARCH_DBC_FACTIONS = "SEARCH_DBC_FACTIONS";
export const SEARCH_DBC_FACTION_TEMPLATES = "SEARCH_DBC_FACTION_TEMPLATES";
export const SEARCH_DBC_CREATURE_SPELL_DATAS =
  "SEARCH_DBC_CREATURE_SPELL_DATAS";
export const SEARCH_DBC_CREATURE_DISPLAY_INFOS =
  "SEARCH_DBC_CREATURE_DISPLAY_INFOS";
export const SEARCH_DBC_CREATURE_MODEL_DATAS =
  "SEARCH_DBC_CREATURE_MODEL_DATAS";
export const SEARCH_DBC_ITEM_DISPLAY_INFOS = "SEARCH_DBC_ITEM_DISPLAY_INFOS";
export const SEARCH_DBC_ITEMS = "SEARCH_DBC_ITEMS";
export const SEARCH_DBC_SPELLS = "SEARCH_DBC_SPELLS";
export const SEARCH_DBC_SPELL_DURATIONS = "SEARCH_DBC_SPELL_DURATIONS";
export const SEARCH_DBC_SCALING_STAT_DISTRIBUTIONS =
  "SEARCH_DBC_SCALING_STAT_DISTRIBUTIONS";
export const SEARCH_DBC_SCALING_STAT_VALUES = "SEARCH_DBC_SCALING_STAT_VALUES";
export const SEARCH_DBC_ITEM_SETS = "SEARCH_DBC_ITEM_SETS";
export const SEARCH_DBC_SPELL_ITEM_ENCHANTMENTS =
  "SEARCH_DBC_SPELL_ITEM_ENCHANTMENTS";
export const SEARCH_DBC_ITEM_RANDOM_PROPERTITIES =
  "SEARCH_DBC_ITEM_RANDOM_PROPERTITIES";
export const SEARCH_DBC_ITEM_RANDOM_SUFFIXES =
  "SEARCH_DBC_ITEM_RANDOM_SUFFIXES";
export const SEARCH_DBC_SPELL_CAST_TIMES = "SEARCH_DBC_SPELL_CAST_TIMES";
export const SEARCH_DBC_SPELL_RANGES = "SEARCH_DBC_SPELL_RANGES";

export const SEARCH_CREATURE_TEMPLATES = "SEARCH_CREATURE_TEMPLATES";
export const COUNT_CREATURE_TEMPLATES = "COUNT_CREATURE_TEMPLATES";
export const PAGINATE_CREATURE_TEMPLATES = "PAGINATE_CREATURE_TEMPLATES";
export const STORE_CREATURE_TEMPLATE = "STORE_CREATURE_TEMPLATE";
export const FIND_CREATURE_TEMPLATE = "FIND_CREATURE_TEMPLATE";
export const UPDATE_CREATURE_TEMPLATE = "UPDATE_CREATURE_TEMPLATE";
export const DESTROY_CREATURE_TEMPLATE = "DESTROY_CREATURE_TEMPLATE";
export const CREATE_CREATURE_TEMPLATE = "CREATE_CREATURE_TEMPLATE";
export const COPY_CREATURE_TEMPLATE = "COPY_CREATURE_TEMPLATE";

export const SEARCH_CREATURE_TEMPLATE_LOCALES =
  "SEARCH_CREATURE_TEMPLATE_LOCALES";
export const STORE_CREATURE_TEMPLATE_LOCALES =
  "STORE_CREATURE_TEMPLATE_LOCALES";

export const STORE_CREATURE_TEMPLATE_ADDON = "STORE_CREATURE_TEMPLATE_ADDON";
export const FIND_CREATURE_TEMPLATE_ADDON = "FIND_CREATURE_TEMPLATE_ADDON";
export const UPDATE_CREATURE_TEMPLATE_ADDON = "UPDATE_CREATURE_TEMPLATE_ADDON";
export const CREATE_CREATURE_TEMPLATE_ADDON = "CREATE_CREATURE_TEMPLATE_ADDON";

export const SEARCH_CREATURE_TEMPLATE_RESISTANCES =
  "SEARCH_CREATURE_TEMPLATE_RESISTANCES";
export const STORE_CREATURE_TEMPLATE_RESISTANCE =
  "STORE_CREATURE_TEMPLATE_RESISTANCE";
export const FIND_CREATURE_TEMPLATE_RESISTANCE =
  "FIND_CREATURE_TEMPLATE_RESISTANCE";
export const UPDATE_CREATURE_TEMPLATE_RESISTANCE =
  "UPDATE_CREATURE_TEMPLATE_RESISTANCE";
export const DESTROY_CREATURE_TEMPLATE_RESISTANCE =
  "DESTROY_CREATURE_TEMPLATE_RESISTANCE";
export const CREATE_CREATURE_TEMPLATE_RESISTANCE =
  "CREATE_CREATURE_TEMPLATE_RESISTANCE";
export const COPY_CREATURE_TEMPLATE_RESISTANCE =
  "COPY_CREATURE_TEMPLATE_RESISTANCE";

export const SEARCH_CREATURE_TEMPLATE_SPELLS =
  "SEARCH_CREATURE_TEMPLATE_SPELLS";
export const STORE_CREATURE_TEMPLATE_SPELL = "STORE_CREATURE_TEMPLATE_SPELL";
export const FIND_CREATURE_TEMPLATE_SPELL = "FIND_CREATURE_TEMPLATE_SPELL";
export const UPDATE_CREATURE_TEMPLATE_SPELL = "UPDATE_CREATURE_TEMPLATE_SPELL";
export const DESTROY_CREATURE_TEMPLATE_SPELL =
  "DESTROY_CREATURE_TEMPLATE_SPELL";
export const CREATE_CREATURE_TEMPLATE_SPELL = "CREATE_CREATURE_TEMPLATE_SPELL";
export const COPY_CREATURE_TEMPLATE_SPELL = "COPY_CREATURE_TEMPLATE_SPELL";

export const STORE_CREATURE_ONKILL_REPUTATION =
  "STORE_CREATURE_ONKILL_REPUTATION";
export const FIND_CREATURE_ONKILL_REPUTATION =
  "FIND_CREATURE_ONKILL_REPUTATION";
export const UPDATE_CREATURE_ONKILL_REPUTATION =
  "UPDATE_CREATURE_ONKILL_REPUTATION";
export const CREATE_CREATURE_ONKILL_REPUTATION =
  "CREATE_CREATURE_ONKILL_REPUTATION";

export const SEARCH_CREATURE_EQUIP_TEMPLATES =
  "SEARCH_CREATURE_EQUIP_TEMPLATES";
export const STORE_CREATURE_EQUIP_TEMPLATE = "STORE_CREATURE_EQUIP_TEMPLATE";
export const FIND_CREATURE_EQUIP_TEMPLATE = "FIND_CREATURE_EQUIP_TEMPLATE";
export const UPDATE_CREATURE_EQUIP_TEMPLATE = "UPDATE_CREATURE_EQUIP_TEMPLATE";
export const DESTROY_CREATURE_EQUIP_TEMPLATE =
  "DESTROY_CREATURE_EQUIP_TEMPLATE";
export const CREATE_CREATURE_EQUIP_TEMPLATE = "CREATE_CREATURE_EQUIP_TEMPLATE";
export const COPY_CREATURE_EQUIP_TEMPLATE = "COPY_CREATURE_EQUIP_TEMPLATE";

export const SEARCH_CREATURE_QUEST_ITEMS = "SEARCH_CREATURE_QUEST_ITEMS";
export const STORE_CREATURE_QUEST_ITEM = "STORE_CREATURE_QUEST_ITEM";
export const FIND_CREATURE_QUEST_ITEM = "FIND_CREATURE_QUEST_ITEM";
export const UPDATE_CREATURE_QUEST_ITEM = "UPDATE_CREATURE_QUEST_ITEM";
export const DESTROY_CREATURE_QUEST_ITEM = "DESTROY_CREATURE_QUEST_ITEM";
export const CREATE_CREATURE_QUEST_ITEM = "CREATE_CREATURE_QUEST_ITEM";
export const COPY_CREATURE_QUEST_ITEM = "COPY_CREATURE_QUEST_ITEM";

export const SEARCH_NPC_VENDORS = "SEARCH_NPC_VENDORS";
export const STORE_NPC_VENDOR = "STORE_NPC_VENDOR";
export const FIND_NPC_VENDOR = "FIND_NPC_VENDOR";
export const UPDATE_NPC_VENDOR = "UPDATE_NPC_VENDOR";
export const DESTROY_NPC_VENDOR = "DESTROY_NPC_VENDOR";
export const CREATE_NPC_VENDOR = "CREATE_NPC_VENDOR";
export const COPY_NPC_VENDOR = "COPY_NPC_VENDOR";

export const SEARCH_NPC_TRAINERS = "SEARCH_NPC_TRAINERS";
export const STORE_NPC_TRAINER = "STORE_NPC_TRAINER";
export const FIND_NPC_TRAINER = "FIND_NPC_TRAINER";
export const UPDATE_NPC_TRAINER = "UPDATE_NPC_TRAINER";
export const DESTROY_NPC_TRAINER = "DESTROY_NPC_TRAINER";
export const CREATE_NPC_TRAINER = "CREATE_NPC_TRAINER";
export const COPY_NPC_TRAINER = "COPY_NPC_TRAINER";

export const SEARCH_CREATURE_LOOT_TEMPLATES = "SEARCH_CREATURE_LOOT_TEMPLATES";
export const STORE_CREATURE_LOOT_TEMPLATE = "STORE_CREATURE_LOOT_TEMPLATE";
export const FIND_CREATURE_LOOT_TEMPLATE = "FIND_CREATURE_LOOT_TEMPLATE";
export const UPDATE_CREATURE_LOOT_TEMPLATE = "UPDATE_CREATURE_LOOT_TEMPLATE";
export const DESTROY_CREATURE_LOOT_TEMPLATE = "DESTROY_CREATURE_LOOT_TEMPLATE";
export const CREATE_CREATURE_LOOT_TEMPLATE = "CREATE_CREATURE_LOOT_TEMPLATE";
export const COPY_CREATURE_LOOT_TEMPLATE = "COPY_CREATURE_LOOT_TEMPLATE";

export const SEARCH_PICKPOCKETING_LOOT_TEMPLATES =
  "SEARCH_PICKPOCKETING_LOOT_TEMPLATES";
export const STORE_PICKPOCKETING_LOOT_TEMPLATE =
  "STORE_PICKPOCKETING_LOOT_TEMPLATE";
export const FIND_PICKPOCKETING_LOOT_TEMPLATE =
  "FIND_PICKPOCKETING_LOOT_TEMPLATE";
export const UPDATE_PICKPOCKETING_LOOT_TEMPLATE =
  "UPDATE_PICKPOCKETING_LOOT_TEMPLATE";
export const DESTROY_PICKPOCKETING_LOOT_TEMPLATE =
  "DESTROY_PICKPOCKETING_LOOT_TEMPLATE";
export const CREATE_PICKPOCKETING_LOOT_TEMPLATE =
  "CREATE_PICKPOCKETING_LOOT_TEMPLATE";
export const COPY_PICKPOCKETING_LOOT_TEMPLATE =
  "COPY_PICKPOCKETING_LOOT_TEMPLATE";

export const SEARCH_SKINNING_LOOT_TEMPLATES = "SEARCH_SKINNING_LOOT_TEMPLATES";
export const STORE_SKINNING_LOOT_TEMPLATE = "STORE_SKINNING_LOOT_TEMPLATE";
export const FIND_SKINNING_LOOT_TEMPLATE = "FIND_SKINNING_LOOT_TEMPLATE";
export const UPDATE_SKINNING_LOOT_TEMPLATE = "UPDATE_SKINNING_LOOT_TEMPLATE";
export const DESTROY_SKINNING_LOOT_TEMPLATE = "DESTROY_SKINNING_LOOT_TEMPLATE";
export const CREATE_SKINNING_LOOT_TEMPLATE = "CREATE_SKINNING_LOOT_TEMPLATE";
export const COPY_SKINNING_LOOT_TEMPLATE = "COPY_SKINNING_LOOT_TEMPLATE";

export const SEARCH_ITEM_TEMPLATES = "SEARCH_ITEM_TEMPLATES";
export const COUNT_ITEM_TEMPLATES = "COUNT_ITEM_TEMPLATES";
export const PAGINATE_ITEM_TEMPLATES = "PAGINATE_ITEM_TEMPLATES";
export const STORE_ITEM_TEMPLATE = "STORE_ITEM_TEMPLATE";
export const FIND_ITEM_TEMPLATE = "FIND_ITEM_TEMPLATE";
export const UPDATE_ITEM_TEMPLATE = "UPDATE_ITEM_TEMPLATE";
export const DESTROY_ITEM_TEMPLATE = "DESTROY_ITEM_TEMPLATE";
export const CREATE_ITEM_TEMPLATE = "CREATE_ITEM_TEMPLATE";
export const COPY_ITEM_TEMPLATE = "COPY_ITEM_TEMPLATE";

export const SEARCH_ITEM_TEMPLATE_LOCALES = "SEARCH_ITEM_TEMPLATE_LOCALES";
export const STORE_ITEM_TEMPLATE_LOCALES = "STORE_ITEM_TEMPLATE_LOCALES";

export const SEARCH_ITEM_ENCHANTMENT_TEMPLATES =
  "SEARCH_ITEM_ENCHANTMENT_TEMPLATES";
export const STORE_ITEM_ENCHANTMENT_TEMPLATE =
  "STORE_ITEM_ENCHANTMENT_TEMPLATE";
export const FIND_ITEM_ENCHANTMENT_TEMPLATE = "FIND_ITEM_ENCHANTMENT_TEMPLATE";
export const UPDATE_ITEM_ENCHANTMENT_TEMPLATE =
  "UPDATE_ITEM_ENCHANTMENT_TEMPLATE";
export const DESTROY_ITEM_ENCHANTMENT_TEMPLATE =
  "DESTROY_ITEM_ENCHANTMENT_TEMPLATE";
export const CREATE_ITEM_ENCHANTMENT_TEMPLATE =
  "CREATE_ITEM_ENCHANTMENT_TEMPLATE";
export const COPY_ITEM_ENCHANTMENT_TEMPLATE = "COPY_ITEM_ENCHANTMENT_TEMPLATE";

export const SEARCH_ITEM_LOOT_TEMPLATES = "SEARCH_ITEM_LOOT_TEMPLATES";
export const STORE_ITEM_LOOT_TEMPLATE = "STORE_ITEM_LOOT_TEMPLATE";
export const FIND_ITEM_LOOT_TEMPLATE = "FIND_ITEM_LOOT_TEMPLATE";
export const UPDATE_ITEM_LOOT_TEMPLATE = "UPDATE_ITEM_LOOT_TEMPLATE";
export const DESTROY_ITEM_LOOT_TEMPLATE = "DESTROY_ITEM_LOOT_TEMPLATE";
export const CREATE_ITEM_LOOT_TEMPLATE = "CREATE_ITEM_LOOT_TEMPLATE";
export const COPY_ITEM_LOOT_TEMPLATE = "COPY_ITEM_LOOT_TEMPLATE";

export const SEARCH_DISENCHANT_LOOT_TEMPLATES =
  "SEARCH_DISENCHANT_LOOT_TEMPLATES";
export const STORE_DISENCHANT_LOOT_TEMPLATE = "STORE_DISENCHANT_LOOT_TEMPLATE";
export const FIND_DISENCHANT_LOOT_TEMPLATE = "FIND_DISENCHANT_LOOT_TEMPLATE";
export const UPDATE_DISENCHANT_LOOT_TEMPLATE =
  "UPDATE_DISENCHANT_LOOT_TEMPLATE";
export const DESTROY_DISENCHANT_LOOT_TEMPLATE =
  "DESTROY_DISENCHANT_LOOT_TEMPLATE";
export const CREATE_DISENCHANT_LOOT_TEMPLATE =
  "CREATE_DISENCHANT_LOOT_TEMPLATE";
export const COPY_DISENCHANT_LOOT_TEMPLATE = "COPY_DISENCHANT_LOOT_TEMPLATE";

export const SEARCH_PROSPECTING_LOOT_TEMPLATES =
  "SEARCH_PROSPECTING_LOOT_TEMPLATES";
export const STORE_PROSPECTING_LOOT_TEMPLATE =
  "STORE_PROSPECTING_LOOT_TEMPLATE";
export const FIND_PROSPECTING_LOOT_TEMPLATE = "FIND_PROSPECTING_LOOT_TEMPLATE";
export const UPDATE_PROSPECTING_LOOT_TEMPLATE =
  "UPDATE_PROSPECTING_LOOT_TEMPLATE";
export const DESTROY_PROSPECTING_LOOT_TEMPLATE =
  "DESTROY_PROSPECTING_LOOT_TEMPLATE";
export const CREATE_PROSPECTING_LOOT_TEMPLATE =
  "CREATE_PROSPECTING_LOOT_TEMPLATE";
export const COPY_PROSPECTING_LOOT_TEMPLATE = "COPY_PROSPECTING_LOOT_TEMPLATE";

export const SEARCH_MILLING_LOOT_TEMPLATES = "SEARCH_MILLING_LOOT_TEMPLATES";
export const STORE_MILLING_LOOT_TEMPLATE = "STORE_MILLING_LOOT_TEMPLATE";
export const FIND_MILLING_LOOT_TEMPLATE = "FIND_MILLING_LOOT_TEMPLATE";
export const UPDATE_MILLING_LOOT_TEMPLATE = "UPDATE_MILLING_LOOT_TEMPLATE";
export const DESTROY_MILLING_LOOT_TEMPLATE = "DESTROY_MILLING_LOOT_TEMPLATE";
export const CREATE_MILLING_LOOT_TEMPLATE = "CREATE_MILLING_LOOT_TEMPLATE";
export const COPY_MILLING_LOOT_TEMPLATE = "COPY_MILLING_LOOT_TEMPLATE";

export const SEARCH_GAME_OBJECT_TEMPLATES = "SEARCH_GAME_OBJECT_TEMPLATES";
export const COUNT_GAME_OBJECT_TEMPLATES = "COUNT_GAME_OBJECT_TEMPLATES";
export const PAGINATE_GAME_OBJECT_TEMPLATES = "PAGINATE_GAME_OBJECT_TEMPLATES";
export const STORE_GAME_OBJECT_TEMPLATE = "STORE_GAME_OBJECT_TEMPLATE";
export const FIND_GAME_OBJECT_TEMPLATE = "FIND_GAME_OBJECT_TEMPLATE";
export const UPDATE_GAME_OBJECT_TEMPLATE = "UPDATE_GAME_OBJECT_TEMPLATE";
export const DESTROY_GAME_OBJECT_TEMPLATE = "DESTROY_GAME_OBJECT_TEMPLATE";
export const CREATE_GAME_OBJECT_TEMPLATE = "CREATE_GAME_OBJECT_TEMPLATE";
export const COPY_GAME_OBJECT_TEMPLATE = "COPY_GAME_OBJECT_TEMPLATE";

export const SEARCH_GAME_OBJECT_TEMPLATE_LOCALES =
  "SEARCH_GAME_OBJECT_TEMPLATE_LOCALES";
export const STORE_GAME_OBJECT_TEMPLATE_LOCALES =
  "STORE_GAME_OBJECT_TEMPLATE_LOCALES";

export const STORE_GAME_OBJECT_TEMPLATE_ADDON =
  "STORE_GAME_OBJECT_TEMPLATE_ADDON";
export const FIND_GAME_OBJECT_TEMPLATE_ADDON =
  "FIND_GAME_OBJECT_TEMPLATE_ADDON";
export const UPDATE_GAME_OBJECT_TEMPLATE_ADDON =
  "UPDATE_GAME_OBJECT_TEMPLATE_ADDON";
export const CREATE_GAME_OBJECT_TEMPLATE_ADDON =
  "CREATE_GAME_OBJECT_TEMPLATE_ADDON";

export const SEARCH_GAME_OBJECT_QUEST_ITEMS = "SEARCH_GAME_OBJECT_QUEST_ITEMS";
export const STORE_GAME_OBJECT_QUEST_ITEM = "STORE_GAME_OBJECT_QUEST_ITEM";
export const FIND_GAME_OBJECT_QUEST_ITEM = "FIND_GAME_OBJECT_QUEST_ITEM";
export const UPDATE_GAME_OBJECT_QUEST_ITEM = "UPDATE_GAME_OBJECT_QUEST_ITEM";
export const DESTROY_GAME_OBJECT_QUEST_ITEM = "DESTROY_GAME_OBJECT_QUEST_ITEM";
export const CREATE_GAME_OBJECT_QUEST_ITEM = "CREATE_GAME_OBJECT_QUEST_ITEM";
export const COPY_GAME_OBJECT_QUEST_ITEM = "COPY_GAME_OBJECT_QUEST_ITEM";

export const SEARCH_GAME_OBJECT_LOOT_TEMPLATES =
  "SEARCH_GAME_OBJECT_LOOT_TEMPLATES";
export const STORE_GAME_OBJECT_LOOT_TEMPLATE =
  "STORE_GAME_OBJECT_LOOT_TEMPLATE";
export const FIND_GAME_OBJECT_LOOT_TEMPLATE = "FIND_GAME_OBJECT_LOOT_TEMPLATE";
export const UPDATE_GAME_OBJECT_LOOT_TEMPLATE =
  "UPDATE_GAME_OBJECT_LOOT_TEMPLATE";
export const DESTROY_GAME_OBJECT_LOOT_TEMPLATE =
  "DESTROY_GAME_OBJECT_LOOT_TEMPLATE";
export const CREATE_GAME_OBJECT_LOOT_TEMPLATE =
  "CREATE_GAME_OBJECT_LOOT_TEMPLATE";
export const COPY_GAME_OBJECT_LOOT_TEMPLATE = "COPY_GAME_OBJECT_LOOT_TEMPLATE";

export const SEARCH_QUEST_TEMPLATES = "SEARCH_QUEST_TEMPLATES";
export const COUNT_QUEST_TEMPLATES = "COUNT_QUEST_TEMPLATES";
export const PAGINATE_QUEST_TEMPLATES = "PAGINATE_QUEST_TEMPLATES";
export const STORE_QUEST_TEMPLATE = "STORE_QUEST_TEMPLATE";
export const FIND_QUEST_TEMPLATE = "FIND_QUEST_TEMPLATE";
export const UPDATE_QUEST_TEMPLATE = "UPDATE_QUEST_TEMPLATE";
export const DESTROY_QUEST_TEMPLATE = "DESTROY_QUEST_TEMPLATE";
export const CREATE_QUEST_TEMPLATE = "CREATE_QUEST_TEMPLATE";
export const COPY_QUEST_TEMPLATE = "COPY_QUEST_TEMPLATE";

export const SEARCH_QUEST_TEMPLATE_LOCALES = "SEARCH_QUEST_TEMPLATE_LOCALES";
export const STORE_QUEST_TEMPLATE_LOCALES = "STORE_QUEST_TEMPLATE_LOCALES";

export const STORE_QUEST_TEMPLATE_ADDON = "STORE_QUEST_TEMPLATE_ADDON";
export const FIND_QUEST_TEMPLATE_ADDON = "FIND_QUEST_TEMPLATE_ADDON";
export const UPDATE_QUEST_TEMPLATE_ADDON = "UPDATE_QUEST_TEMPLATE_ADDON";
export const CREATE_QUEST_TEMPLATE_ADDON = "CREATE_QUEST_TEMPLATE_ADDON";

export const STORE_QUEST_OFFER_REWARD = "STORE_QUEST_OFFER_REWARD";
export const FIND_QUEST_OFFER_REWARD = "FIND_QUEST_OFFER_REWARD";
export const UPDATE_QUEST_OFFER_REWARD = "UPDATE_QUEST_OFFER_REWARD";
export const CREATE_QUEST_OFFER_REWARD = "CREATE_QUEST_OFFER_REWARD";

export const STORE_QUEST_REQUEST_ITEMS = "STORE_QUEST_REQUEST_ITEMS";
export const FIND_QUEST_REQUEST_ITEMS = "FIND_QUEST_REQUEST_ITEMS";
export const UPDATE_QUEST_REQUEST_ITEMS = "UPDATE_QUEST_REQUEST_ITEMS";
export const CREATE_QUEST_REQUEST_ITEMS = "CREATE_QUEST_REQUEST_ITEMS";

export const SEARCH_CREATURE_QUEST_STARTERS = "SEARCH_CREATURE_QUEST_STARTERS";
export const STORE_CREATURE_QUEST_STARTER = "STORE_CREATURE_QUEST_STARTER";
export const FIND_CREATURE_QUEST_STARTER = "FIND_CREATURE_QUEST_STARTER";
export const UPDATE_CREATURE_QUEST_STARTER = "UPDATE_CREATURE_QUEST_STARTER";
export const DESTROY_CREATURE_QUEST_STARTER = "DESTROY_CREATURE_QUEST_STARTER";
export const CREATE_CREATURE_QUEST_STARTER = "CREATE_CREATURE_QUEST_STARTER";
export const COPY_CREATURE_QUEST_STARTER = "COPY_CREATURE_QUEST_STARTER";

export const SEARCH_CREATURE_QUEST_ENDERS = "SEARCH_CREATURE_QUEST_ENDERS";
export const STORE_CREATURE_QUEST_ENDER = "STORE_CREATURE_QUEST_ENDER";
export const FIND_CREATURE_QUEST_ENDER = "FIND_CREATURE_QUEST_ENDER";
export const UPDATE_CREATURE_QUEST_ENDER = "UPDATE_CREATURE_QUEST_ENDER";
export const DESTROY_CREATURE_QUEST_ENDER = "DESTROY_CREATURE_QUEST_ENDER";
export const CREATE_CREATURE_QUEST_ENDER = "CREATE_CREATURE_QUEST_ENDER";
export const COPY_CREATURE_QUEST_ENDER = "COPY_CREATURE_QUEST_ENDER";

export const SEARCH_GAME_OBJECT_QUEST_STARTERS =
  "SEARCH_GAME_OBJECT_QUEST_STARTERS";
export const STORE_GAME_OBJECT_QUEST_STARTER =
  "STORE_GAME_OBJECT_QUEST_STARTER";
export const FIND_GAME_OBJECT_QUEST_STARTER = "FIND_GAME_OBJECT_QUEST_STARTER";
export const UPDATE_GAME_OBJECT_QUEST_STARTER =
  "UPDATE_GAME_OBJECT_QUEST_STARTER";
export const DESTROY_GAME_OBJECT_QUEST_STARTER =
  "DESTROY_GAME_OBJECT_QUEST_STARTER";
export const CREATE_GAME_OBJECT_QUEST_STARTER =
  "CREATE_GAME_OBJECT_QUEST_STARTER";
export const COPY_GAME_OBJECT_QUEST_STARTER = "COPY_GAME_OBJECT_QUEST_STARTER";

export const SEARCH_GAME_OBJECT_QUEST_ENDERS =
  "SEARCH_GAME_OBJECT_QUEST_ENDERS";
export const STORE_GAME_OBJECT_QUEST_ENDER = "STORE_GAME_OBJECT_QUEST_ENDER";
export const FIND_GAME_OBJECT_QUEST_ENDER = "FIND_GAME_OBJECT_QUEST_ENDER";
export const UPDATE_GAME_OBJECT_QUEST_ENDER = "UPDATE_GAME_OBJECT_QUEST_ENDER";
export const DESTROY_GAME_OBJECT_QUEST_ENDER =
  "DESTROY_GAME_OBJECT_QUEST_ENDER";
export const CREATE_GAME_OBJECT_QUEST_ENDER = "CREATE_GAME_OBJECT_QUEST_ENDER";
export const COPY_GAME_OBJECT_QUEST_ENDER = "COPY_GAME_OBJECT_QUEST_ENDER";

export const SEARCH_SMART_SCRIPTS = "SEARCH_SMART_SCRIPTS";
export const COUNT_SMART_SCRIPTS = "COUNT_SMART_SCRIPTS";
export const PAGINATE_SMART_SCRIPTS = "PAGINATE_SMART_SCRIPTS";
export const STORE_SMART_SCRIPT = "STORE_SMART_SCRIPT";
export const FIND_SMART_SCRIPT = "FIND_SMART_SCRIPT";
export const UPDATE_SMART_SCRIPT = "UPDATE_SMART_SCRIPT";
export const DESTROY_SMART_SCRIPT = "DESTROY_SMART_SCRIPT";
export const CREATE_SMART_SCRIPT = "CREATE_SMART_SCRIPT";
export const COPY_SMART_SCRIPT = "COPY_SMART_SCRIPT";

export const SEARCH_SPELLS = "SEARCH_SPELLS";
export const COUNT_SPELLS = "COUNT_SPELLS";
export const PAGINATE_SPELLS = "PAGINATE_SPELLS";
export const STORE_SPELL = "STORE_SPELL";
export const FIND_SPELL = "FIND_SPELL";
export const UPDATE_SPELL = "UPDATE_SPELL";
export const DESTROY_SPELL = "DESTROY_SPELL";
export const CREATE_SPELL = "CREATE_SPELL";
export const COPY_SPELL = "COPY_SPELL";

export const SEARCH_GOSSIP_MENUS = "SEARCH_GOSSIP_MENUS";
export const COUNT_GOSSIP_MENUS = "COUNT_GOSSIP_MENUS";
export const PAGINATE_GOSSIP_MENUS = "PAGINATE_GOSSIP_MENUS";
export const STORE_GOSSIP_MENU = "STORE_GOSSIP_MENU";
export const FIND_GOSSIP_MENU = "FIND_GOSSIP_MENU";
export const UPDATE_GOSSIP_MENU = "UPDATE_GOSSIP_MENU";
export const DESTROY_GOSSIP_MENU = "DESTROY_GOSSIP_MENU";
export const CREATE_GOSSIP_MENU = "CREATE_GOSSIP_MENU";
export const COPY_GOSSIP_MENU = "COPY_GOSSIP_MENU";

export const STORE_NPC_TEXT = "STORE_NPC_TEXT";
export const FIND_NPC_TEXT = "FIND_NPC_TEXT";
export const UPDATE_NPC_TEXT = "UPDATE_NPC_TEXT";
export const CREATE_NPC_TEXT = "CREATE_NPC_TEXT";

export const SEARCH_NPC_TEXT_LOCALES = "SEARCH_NPC_TEXT_LOCALES";
export const STORE_NPC_TEXT_LOCALES = "STORE_NPC_TEXT_LOCALES";

export const SEARCH_GOSSIP_MENU_OPTIONS = "SEARCH_GOSSIP_MENU_OPTIONS";
export const STORE_GOSSIP_MENU_OPTION = "STORE_GOSSIP_MENU_OPTION";
export const FIND_GOSSIP_MENU_OPTION = "FIND_GOSSIP_MENU_OPTION";
export const UPDATE_GOSSIP_MENU_OPTION = "UPDATE_GOSSIP_MENU_OPTION";
export const DESTROY_GOSSIP_MENU_OPTION = "DESTROY_GOSSIP_MENU_OPTION";
export const CREATE_GOSSIP_MENU_OPTION = "CREATE_GOSSIP_MENU_OPTION";
export const COPY_GOSSIP_MENU_OPTION = "COPY_GOSSIP_MENU_OPTION";

export const SEARCH_REFERENCE_LOOT_TEMPLATES =
  "SEARCH_REFERENCE_LOOT_TEMPLATES";
export const STORE_REFERENCE_LOOT_TEMPLATE = "STORE_REFERENCE_LOOT_TEMPLATE";
export const FIND_REFERENCE_LOOT_TEMPLATE = "FIND_REFERENCE_LOOT_TEMPLATE";
export const UPDATE_REFERENCE_LOOT_TEMPLATE = "UPDATE_REFERENCE_LOOT_TEMPLATE";
export const DESTROY_REFERENCE_LOOT_TEMPLATE =
  "DESTROY_REFERENCE_LOOT_TEMPLATE";
export const CREATE_REFERENCE_LOOT_TEMPLATE = "CREATE_REFERENCE_LOOT_TEMPLATE";
export const COPY_REFERENCE_LOOT_TEMPLATE = "COPY_REFERENCE_LOOT_TEMPLATE";

export const SEARCH_FACTION_TEMPLATES_FOR_SELECTOR =
  "SEARCH_FACTION_TEMPLATES_FOR_SELECTOR";
export const COUNT_FACTION_TEMPLATES_FOR_SELECTOR =
  "COUNT_FACTION_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_FACTION_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_FACTION_TEMPLATES_FOR_SELECTOR";

export const SEARCH_CREATURE_SPELL_DATAS_FOR_SELECTOR =
  "SEARCH_CREATURE_SPELL_DATAS_FOR_SELECTOR";
export const COUNT_CREATURE_SPELL_DATAS_FOR_SELECTOR =
  "COUNT_CREATURE_SPELL_DATAS_FOR_SELECTOR";
export const PAGINATE_CREATURE_SPELL_DATAS_FOR_SELECTOR =
  "PAGINATE_CREATURE_SPELL_DATAS_FOR_SELECTOR";

export const SEARCH_CREATURE_MODEL_INFOS_FOR_SELECTOR =
  "SEARCH_CREATURE_MODEL_INFOS_FOR_SELECTOR";
export const COUNT_CREATURE_MODEL_INFOS_FOR_SELECTOR =
  "COUNT_CREATURE_MODEL_INFOS_FOR_SELECTOR";
export const PAGINATE_CREATURE_MODEL_INFOS_FOR_SELECTOR =
  "PAGINATE_CREATURE_MODEL_INFOS_FOR_SELECTOR";

export const SEARCH_CREATURE_TEMPLATES_FOR_SELECTOR =
  "SEARCH_CREATURE_TEMPLATES_FOR_SELECTOR";
export const COUNT_CREATURE_TEMPLATES_FOR_SELECTOR =
  "COUNT_CREATURE_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_CREATURE_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_CREATURE_TEMPLATES_FOR_SELECTOR";

export const SEARCH_SPELLS_FOR_SELECTOR = "SEARCH_SPELLS_FOR_SELECTOR";
export const COUNT_SPELLS_FOR_SELECTOR = "COUNT_SPELLS_FOR_SELECTOR";
export const PAGINATE_SPELLS_FOR_SELECTOR = "PAGINATE_SPELLS_FOR_SELECTOR";

export const SEARCH_SPELL_DURATIONS_FOR_SELECTOR =
  "SEARCH_SPELL_DURATIONS_FOR_SELECTOR";
export const COUNT_SPELL_DURATIONS_FOR_SELECTOR =
  "COUNT_SPELL_DURATIONS_FOR_SELECTOR";
export const PAGINATE_SPELL_DURATIONS_FOR_SELECTOR =
  "PAGINATE_SPELL_DURATIONS_FOR_SELECTOR";

export const SEARCH_SPELL_CAST_TIMES_FOR_SELECTOR =
  "SEARCH_SPELL_CAST_TIMES_FOR_SELECTOR";
export const COUNT_SPELL_CAST_TIMES_FOR_SELECTOR =
  "COUNT_SPELL_CAST_TIMES_FOR_SELECTOR";
export const PAGINATE_SPELL_CAST_TIMES_FOR_SELECTOR =
  "PAGINATE_SPELL_CAST_TIMES_FOR_SELECTOR";

export const SEARCH_SPELL_RANGES_FOR_SELECTOR =
  "SEARCH_SPELL_RANGES_FOR_SELECTOR";
export const COUNT_SPELL_RANGES_FOR_SELECTOR =
  "COUNT_SPELL_RANGES_FOR_SELECTOR";
export const PAGINATE_SPELL_RANGES_FOR_SELECTOR =
  "PAGINATE_SPELL_RANGES_FOR_SELECTOR";

export const SEARCH_SPELL_AREAS = "SEARCH_SPELL_AREAS";
export const STORE_SPELL_AREA = "STORE_SPELL_AREA";
export const FIND_SPELL_AREA = "FIND_SPELL_AREA";
export const UPDATE_SPELL_AREA = "UPDATE_SPELL_AREA";
export const DESTROY_SPELL_AREA = "DESTROY_SPELL_AREA";
export const CREATE_SPELL_AREA = "CREATE_SPELL_AREA";
export const COPY_SPELL_AREA = "COPY_SPELL_AREA";

export const STORE_SPELL_BONUS_DATA = "STORE_SPELL_BONUS_DATA";
export const FIND_SPELL_BONUS_DATA = "FIND_SPELL_BONUS_DATA";
export const UPDATE_SPELL_BONUS_DATA = "UPDATE_SPELL_BONUS_DATA";
export const CREATE_SPELL_BONUS_DATA = "CREATE_SPELL_BONUS_DATA";

export const STORE_SPELL_CUSTOM_ATTR = "STORE_SPELL_CUSTOM_ATTR";
export const FIND_SPELL_CUSTOM_ATTR = "FIND_SPELL_CUSTOM_ATTR";
export const UPDATE_SPELL_CUSTOM_ATTR = "UPDATE_SPELL_CUSTOM_ATTR";
export const CREATE_SPELL_CUSTOM_ATTR = "CREATE_SPELL_CUSTOM_ATTR";

export const SEARCH_SPELL_GROUPS = "SEARCH_SPELL_GROUPS";
export const STORE_SPELL_GROUP = "STORE_SPELL_GROUP";
export const FIND_SPELL_GROUP = "FIND_SPELL_GROUP";
export const UPDATE_SPELL_GROUP = "UPDATE_SPELL_GROUP";
export const DESTROY_SPELL_GROUP = "DESTROY_SPELL_GROUP";
export const CREATE_SPELL_GROUP = "CREATE_SPELL_GROUP";
export const COPY_SPELL_GROUP = "COPY_SPELL_GROUP";

export const SEARCH_SPELL_LINKED_SPELLS = "SEARCH_SPELL_LINKED_SPELLS";
export const STORE_SPELL_LINKED_SPELL = "STORE_SPELL_LINKED_SPELL";
export const FIND_SPELL_LINKED_SPELL = "FIND_SPELL_LINKED_SPELL";
export const UPDATE_SPELL_LINKED_SPELL = "UPDATE_SPELL_LINKED_SPELL";
export const DESTROY_SPELL_LINKED_SPELL = "DESTROY_SPELL_LINKED_SPELL";
export const CREATE_SPELL_LINKED_SPELL = "CREATE_SPELL_LINKED_SPELL";
export const COPY_SPELL_LINKED_SPELL = "COPY_SPELL_LINKED_SPELL";

export const SEARCH_SPELL_LOOT_TEMPLATES = "SEARCH_SPELL_LOOT_TEMPLATES";
export const STORE_SPELL_LOOT_TEMPLATE = "STORE_SPELL_LOOT_TEMPLATE";
export const FIND_SPELL_LOOT_TEMPLATE = "FIND_SPELL_LOOT_TEMPLATE";
export const UPDATE_SPELL_LOOT_TEMPLATE = "UPDATE_SPELL_LOOT_TEMPLATE";
export const DESTROY_SPELL_LOOT_TEMPLATE = "DESTROY_SPELL_LOOT_TEMPLATE";
export const CREATE_SPELL_LOOT_TEMPLATE = "CREATE_SPELL_LOOT_TEMPLATE";
export const COPY_SPELL_LOOT_TEMPLATE = "COPY_SPELL_LOOT_TEMPLATE";

export const SEARCH_SCALING_STAT_DISTRIBUTIONS =
  "SEARCH_SCALING_STAT_DISTRIBUTIONS";
export const COUNT_SCALING_STAT_DISTRIBUTIONS =
  "COUNT_SCALING_STAT_DISTRIBUTIONS";
export const PAGINATE_SCALING_STAT_DISTRIBUTIONS =
  "PAGINATE_SCALING_STAT_DISTRIBUTIONS";
export const STORE_SCALING_STAT_DISTRIBUTION =
  "STORE_SCALING_STAT_DISTRIBUTION";
export const FIND_SCALING_STAT_DISTRIBUTION = "FIND_SCALING_STAT_DISTRIBUTION";
export const UPDATE_SCALING_STAT_DISTRIBUTION =
  "UPDATE_SCALING_STAT_DISTRIBUTION";
export const DESTROY_SCALING_STAT_DISTRIBUTION =
  "DESTROY_SCALING_STAT_DISTRIBUTION";
export const CREATE_SCALING_STAT_DISTRIBUTION =
  "CREATE_SCALING_STAT_DISTRIBUTION";
export const COPY_SCALING_STAT_DISTRIBUTION = "COPY_SCALING_STAT_DISTRIBUTION";

export const SEARCH_GOSSIP_MENUS_FOR_SELECTOR =
  "SEARCH_GOSSIP_MENUS_FOR_SELECTOR";
export const COUNT_GOSSIP_MENUS_FOR_SELECTOR =
  "COUNT_GOSSIP_MENUS_FOR_SELECTOR";
export const PAGINATE_GOSSIP_MENUS_FOR_SELECTOR =
  "PAGINATE_GOSSIP_MENUS_FOR_SELECTOR";

export const SEARCH_ITEM_TEMPLATES_FOR_SELECTOR =
  "SEARCH_ITEM_TEMPLATES_FOR_SELECTOR";
export const COUNT_ITEM_TEMPLATES_FOR_SELECTOR =
  "COUNT_ITEM_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_ITEM_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_ITEM_TEMPLATES_FOR_SELECTOR";

export const SEARCH_ITEM_SETS_FOR_SELECTOR = "SEARCH_ITEM_SETS_FOR_SELECTOR";
export const COUNT_ITEM_SETS_FOR_SELECTOR = "COUNT_ITEM_SETS_FOR_SELECTOR";
export const PAGINATE_ITEM_SETS_FOR_SELECTOR =
  "PAGINATE_ITEM_SETS_FOR_SELECTOR";

export const SEARCH_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR =
  "SEARCH_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR";
export const COUNT_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR =
  "COUNT_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR";
export const PAGINATE_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR =
  "PAGINATE_SCALING_STAT_DISTRIBUTIONS_FOR_SELECTOR";

export const SEARCH_WAYPOINT_DATAS_FOR_SELECTOR =
  "SEARCH_WAYPOINT_DATAS_FOR_SELECTOR";
export const COUNT_WAYPOINT_DATAS_FOR_SELECTOR =
  "COUNT_WAYPOINT_DATAS_FOR_SELECTOR";
export const PAGINATE_WAYPOINT_DATAS_FOR_SELECTOR =
  "PAGINATE_WAYPOINT_DATAS_FOR_SELECTOR";

export const SEARCH_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR =
  "SEARCH_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR";
export const COUNT_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR =
  "COUNT_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_ITEM_ENCHANTMENT_TEMPLATES_FOR_SELECTOR";

export const SEARCH_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR =
  "SEARCH_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR";
export const COUNT_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR =
  "COUNT_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR";
export const PAGINATE_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR =
  "PAGINATE_ITEM_RANDOM_PROPERTIES_FOR_SELECTOR";

export const SEARCH_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR =
  "SEARCH_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR";
export const COUNT_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR =
  "COUNT_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR";
export const PAGINATE_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR =
  "PAGINATE_ITEM_RANDOM_SUFFIXES_FOR_SELECTOR";

export const SEARCH_ITEM_DISPLAY_INFOS_FOR_SELECTOR =
  "SEARCH_ITEM_DISPLAY_INFOS_FOR_SELECTOR";
export const COUNT_ITEM_DISPLAY_INFOS_FOR_SELECTOR =
  "COUNT_ITEM_DISPLAY_INFOS_FOR_SELECTOR";
export const PAGINATE_ITEM_DISPLAY_INFOS_FOR_SELECTOR =
  "PAGINATE_ITEM_DISPLAY_INFOS_FOR_SELECTOR";

export const SEARCH_QUEST_TEMPLATES_FOR_SELECTOR =
  "SEARCH_QUEST_TEMPLATES_FOR_SELECTOR";
export const COUNT_QUEST_TEMPLATES_FOR_SELECTOR =
  "COUNT_QUEST_TEMPLATES_FOR_SELECTOR";
export const PAGINATE_QUEST_TEMPLATES_FOR_SELECTOR =
  "PAGINATE_QUEST_TEMPLATES_FOR_SELECTOR";

export const FIND_VERSION = "FIND_VERSION";
