import 'package:foxy/page/bootstrap/bootstrap_view_model.dart';
import 'package:foxy/page/more/more_view_model.dart';
import 'package:foxy/page/creature_template/creature_equip_template_view_model.dart';
import 'package:foxy/view_model/feature_view_model.dart';
import 'package:foxy/page/creature_template/creature_loot_template_view_model.dart';
import 'package:foxy/page/creature_template/creature_on_kill_reputation_view_model.dart';
import 'package:foxy/page/creature_template/creature_quest_item_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_addon_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_detail_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_list_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_resistance_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_spell_view_model.dart';
import 'package:foxy/page/creature_template/npc_trainer_view_model.dart';
import 'package:foxy/page/creature_template/npc_vendor_view_model.dart';
import 'package:foxy/page/creature_template/pickpocketing_loot_template_view_model.dart';
import 'package:foxy/page/creature_template/skinning_loot_template_view_model.dart';
import 'package:foxy/page/dashboard/dashboard_view_model.dart';
import 'package:foxy/page/foxy_app/foxy_view_model.dart';
import 'package:foxy/page/game_object/game_object_template_list_view_model.dart';
import 'package:foxy/page/game_object/game_object_template_detail_view_model.dart';
import 'package:foxy/page/game_object/game_object_template_addon_view_model.dart';
import 'package:foxy/page/game_object/game_object_quest_item_view_model.dart';
import 'package:foxy/page/game_object/game_object_loot_template_view_model.dart';
import 'package:foxy/page/item/disenchant_loot_template_view_model.dart';
import 'package:foxy/page/item/item_enchantment_template_view_model.dart';
import 'package:foxy/page/item/item_loot_template_view_model.dart';
import 'package:foxy/page/item/item_template_detail_view_model.dart';
import 'package:foxy/page/item/item_template_list_view_model.dart';
import 'package:foxy/page/item/milling_loot_template_view_model.dart';
import 'package:foxy/page/item/prospecting_loot_template_view_model.dart';
import 'package:foxy/page/gossip_menu/gossip_menu_detail_view_model.dart';
import 'package:foxy/page/gossip_menu/gossip_menu_list_view_model.dart';
import 'package:foxy/page/gossip_menu/gossip_menu_option_view_model.dart';
import 'package:foxy/page/gossip_menu/npc_text_view_model.dart';
import 'package:foxy/page/scaffold/scaffold_view_model.dart';
import 'package:foxy/page/scaffold/dbc_import_view_model.dart';
import 'package:foxy/page/setting/setting_view_model.dart';
import 'package:foxy/page/smart_script/smart_script_list_view_model.dart';
import 'package:foxy/page/spell/spell_list_view_model.dart';
import 'package:foxy/page/spell/spell_detail_view_model.dart';
import 'package:foxy/page/spell/spell_bonus_data_view_model.dart';
import 'package:foxy/page/spell/spell_custom_attr_view_model.dart';
import 'package:foxy/page/spell/spell_area_view_model.dart';
import 'package:foxy/page/spell/spell_group_view_model.dart';
import 'package:foxy/page/spell/spell_linked_spell_view_model.dart';
import 'package:foxy/page/spell/spell_rank_view_model.dart';
import 'package:foxy/page/spell/spell_loot_template_view_model.dart';
import 'package:foxy/page/smart_script/smart_script_detail_view_model.dart';
import 'package:foxy/page/quest/creature_questender_view_model.dart';
import 'package:foxy/page/quest/creature_queststarter_view_model.dart';
import 'package:foxy/page/quest/gameobject_questender_view_model.dart';
import 'package:foxy/page/quest/gameobject_queststarter_view_model.dart';
import 'package:foxy/page/quest/quest_offer_reward_view_model.dart';
import 'package:foxy/page/quest/quest_request_items_view_model.dart';
import 'package:foxy/page/quest/quest_template_addon_view_model.dart';
import 'package:foxy/page/quest/quest_template_detail_view_model.dart';
import 'package:foxy/page/quest/quest_template_list_view_model.dart';
import 'package:foxy/router/router_facade.dart';
import 'package:get_it/get_it.dart';

class DI {
  static void ensureInitialized() {
    GetIt.instance.registerSingleton(RouterFacade());
    GetIt.instance.registerSingleton(FoxyViewModel());
    GetIt.instance.registerSingleton(FeatureViewModel());
    GetIt.instance.registerFactory(() => BootstrapViewModel());
    GetIt.instance.registerSingleton(ScaffoldViewModel());
    GetIt.instance.registerSingleton(DbcImportViewModel());
    GetIt.instance.registerFactory(() => DashboardViewModel());
    GetIt.instance.registerLazySingleton(() => MoreViewModel());
    GetIt.instance.registerLazySingleton(() => CreatureTemplateListViewModel());
    GetIt.instance.registerFactory(() => CreatureTemplateDetailViewModel());
    GetIt.instance.registerFactory(() => CreatureTemplateAddonViewModel());
    GetIt.instance.registerFactory(() => CreatureOnKillReputationViewModel());
    GetIt.instance.registerFactory(() => CreatureEquipTemplateViewModel());
    GetIt.instance.registerFactory(() => CreatureQuestItemViewModel());
    GetIt.instance.registerFactory(() => CreatureTemplateResistanceViewModel());
    GetIt.instance.registerFactory(() => CreatureTemplateSpellViewModel());
    GetIt.instance.registerFactory(() => CreatureLootTemplateViewModel());
    GetIt.instance.registerFactory(() => NpcTrainerViewModel());
    GetIt.instance.registerFactory(() => NpcVendorViewModel());
    GetIt.instance.registerFactory(() => PickpocketingLootTemplateViewModel());
    GetIt.instance.registerFactory(() => SkinningLootTemplateViewModel());
    GetIt.instance.registerLazySingleton(
      () => GameObjectTemplateListViewModel(),
    );
    GetIt.instance.registerFactory(() => GameObjectTemplateDetailViewModel());
    GetIt.instance.registerFactory(() => GameObjectTemplateAddonViewModel());
    GetIt.instance.registerFactory(() => GameObjectQuestItemViewModel());
    GetIt.instance.registerFactory(() => GameObjectLootTemplateViewModel());
    GetIt.instance.registerLazySingleton(() => ItemTemplateListViewModel());
    GetIt.instance.registerFactory(() => ItemTemplateDetailViewModel());
    GetIt.instance.registerFactory(() => ItemLootTemplateViewModel());
    GetIt.instance.registerFactory(() => DisenchantLootTemplateViewModel());
    GetIt.instance.registerFactory(() => ProspectingLootTemplateViewModel());
    GetIt.instance.registerFactory(() => MillingLootTemplateViewModel());
    GetIt.instance.registerFactory(() => ItemEnchantmentTemplateViewModel());
    GetIt.instance.registerLazySingleton(() => GossipMenuListViewModel());
    GetIt.instance.registerLazySingleton(() => QuestTemplateListViewModel());
    GetIt.instance.registerFactory(() => QuestTemplateDetailViewModel());
    GetIt.instance.registerFactory(() => QuestTemplateAddonViewModel());
    GetIt.instance.registerFactory(() => QuestRequestItemsViewModel());
    GetIt.instance.registerFactory(() => QuestOfferRewardViewModel());
    GetIt.instance.registerFactory(() => CreatureQueststarterViewModel());
    GetIt.instance.registerFactory(() => CreatureQuestenderViewModel());
    GetIt.instance.registerFactory(() => GameobjectQueststarterViewModel());
    GetIt.instance.registerFactory(() => GameobjectQuestenderViewModel());
    GetIt.instance.registerFactory(() => GossipMenuDetailViewModel());
    GetIt.instance.registerFactory(() => NpcTextViewModel());
    GetIt.instance.registerFactory(() => GossipMenuOptionViewModel());
    GetIt.instance.registerFactory(() => SettingViewModel());
    GetIt.instance.registerLazySingleton(() => SmartScriptListViewModel());
    GetIt.instance.registerFactory(() => SmartScriptDetailViewModel());
    GetIt.instance.registerLazySingleton(() => SpellListViewModel());
    GetIt.instance.registerFactory(() => SpellDetailViewModel());
    GetIt.instance.registerFactory(() => SpellBonusDataViewModel());
    GetIt.instance.registerFactory(() => SpellCustomAttrViewModel());
    GetIt.instance.registerFactory(() => SpellAreaViewModel());
    GetIt.instance.registerFactory(() => SpellGroupViewModel());
    GetIt.instance.registerFactory(() => SpellLinkedSpellViewModel());
    GetIt.instance.registerFactory(() => SpellRankViewModel());
    GetIt.instance.registerFactory(() => SpellLootTemplateViewModel());
  }
}
