import 'package:foxy/page/achievement/achievement_detail_view_model.dart';
import 'package:foxy/page/achievement/achievement_list_view_model.dart';
import 'package:foxy/page/area_table/area_table_detail_view_model.dart';
import 'package:foxy/page/area_table/area_table_list_view_model.dart';
import 'package:foxy/page/bootstrap/bootstrap_view_model.dart';
import 'package:foxy/page/condition/condition_detail_view_model.dart';
import 'package:foxy/page/condition/condition_list_view_model.dart';
import 'package:foxy/page/creature_template/creature_equip_template_view_model.dart';
import 'package:foxy/page/creature_template/creature_loot_template_view_model.dart';
import 'package:foxy/page/creature_template/creature_on_kill_reputation_view_model.dart';
import 'package:foxy/page/creature_template/creature_quest_item_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_addon_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_detail_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_list_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_resistance_view_model.dart';
import 'package:foxy/page/creature_template/creature_template_spell_view_model.dart';
import 'package:foxy/page/creature_template/npc_trainer_view_model.dart';
import 'package:foxy/page/creature_template/npc_vendor_view_model.dart';
import 'package:foxy/page/creature_template/pickpocketing_loot_template_view_model.dart';
import 'package:foxy/page/creature_template/skinning_loot_template_view_model.dart';
import 'package:foxy/page/currency_type/currency_type_detail_view_model.dart';
import 'package:foxy/page/currency_type/currency_type_list_view_model.dart';
import 'package:foxy/page/dashboard/dashboard_view_model.dart';
import 'package:foxy/page/emote_text/emote_text_detail_view_model.dart';
import 'package:foxy/page/emote_text/emote_text_list_view_model.dart';
import 'package:foxy/page/foxy_app/foxy_view_model.dart';
import 'package:foxy/page/game_object/game_object_loot_template_view_model.dart';
import 'package:foxy/page/game_object/game_object_quest_item_view_model.dart';
import 'package:foxy/page/game_object/game_object_template_addon_view_model.dart';
import 'package:foxy/page/game_object/game_object_template_detail_view_model.dart';
import 'package:foxy/page/game_object/game_object_template_list_view_model.dart';
import 'package:foxy/page/gem_property/gem_property_detail_view_model.dart';
import 'package:foxy/page/gem_property/gem_property_list_view_model.dart';
import 'package:foxy/page/glyph_property/glyph_property_detail_view_model.dart';
import 'package:foxy/page/glyph_property/glyph_property_list_view_model.dart';
import 'package:foxy/page/gossip_menu/gossip_menu_detail_view_model.dart';
import 'package:foxy/page/gossip_menu/gossip_menu_list_view_model.dart';
import 'package:foxy/page/gossip_menu/gossip_menu_option_view_model.dart';
import 'package:foxy/page/gossip_menu/npc_text_view_model.dart';
import 'package:foxy/page/item/disenchant_loot_template_view_model.dart';
import 'package:foxy/page/item/item_enchantment_template_view_model.dart';
import 'package:foxy/page/item/item_loot_template_view_model.dart';
import 'package:foxy/page/item/item_template_detail_view_model.dart';
import 'package:foxy/page/item/item_template_list_view_model.dart';
import 'package:foxy/page/item/milling_loot_template_view_model.dart';
import 'package:foxy/page/item/prospecting_loot_template_view_model.dart';
import 'package:foxy/page/item_extended_cost/item_extended_cost_detail_view_model.dart';
import 'package:foxy/page/item_extended_cost/item_extended_cost_list_view_model.dart';
import 'package:foxy/page/item_set/item_set_detail_view_model.dart';
import 'package:foxy/page/item_set/item_set_list_view_model.dart';
import 'package:foxy/page/more/more_view_model.dart';
import 'package:foxy/page/page_text/page_text_detail_view_model.dart';
import 'package:foxy/page/page_text/page_text_list_view_model.dart';
import 'package:foxy/page/page_text/page_text_locale_view_model.dart';
import 'package:foxy/page/player_create_info/player_create_info_action_view_model.dart';
import 'package:foxy/page/player_create_info/player_create_info_cast_spell_view_model.dart';
import 'package:foxy/page/player_create_info/player_create_info_detail_view_model.dart';
import 'package:foxy/page/player_create_info/player_create_info_item_view_model.dart';
import 'package:foxy/page/player_create_info/player_create_info_list_view_model.dart';
import 'package:foxy/page/player_create_info/player_create_info_skill_view_model.dart';
import 'package:foxy/page/player_create_info/player_create_info_spell_custom_view_model.dart';
import 'package:foxy/page/quest/creature_quest_ender_view_model.dart';
import 'package:foxy/page/quest/creature_quest_starter_view_model.dart';
import 'package:foxy/page/quest/game_object_quest_ender_view_model.dart';
import 'package:foxy/page/quest/game_object_quest_starter_view_model.dart';
import 'package:foxy/page/quest/quest_offer_reward_view_model.dart';
import 'package:foxy/page/quest/quest_request_items_view_model.dart';
import 'package:foxy/page/quest/quest_template_addon_view_model.dart';
import 'package:foxy/page/quest/quest_template_detail_view_model.dart';
import 'package:foxy/page/quest/quest_template_list_view_model.dart';
import 'package:foxy/page/quest_faction_reward/quest_faction_reward_detail_view_model.dart';
import 'package:foxy/page/quest_faction_reward/quest_faction_reward_list_view_model.dart';
import 'package:foxy/page/quest_info/quest_info_detail_view_model.dart';
import 'package:foxy/page/quest_info/quest_info_list_view_model.dart';
import 'package:foxy/page/quest_sort/quest_sort_detail_view_model.dart';
import 'package:foxy/page/quest_sort/quest_sort_list_view_model.dart';
import 'package:foxy/page/reference_loot_template/reference_loot_template_detail_view_model.dart';
import 'package:foxy/page/reference_loot_template/reference_loot_template_list_view_model.dart';
import 'package:foxy/page/scaffold/scaffold_view_model.dart';
import 'package:foxy/page/scaling_stat_distribution/scaling_stat_distribution_detail_view_model.dart';
import 'package:foxy/page/scaling_stat_distribution/scaling_stat_distribution_list_view_model.dart';
import 'package:foxy/page/scaling_stat_value/scaling_stat_value_detail_view_model.dart';
import 'package:foxy/page/scaling_stat_value/scaling_stat_value_list_view_model.dart';
import 'package:foxy/page/setting/setting_view_model.dart';
import 'package:foxy/page/smart_script/smart_script_detail_view_model.dart';
import 'package:foxy/page/smart_script/smart_script_list_view_model.dart';
import 'package:foxy/page/spell/spell_area_view_model.dart';
import 'package:foxy/page/spell/spell_bonus_data_view_model.dart';
import 'package:foxy/page/spell/spell_custom_attr_view_model.dart';
import 'package:foxy/page/spell/spell_detail_view_model.dart';
import 'package:foxy/page/spell/spell_group_view_model.dart';
import 'package:foxy/page/spell/spell_linked_spell_view_model.dart';
import 'package:foxy/page/spell/spell_list_view_model.dart';
import 'package:foxy/page/spell/spell_loot_template_view_model.dart';
import 'package:foxy/page/spell/spell_rank_view_model.dart';
import 'package:foxy/page/spell_item_enchantment/spell_item_enchantment_detail_view_model.dart';
import 'package:foxy/page/spell_item_enchantment/spell_item_enchantment_list_view_model.dart';
import 'package:foxy/page/talent/talent_detail_view_model.dart';
import 'package:foxy/page/talent/talent_list_view_model.dart';
import 'package:foxy/repository/achievement_repository.dart';
import 'package:foxy/repository/achievement_category_repository.dart';
import 'package:foxy/repository/achievement_criteria_repository.dart';
import 'package:foxy/repository/activity_log_repository.dart';
import 'package:foxy/repository/area_table_repository.dart';
import 'package:foxy/repository/broadcast_text_repository.dart';
import 'package:foxy/repository/char_title_repository.dart';
import 'package:foxy/repository/cinematic_sequence_repository.dart';
import 'package:foxy/repository/condition_repository.dart';
import 'package:foxy/repository/creature_display_info_repository.dart';
import 'package:foxy/repository/creature_model_data_repository.dart';
import 'package:foxy/repository/creature_equip_template_repository.dart';
import 'package:foxy/repository/creature_model_info_repository.dart';
import 'package:foxy/repository/creature_movement_info_repository.dart';
import 'package:foxy/repository/creature_immunity_repository.dart';
import 'package:foxy/repository/creature_on_kill_reputation_repository.dart';
import 'package:foxy/repository/creature_quest_ender_repository.dart';
import 'package:foxy/repository/creature_quest_item_repository.dart';
import 'package:foxy/repository/creature_quest_starter_repository.dart';
import 'package:foxy/repository/creature_spell_data_repository.dart';
import 'package:foxy/repository/creature_template_addon_repository.dart';
import 'package:foxy/repository/creature_template_locale_repository.dart';
import 'package:foxy/repository/creature_template_repository.dart';
import 'package:foxy/repository/creature_default_trainer_repository.dart';
import 'package:foxy/repository/creature_template_resistance_repository.dart';
import 'package:foxy/repository/creature_template_spell_repository.dart';
import 'package:foxy/repository/currency_type_repository.dart';
import 'package:foxy/repository/currency_category_repository.dart';
import 'package:foxy/repository/destructible_model_data_repository.dart';
import 'package:foxy/repository/dbc_faction_repository.dart';
import 'package:foxy/repository/dbc_faction_template_repository.dart';
import 'package:foxy/repository/dbc_emote_repository.dart';
import 'package:foxy/repository/dbc_item_repository.dart';
import 'package:foxy/repository/emote_text_data_repository.dart';
import 'package:foxy/repository/emote_text_repository.dart';
import 'package:foxy/repository/feature_repository.dart';
import 'package:foxy/repository/game_object_quest_ender_repository.dart';
import 'package:foxy/repository/game_object_art_kit_repository.dart';
import 'package:foxy/repository/game_object_display_info_repository.dart';
import 'package:foxy/repository/game_object_quest_item_repository.dart';
import 'package:foxy/repository/game_object_quest_starter_repository.dart';
import 'package:foxy/repository/game_object_template_addon_repository.dart';
import 'package:foxy/repository/game_object_template_locale_repository.dart';
import 'package:foxy/repository/game_object_template_repository.dart';
import 'package:foxy/repository/gem_property_repository.dart';
import 'package:foxy/repository/glyph_property_repository.dart';
import 'package:foxy/repository/gossip_menu_option_locale_repository.dart';
import 'package:foxy/repository/gossip_menu_option_repository.dart';
import 'package:foxy/repository/gossip_menu_repository.dart';
import 'package:foxy/repository/holiday_repository.dart';
import 'package:foxy/repository/item_display_info_repository.dart';
import 'package:foxy/repository/item_bag_family_repository.dart';
import 'package:foxy/repository/item_enchantment_template_repository.dart';
import 'package:foxy/repository/item_extended_cost_repository.dart';
import 'package:foxy/repository/item_purchase_group_repository.dart';
import 'package:foxy/repository/item_limit_category_repository.dart';
import 'package:foxy/repository/item_random_properties_repository.dart';
import 'package:foxy/repository/item_random_suffix_repository.dart';
import 'package:foxy/repository/item_set_repository.dart';
import 'package:foxy/repository/item_visual_effect_repository.dart';
import 'package:foxy/repository/item_visuals_repository.dart';
import 'package:foxy/repository/item_template_locale_repository.dart';
import 'package:foxy/repository/item_template_repository.dart';
import 'package:foxy/repository/lock_repository.dart';
import 'package:foxy/repository/light_repository.dart';
import 'package:foxy/repository/liquid_type_repository.dart';
import 'package:foxy/repository/map_info_repository.dart';
import 'package:foxy/repository/mail_template_repository.dart';
import 'package:foxy/repository/npc_text_locale_repository.dart';
import 'package:foxy/repository/npc_text_repository.dart';
import 'package:foxy/repository/npc_trainer_repository.dart';
import 'package:foxy/repository/npc_vendor_repository.dart';
import 'package:foxy/repository/page_text_locale_repository.dart';
import 'package:foxy/repository/page_text_repository.dart';
import 'package:foxy/repository/point_of_interest_repository.dart';
import 'package:foxy/repository/player_create_info_action_repository.dart';
import 'package:foxy/repository/player_create_info_cast_spell_repository.dart';
import 'package:foxy/repository/player_create_info_item_repository.dart';
import 'package:foxy/repository/player_create_info_repository.dart';
import 'package:foxy/repository/player_create_info_skill_repository.dart';
import 'package:foxy/repository/player_create_info_spell_custom_repository.dart';
import 'package:foxy/repository/quest_faction_reward_repository.dart';
import 'package:foxy/repository/quest_info_repository.dart';
import 'package:foxy/repository/quest_offer_reward_locale_repository.dart';
import 'package:foxy/repository/quest_offer_reward_repository.dart';
import 'package:foxy/repository/quest_request_items_locale_repository.dart';
import 'package:foxy/repository/quest_request_items_repository.dart';
import 'package:foxy/repository/quest_sort_repository.dart';
import 'package:foxy/repository/quest_template_addon_repository.dart';
import 'package:foxy/repository/quest_template_locale_repository.dart';
import 'package:foxy/repository/quest_template_repository.dart';
import 'package:foxy/repository/scaling_stat_distribution_repository.dart';
import 'package:foxy/repository/scaling_stat_value_repository.dart';
import 'package:foxy/repository/setting_repository.dart';
import 'package:foxy/repository/smart_script_repository.dart';
import 'package:foxy/repository/spell_area_repository.dart';
import 'package:foxy/repository/spell_bonus_data_repository.dart';
import 'package:foxy/repository/spell_custom_attr_repository.dart';
import 'package:foxy/repository/spell_duration_repository.dart';
import 'package:foxy/repository/spell_focus_object_repository.dart';
import 'package:foxy/repository/spell_group_repository.dart';
import 'package:foxy/repository/spell_icon_repository.dart';
import 'package:foxy/repository/spell_item_enchantment_condition_repository.dart';
import 'package:foxy/repository/spell_item_enchantment_repository.dart';
import 'package:foxy/repository/spell_linked_spell_repository.dart';
import 'package:foxy/repository/spell_loot_template_repository.dart';
import 'package:foxy/repository/spell_range_repository.dart';
import 'package:foxy/repository/spell_rank_repository.dart';
import 'package:foxy/repository/spell_repository.dart';
import 'package:foxy/repository/skill_line_repository.dart';
import 'package:foxy/repository/sound_ambience_repository.dart';
import 'package:foxy/repository/sound_provider_preferences_repository.dart';
import 'package:foxy/repository/totem_category_repository.dart';
import 'package:foxy/repository/talent_repository.dart';
import 'package:foxy/repository/talent_tab_repository.dart';
import 'package:foxy/repository/taxi_path_repository.dart';
import 'package:foxy/repository/vehicle_repository.dart';
import 'package:foxy/repository/zone_intro_music_repository.dart';
import 'package:foxy/repository/zone_music_repository.dart';
import 'package:foxy/repository/version_repository.dart';
import 'package:foxy/repository/waypoint_data_repository.dart';
import 'package:foxy/router/router_facade.dart';
import 'package:foxy/event/event_bus.dart';
import 'package:foxy/infrastructure/config/config_util.dart';
import 'package:foxy/infrastructure/dbc/dbc_export_registry.dart';
import 'package:foxy/infrastructure/dbc/dbc_sync_util.dart';
import 'package:get_it/get_it.dart';

class DI {
  static final _instance = GetIt.instance;

  static void ensureInitialized() {
    _instance.registerSingleton(RouterFacade());
    _instance.registerSingleton(FoxyViewModel());
    _instance.registerSingleton(EventBus());
    _registerRepositories();
    _registerUtils();
    _registerViewModels();
  }

  static void _registerRepositories() {
    _instance.registerLazySingleton(() => AchievementRepository());
    _instance.registerLazySingleton(() => AchievementCategoryRepository());
    _instance.registerLazySingleton(() => AchievementCriteriaRepository());
    _instance.registerLazySingleton(() => ActivityLogRepository());
    _instance.registerLazySingleton(() => AreaTableRepository());
    _instance.registerLazySingleton(() => BroadcastTextRepository());
    _instance.registerLazySingleton(() => CharTitleRepository());
    _instance.registerLazySingleton(() => CinematicSequenceRepository());
    _instance.registerLazySingleton(() => ConditionRepository());
    _instance.registerLazySingleton(() => CreatureDisplayInfoRepository());
    _instance.registerLazySingleton(() => CreatureModelDataRepository());
    _instance.registerLazySingleton(() => CreatureEquipTemplateRepository());
    _instance.registerLazySingleton(() => CreatureModelInfoRepository());
    _instance.registerLazySingleton(() => CreatureMovementInfoRepository());
    _instance.registerLazySingleton(() => CreatureImmunityRepository());
    _instance.registerLazySingleton(() => CreatureOnKillReputationRepository());
    _instance.registerLazySingleton(() => CreatureQuestEnderRepository());
    _instance.registerLazySingleton(() => CreatureQuestItemRepository());
    _instance.registerLazySingleton(() => CreatureQuestStarterRepository());
    _instance.registerLazySingleton(() => CreatureSpellDataRepository());
    _instance.registerLazySingleton(() => CreatureTemplateAddonRepository());
    _instance.registerLazySingleton(() => CreatureTemplateLocaleRepository());
    _instance.registerLazySingleton(() => CreatureTemplateRepository());
    _instance.registerLazySingleton(
      () => CreatureTemplateResistanceRepository(),
    );
    _instance.registerLazySingleton(() => CreatureTemplateSpellRepository());
    _instance.registerLazySingleton(() => CreatureDefaultTrainerRepository());
    _instance.registerLazySingleton(() => CurrencyTypeRepository());
    _instance.registerLazySingleton(() => CurrencyCategoryRepository());
    _instance.registerLazySingleton(() => DestructibleModelDataRepository());
    _instance.registerLazySingleton(() => DbcFactionRepository());
    _instance.registerLazySingleton(() => DbcFactionTemplateRepository());
    _instance.registerLazySingleton(() => DbcEmoteRepository());
    _instance.registerLazySingleton(() => DbcItemRepository());
    _instance.registerLazySingleton(() => EmoteTextDataRepository());
    _instance.registerLazySingleton(() => EmoteTextRepository());
    _instance.registerLazySingleton(() => FeatureRepository());
    _instance.registerLazySingleton(() => GameObjectArtKitRepository());
    _instance.registerLazySingleton(() => GameObjectDisplayInfoRepository());
    _instance.registerLazySingleton(() => GameObjectQuestEnderRepository());
    _instance.registerLazySingleton(() => GameObjectQuestItemRepository());
    _instance.registerLazySingleton(() => GameObjectQuestStarterRepository());
    _instance.registerLazySingleton(() => GameObjectTemplateAddonRepository());
    _instance.registerLazySingleton(() => GameObjectTemplateLocaleRepository());
    _instance.registerLazySingleton(() => GameObjectTemplateRepository());
    _instance.registerLazySingleton(() => GemPropertyRepository());
    _instance.registerLazySingleton(() => GlyphPropertyRepository());
    _instance.registerLazySingleton(() => GossipMenuOptionLocaleRepository());
    _instance.registerLazySingleton(() => GossipMenuOptionRepository());
    _instance.registerLazySingleton(() => GossipMenuRepository());
    _instance.registerLazySingleton(() => HolidayRepository());
    _instance.registerLazySingleton(() => ItemDisplayInfoRepository());
    _instance.registerLazySingleton(() => ItemBagFamilyRepository());
    _instance.registerLazySingleton(() => ItemEnchantmentTemplateRepository());
    _instance.registerLazySingleton(() => ItemExtendedCostRepository());
    _instance.registerLazySingleton(() => ItemPurchaseGroupRepository());
    _instance.registerLazySingleton(() => ItemLimitCategoryRepository());
    _instance.registerLazySingleton(() => ItemRandomPropertiesRepository());
    _instance.registerLazySingleton(() => ItemRandomSuffixRepository());
    _instance.registerLazySingleton(() => ItemSetRepository());
    _instance.registerLazySingleton(() => ItemVisualEffectRepository());
    _instance.registerLazySingleton(() => ItemVisualsRepository());
    _instance.registerLazySingleton(() => ItemTemplateLocaleRepository());
    _instance.registerLazySingleton(() => ItemTemplateRepository());
    _instance.registerLazySingleton(() => LockRepository());
    _instance.registerLazySingleton(() => LightRepository());
    _instance.registerLazySingleton(() => LiquidTypeRepository());
    _instance.registerLazySingleton(() => MapInfoRepository());
    _instance.registerLazySingleton(() => MailTemplateRepository());
    _instance.registerLazySingleton(() => NpcTextLocaleRepository());
    _instance.registerLazySingleton(() => NpcTextRepository());
    _instance.registerLazySingleton(() => NpcTrainerRepository());
    _instance.registerLazySingleton(() => NpcVendorRepository());
    _instance.registerLazySingleton(() => PageTextLocaleRepository());
    _instance.registerLazySingleton(() => PageTextRepository());
    _instance.registerLazySingleton(() => PointOfInterestRepository());
    _instance.registerLazySingleton(() => PlayerCreateInfoRepository());
    _instance.registerLazySingleton(() => PlayerCreateInfoActionRepository());
    _instance.registerLazySingleton(
      () => PlayerCreateInfoCastSpellRepository(),
    );
    _instance.registerLazySingleton(() => PlayerCreateInfoItemRepository());
    _instance.registerLazySingleton(
      () => PlayerCreateInfoSpellCustomRepository(),
    );
    _instance.registerLazySingleton(() => PlayerCreateInfoSkillRepository());
    _instance.registerLazySingleton(() => QuestFactionRewardRepository());
    _instance.registerLazySingleton(() => QuestInfoRepository());
    _instance.registerLazySingleton(() => QuestOfferRewardLocaleRepository());
    _instance.registerLazySingleton(() => QuestOfferRewardRepository());
    _instance.registerLazySingleton(() => QuestRequestItemsLocaleRepository());
    _instance.registerLazySingleton(() => QuestRequestItemsRepository());
    _instance.registerLazySingleton(() => QuestSortRepository());
    _instance.registerLazySingleton(() => QuestTemplateAddonRepository());
    _instance.registerLazySingleton(() => QuestTemplateLocaleRepository());
    _instance.registerLazySingleton(() => QuestTemplateRepository());
    _instance.registerLazySingleton(() => ScalingStatDistributionRepository());
    _instance.registerLazySingleton(() => ScalingStatValueRepository());
    _instance.registerLazySingleton(() => SettingRepository());
    _instance.registerLazySingleton(() => SmartScriptRepository());
    _instance.registerLazySingleton(() => SpellAreaRepository());
    _instance.registerLazySingleton(() => SpellBonusDataRepository());
    _instance.registerLazySingleton(() => SpellCustomAttrRepository());
    _instance.registerLazySingleton(() => SpellDurationRepository());
    _instance.registerLazySingleton(() => SpellFocusObjectRepository());
    _instance.registerLazySingleton(() => SpellGroupRepository());
    _instance.registerLazySingleton(() => SpellIconRepository());
    _instance.registerLazySingleton(
      () => SpellItemEnchantmentConditionRepository(),
    );
    _instance.registerLazySingleton(() => SpellItemEnchantmentRepository());
    _instance.registerLazySingleton(() => SpellLinkedSpellRepository());
    _instance.registerLazySingleton(() => SpellLootTemplateRepository());
    _instance.registerLazySingleton(() => SpellRangeRepository());
    _instance.registerLazySingleton(() => SpellRankRepository());
    _instance.registerLazySingleton(() => SpellRepository());
    _instance.registerLazySingleton(() => SkillLineRepository());
    _instance.registerLazySingleton(() => SoundAmbienceRepository());
    _instance.registerLazySingleton(() => SoundProviderPreferencesRepository());
    _instance.registerLazySingleton(() => TotemCategoryRepository());
    _instance.registerLazySingleton(() => TalentRepository());
    _instance.registerLazySingleton(() => TalentTabRepository());
    _instance.registerLazySingleton(() => TaxiPathRepository());
    _instance.registerLazySingleton(() => VehicleRepository());
    _instance.registerLazySingleton(() => ZoneIntroMusicRepository());
    _instance.registerLazySingleton(() => ZoneMusicRepository());
    _instance.registerLazySingleton(() => VersionRepository());
    _instance.registerLazySingleton(() => WaypointDataRepository());
  }

  static void _registerUtils() {
    _instance.registerLazySingleton(() => ConfigUtil());
    _instance.registerLazySingleton(() => DbcSyncUtil());
    _instance.registerLazySingleton(() => DbcExportRegistry());
  }

  static void _registerViewModels() {
    _instance.registerSingleton(ScaffoldViewModel());
    _instance.registerFactory(() => BootstrapViewModel());
    _instance.registerFactory(() => DashboardViewModel());
    _instance.registerFactory(() => MoreViewModel());
    _instance.registerFactory(() => CreatureTemplateListViewModel());
    _instance.registerFactory(() => CreatureTemplateDetailViewModel());
    _instance.registerFactory(() => CreatureTemplateAddonViewModel());
    _instance.registerFactory(() => CreatureOnKillReputationViewModel());
    _instance.registerFactory(() => CreatureEquipTemplateViewModel());
    _instance.registerFactory(() => CreatureQuestItemViewModel());
    _instance.registerFactory(() => CreatureTemplateResistanceViewModel());
    _instance.registerFactory(() => CreatureTemplateSpellViewModel());
    _instance.registerFactory(() => CreatureLootTemplateViewModel());
    _instance.registerFactory(() => NpcTrainerViewModel());
    _instance.registerFactory(() => NpcVendorViewModel());
    _instance.registerFactory(() => PickpocketingLootTemplateViewModel());
    _instance.registerFactory(() => SkinningLootTemplateViewModel());
    _instance.registerFactory(() => GameObjectTemplateListViewModel());
    _instance.registerFactory(() => GameObjectTemplateDetailViewModel());
    _instance.registerFactory(() => GameObjectTemplateAddonViewModel());
    _instance.registerFactory(() => GameObjectQuestItemViewModel());
    _instance.registerFactory(() => GameObjectLootTemplateViewModel());
    _instance.registerFactory(() => ItemTemplateListViewModel());
    _instance.registerFactory(() => ItemTemplateDetailViewModel());
    _instance.registerFactory(() => ItemLootTemplateViewModel());
    _instance.registerFactory(() => DisenchantLootTemplateViewModel());
    _instance.registerFactory(() => ProspectingLootTemplateViewModel());
    _instance.registerFactory(() => MillingLootTemplateViewModel());
    _instance.registerFactory(() => ItemEnchantmentTemplateViewModel());
    _instance.registerFactory(() => GossipMenuListViewModel());
    _instance.registerFactory(() => QuestTemplateListViewModel());
    _instance.registerFactory(() => QuestTemplateDetailViewModel());
    _instance.registerFactory(() => QuestTemplateAddonViewModel());
    _instance.registerFactory(() => QuestRequestItemsViewModel());
    _instance.registerFactory(() => QuestOfferRewardViewModel());
    _instance.registerFactory(() => CreatureQuestStarterViewModel());
    _instance.registerFactory(() => CreatureQuestEnderViewModel());
    _instance.registerFactory(() => GameObjectQuestStarterViewModel());
    _instance.registerFactory(() => GameObjectQuestEnderViewModel());
    _instance.registerFactory(() => GossipMenuDetailViewModel());
    _instance.registerFactory(() => NpcTextViewModel());
    _instance.registerFactory(() => GossipMenuOptionViewModel());
    _instance.registerFactory(() => SettingViewModel());
    _instance.registerFactory(() => SmartScriptListViewModel());
    _instance.registerFactory(() => SmartScriptDetailViewModel());
    _instance.registerFactory(() => SpellListViewModel());
    _instance.registerFactory(() => SpellDetailViewModel());
    _instance.registerFactory(() => SpellBonusDataViewModel());
    _instance.registerFactory(() => SpellCustomAttrViewModel());
    _instance.registerFactory(() => SpellAreaViewModel());
    _instance.registerFactory(() => SpellGroupViewModel());
    _instance.registerFactory(() => SpellLinkedSpellViewModel());
    _instance.registerFactory(() => SpellRankViewModel());
    _instance.registerFactory(() => SpellLootTemplateViewModel());
    _instance.registerFactory(() => ReferenceLootTemplateListViewModel());
    _instance.registerFactory(() => ReferenceLootTemplateDetailViewModel());
    _instance.registerFactory(() => PageTextListViewModel());
    _instance.registerFactory(() => PageTextDetailViewModel());
    _instance.registerFactory(() => PageTextLocaleViewModel());
    _instance.registerFactory(() => ConditionListViewModel());
    _instance.registerFactory(() => ConditionDetailViewModel());
    _instance.registerFactory(() => PlayerCreateInfoListViewModel());
    _instance.registerFactory(() => PlayerCreateInfoDetailViewModel());
    _instance.registerFactory(() => PlayerCreateInfoActionViewModel());
    _instance.registerFactory(() => PlayerCreateInfoCastSpellViewModel());
    _instance.registerFactory(() => PlayerCreateInfoItemViewModel());
    _instance.registerFactory(() => PlayerCreateInfoSpellCustomViewModel());
    _instance.registerFactory(() => PlayerCreateInfoSkillViewModel());
    _instance.registerFactory(() => AreaTableListViewModel());
    _instance.registerFactory(() => AreaTableDetailViewModel());
    _instance.registerFactory(() => EmoteTextListViewModel());
    _instance.registerFactory(() => EmoteTextDetailViewModel());
    _instance.registerFactory(() => QuestFactionRewardListViewModel());
    _instance.registerFactory(() => QuestFactionRewardDetailViewModel());
    _instance.registerFactory(() => QuestSortListViewModel());
    _instance.registerFactory(() => QuestSortDetailViewModel());
    _instance.registerFactory(() => QuestInfoListViewModel());
    _instance.registerFactory(() => QuestInfoDetailViewModel());
    _instance.registerFactory(() => ItemExtendedCostListViewModel());
    _instance.registerFactory(() => ItemExtendedCostDetailViewModel());
    _instance.registerFactory(() => ScalingStatDistributionListViewModel());
    _instance.registerFactory(() => ScalingStatDistributionDetailViewModel());
    _instance.registerFactory(() => SpellItemEnchantmentListViewModel());
    _instance.registerFactory(() => SpellItemEnchantmentDetailViewModel());
    _instance.registerFactory(() => GemPropertyListViewModel());
    _instance.registerFactory(() => GemPropertyDetailViewModel());
    _instance.registerFactory(() => GlyphPropertyListViewModel());
    _instance.registerFactory(() => GlyphPropertyDetailViewModel());
    _instance.registerFactory(() => TalentListViewModel());
    _instance.registerFactory(() => TalentDetailViewModel());
    _instance.registerFactory(() => CurrencyTypeListViewModel());
    _instance.registerFactory(() => CurrencyTypeDetailViewModel());
    _instance.registerFactory(() => ScalingStatValueListViewModel());
    _instance.registerFactory(() => ScalingStatValueDetailViewModel());
    _instance.registerFactory(() => ItemSetListViewModel());
    _instance.registerFactory(() => ItemSetDetailViewModel());
    _instance.registerFactory(() => AchievementListViewModel());
    _instance.registerFactory(() => AchievementDetailViewModel());
  }
}
