/// Update service: fetches the update manifest, compares versions,
/// downloads with verification (SHA-256), and extracts.
///
/// Distribution is a portable zip (no installer): the release pipeline zips
/// the Release folder and attaches it to the GitHub Release alongside
/// `latest.yaml`; this service fetches the manifest from
/// `releases/latest/download/latest.yaml` (302 following handled by the
/// http package), downloads and verifies the zip, extracts it into
/// `.update_tmp/` under the app directory, and a helper program
/// (`tool/updater/updater_main.dart`) performs the file swap after the main
/// process exits.
library;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:archive/archive_io.dart';
import 'package:crypto/crypto.dart';
import 'package:foxy/infrastructure/errors/foxy_exceptions.dart';
import 'package:foxy/infrastructure/update/update_swapper.dart';
import 'package:http/http.dart' as http;
import 'package:package_info_plus/package_info_plus.dart';
import 'package:path/path.dart' as p;
import 'package:pub_semver/pub_semver.dart';
import 'package:yaml/yaml.dart';

/// Update manifest `latest.yaml`: generated by the release pipeline; YAML
/// structure in
/// `tool/release/make_update_manifest.dart`。
class UpdateManifestInfo {
  const UpdateManifestInfo({
    required this.version,
    required this.buildNumber,
    required this.zipUrl,
    required this.sizeBytes,
    required this.sha256,
    required this.notes,
    this.isPrerelease = false,
  });

  /// New version (matches pubspec's `version`, without the build).
  final String version;

  /// New version build number (matches pubspec's `+N`).
  final String buildNumber;

  /// Whether this is a prerelease (test) version: the release pipeline
  /// writes this into the manifest when the release tag carries a
  /// `-alpha`/`-beta`/`-rc` suffix, and the app skips such versions so they
  /// are never pushed to regular users.
  final bool isPrerelease;

  /// zip download URL (points at the versioned Release asset).
  final Uri zipUrl;

  /// zip size in bytes.
  final int sizeBytes;

  /// zip SHA-256 (lowercase hex).
  final String sha256;

  /// Update notes in Chinese.
  final String notes;

  /// Built from the release-entry Map parsed out of YAML/JSON.
  ///
  /// Missing or mistyped fields throw [FormatException]; `isPrerelease`
  /// may be omitted (for backward compatibility with old manifests) and
  /// defaults to a stable release.
  factory UpdateManifestInfo.fromMap(Map<dynamic, dynamic> map) {
    final version = map['version'];
    final buildNumber = map['buildNumber'];
    final zipUrl = map['zipUrl'];
    final sizeBytes = map['sizeBytes'];
    final sha256 = map['sha256'];
    final notes = map['notes'];
    final isPrerelease = map['isPrerelease'];
    if (version is! String ||
        buildNumber is! String ||
        zipUrl is! String ||
        sizeBytes is! int ||
        sha256 is! String ||
        notes is! String ||
        (isPrerelease != null && isPrerelease is! bool)) {
      throw const FormatException('update manifest release invalid');
    }
    return UpdateManifestInfo(
      version: version,
      buildNumber: buildNumber,
      isPrerelease: isPrerelease == true,
      zipUrl: Uri.parse(zipUrl),
      sizeBytes: sizeBytes,
      sha256: sha256.toLowerCase(),
      notes: notes,
    );
  }
}

/// Update-check result.
sealed class UpdateCheckResult {
  const UpdateCheckResult();
}

/// A newer updatable version was found.
final class UpdateAvailable extends UpdateCheckResult {
  const UpdateAvailable(this.update);

  final UpdateManifestInfo update;
}

/// Already on the latest version.
final class UpToDate extends UpdateCheckResult {
  const UpToDate();
}

/// Download-cancellation token.
class UpdateCancelToken {
  bool _canceled = false;

  /// Whether cancellation was requested.
  bool get isCanceled => _canceled;

  /// Requests cancellation (the download stops at the next data chunk and
  /// cleans up the partial file).
  void cancel() => _canceled = true;
}

class UpdateService {
  UpdateService({http.Client? client, String? manifestUrl})
    : _client = client ?? http.Client(),
      _manifestUrl = Uri.parse(manifestUrl ?? defaultManifestUrl);

  /// Manifest URL: a GitHub Releases asset; `latest` always points at the
  /// newest release.
  static const defaultManifestUrl =
      'https://github.com/CalsRanna/foxy/releases/latest/download/latest.yaml';

  /// Expected manifest appId (written by the release pipeline; guards
  /// against a misconfigured manifest URL).
  static const expectedAppId = 'com.calsranna.foxy';

  static const _requestTimeout = Duration(seconds: 30);

  /// Idle timeout between consecutive body chunks, so a stalled connection
  /// never hangs the download forever.
  static const _chunkTimeout = Duration(seconds: 30);

  final http.Client _client;
  final Uri _manifestUrl;

  /// Checks for a new version.
  ///
  /// [installedVersion] / [installedBuildNumber] are injectable for tests
  /// and default to `package_info_plus`. Failures throw [UpdateException].
  Future<UpdateCheckResult> checkForUpdates({
    String? installedVersion,
    String? installedBuildNumber,
  }) async {
    try {
      final response = await _client.get(_manifestUrl).timeout(_requestTimeout);
      if (response.statusCode != 200) {
        throw UpdateException(
          UpdateErrorKind.network,
          'Update manifest fetch failed: HTTP ${response.statusCode}',
        );
      }
      // Decode the body as UTF-8 explicitly: `response.body` falls back to
      // latin-1 when the Content-Type header carries no charset (GitHub
      // serves release assets as application/octet-stream), which garbles
      // the Chinese notes.
      final updates = _parseManifest(utf8.decode(response.bodyBytes));

      String currentVersion;
      String currentBuild;
      if (installedVersion != null) {
        currentVersion = installedVersion;
        currentBuild = installedBuildNumber ?? '';
      } else {
        final info = await PackageInfo.fromPlatform();
        currentVersion = info.version;
        currentBuild = info.buildNumber;
      }

      // Newest-first scan: prerelease entries (test versions) are skipped so
      // they never shadow a stable release, and the first stable release
      // newer than the installed version wins.
      for (final update in updates) {
        if (update.isPrerelease) {
          continue;
        }
        if (_isNewer(update, currentVersion, currentBuild)) {
          return UpdateAvailable(update);
        }
      }
      return const UpToDate();
    } on UpdateException {
      rethrow;
    } on TimeoutException catch (error) {
      throw UpdateException(
        UpdateErrorKind.network,
        'Update manifest fetch timed out: $error',
      );
    } on SocketException catch (error) {
      throw UpdateException(
        UpdateErrorKind.network,
        'Update manifest fetch failed: $error',
      );
    } on http.ClientException catch (error) {
      throw UpdateException(
        UpdateErrorKind.network,
        'Update manifest fetch failed: $error',
      );
    } on FormatException catch (error) {
      throw UpdateException(
        UpdateErrorKind.invalidManifest,
        'Update manifest parse failed: $error',
      );
    }
  }

  /// Downloads, verifies and extracts the new version into `.update_tmp/`
  /// under [appDir].
  ///
  /// [onProgress] receives 0..1 download progress; returns the actual
  /// payload root (if the zip has a single top-level directory — the
  /// folder itself was zipped — that directory is returned, otherwise
  /// `.update_tmp/`). On failure, partial files are cleaned up and
  /// [UpdateException] is thrown.
  Future<Directory> prepareUpdate(
    UpdateManifestInfo update, {
    required Directory appDir,
    void Function(double fraction)? onProgress,
    UpdateCancelToken? cancelToken,
  }) async {
    final zipFile = await downloadZip(
      update,
      onProgress: onProgress,
      cancelToken: cancelToken,
    );
    try {
      final updateDir = Directory(
        p.join(appDir.path, UpdateSwapper.tempDirName),
      );
      if (await updateDir.exists()) {
        await updateDir.delete(recursive: true);
      }
      await updateDir.create(recursive: true);
      await _extractZip(zipFile, updateDir);
      return resolvePayloadRoot(updateDir);
    } on UpdateException {
      rethrow;
    } on FileSystemException catch (error) {
      throw UpdateException(
        UpdateErrorKind.fileSystem,
        'Update extract failed: $error',
      );
    } finally {
      await _deleteQuietly(zipFile);
    }
  }

  /// Downloads the zip into the system temp directory and verifies its
  /// size and SHA-256.
  ///
  /// [onProgress] receives 0..1 download progress; on verification failure
  /// the partial file is deleted and [UpdateException] is thrown. Returns
  /// the verified zip file.
  Future<File> downloadZip(
    UpdateManifestInfo update, {
    void Function(double fraction)? onProgress,
    UpdateCancelToken? cancelToken,
  }) async {
    final file = File(
      p.join(Directory.systemTemp.path, 'foxy_update_${update.version}.zip'),
    );
    IOSink? sink;
    try {
      final request = http.Request('GET', update.zipUrl);
      final response = await _client.send(request).timeout(_requestTimeout);
      if (response.statusCode != 200) {
        throw UpdateException(
          UpdateErrorKind.network,
          'Update zip download failed: HTTP ${response.statusCode}',
        );
      }
      final total = response.contentLength;
      sink = file.openWrite();
      var downloaded = 0;
      // Per-chunk idle timeout on the body stream: a header-only timeout is
      // not enough — if the connection stalls mid-stream the download would
      // hang forever and the cancel token would never see the next chunk.
      await for (final chunk in response.stream.timeout(_chunkTimeout)) {
        if (cancelToken?.isCanceled ?? false) {
          throw const UpdateException(
            UpdateErrorKind.canceled,
            'Update download canceled by user',
          );
        }
        sink.add(chunk);
        downloaded += chunk.length;
        if (total != null && total > 0) {
          onProgress?.call(downloaded / total);
        }
      }
      await sink.flush();
      await sink.close();
      sink = null;

      final actualSize = await file.length();
      if (actualSize != update.sizeBytes) {
        await _deleteQuietly(file);
        throw UpdateException(
          UpdateErrorKind.verification,
          'Update zip size mismatch: expected ${update.sizeBytes}, got $actualSize',
        );
      }
      final digest = await sha256.bind(file.openRead()).first;
      final hex = digest.bytes
          .map((byte) => byte.toRadixString(16).padLeft(2, '0'))
          .join();
      if (hex != update.sha256) {
        await _deleteQuietly(file);
        throw const UpdateException(
          UpdateErrorKind.verification,
          'Update zip SHA-256 mismatch',
        );
      }
      return file;
    } on UpdateException {
      await _disposeSink(sink);
      await _deleteQuietly(file);
      rethrow;
    } on TimeoutException catch (error) {
      await _disposeSink(sink);
      await _deleteQuietly(file);
      throw UpdateException(
        UpdateErrorKind.network,
        'Update zip download timed out: $error',
      );
    } on SocketException catch (error) {
      await _disposeSink(sink);
      await _deleteQuietly(file);
      throw UpdateException(
        UpdateErrorKind.network,
        'Update zip download failed: $error',
      );
    } on http.ClientException catch (error) {
      await _disposeSink(sink);
      await _deleteQuietly(file);
      throw UpdateException(
        UpdateErrorKind.network,
        'Update zip download failed: $error',
      );
    } on FileSystemException catch (error) {
      await _disposeSink(sink);
      await _deleteQuietly(file);
      throw UpdateException(
        UpdateErrorKind.fileSystem,
        'Update zip write failed: $error',
      );
    }
  }

  /// Extracts [zipFile] into [targetDir] (zip-slip protection is built
  /// into the archive package's [extractArchiveToDisk]).
  static Future<void> _extractZip(File zipFile, Directory targetDir) async {
    final archive = ZipDecoder().decodeBytes(await zipFile.readAsBytes());
    // Defensive cap against malformed/malicious zips: real update packages
    // have only dozens of files and tens of MB, so the cap sits far above
    // normal values and only blocks obvious anomalies (guarding against
    // memory spikes during extraction).
    if (archive.length > 2000) {
      throw UpdateException(
        UpdateErrorKind.fileSystem,
        'Update zip contains too many entries: ${archive.length}',
      );
    }
    final totalBytes = archive.fold<int>(0, (sum, file) => sum + file.size);
    if (totalBytes > 2 * 1024 * 1024 * 1024) {
      throw UpdateException(
        UpdateErrorKind.fileSystem,
        'Update zip is too large: $totalBytes bytes',
      );
    }
    await extractArchiveToDisk(archive, targetDir.path);
  }

  /// If the extracted output has a single top-level directory (the release
  /// zipped the folder itself), that directory is returned as the payload
  /// root; otherwise [updateDir] itself is returned.
  static Directory resolvePayloadRoot(Directory updateDir) {
    final entities = updateDir.listSync(followLinks: false);
    final dirs = entities.whereType<Directory>().toList();
    final hasRootFile = entities.any((entity) => entity is File);
    if (!hasRootFile && dirs.length == 1) {
      return dirs.single;
    }
    return updateDir;
  }

  /// Whether [update] is higher than the installed version: major versions
  /// compare first, with the build number as tiebreaker.
  ///
  /// Prerelease filtering happens in [checkForUpdates], which skips entries
  /// marked `isPrerelease` (test versions are never pushed to regular
  /// users); this method only compares versions.
  static bool _isNewer(
    UpdateManifestInfo update,
    String installedVersion,
    String installedBuildNumber,
  ) {
    final current = _tryParseVersion(installedVersion);
    final latest = _tryParseVersion(update.version);
    if (current == null || latest == null) {
      // When a version cannot be parsed, fall back to build-number
      // comparison (an update is only possible if both are parseable).
      final currentBuild = int.tryParse(installedBuildNumber);
      final latestBuild = int.tryParse(update.buildNumber);
      return latestBuild != null &&
          currentBuild != null &&
          latestBuild > currentBuild;
    }
    if (latest > current) return true;
    if (latest == current) {
      final currentBuild = int.tryParse(installedBuildNumber) ?? 0;
      final latestBuild = int.tryParse(update.buildNumber) ?? 0;
      return latestBuild > currentBuild;
    }
    return false;
  }

  /// Parses the `latest.yaml` manifest: validates the appId and returns all
  /// release entries newest-first.
  ///
  /// Structure in `tool/release/make_update_manifest.dart`; the release
  /// pipeline guarantees the newest version is first.
  static List<UpdateManifestInfo> _parseManifest(String body) {
    final decoded = loadYaml(body);
    if (decoded is! Map) {
      throw const UpdateException(
        UpdateErrorKind.invalidManifest,
        'Update manifest is not a YAML mapping',
      );
    }
    if (decoded['appId'] != expectedAppId) {
      throw UpdateException(
        UpdateErrorKind.invalidManifest,
        'Update manifest appId mismatch: ${decoded['appId']}',
      );
    }
    final releases = decoded['releases'];
    if (releases is! List || releases.isEmpty) {
      throw const UpdateException(
        UpdateErrorKind.invalidManifest,
        'Update manifest has no releases',
      );
    }
    return [for (final release in releases) _parseRelease(release)];
  }

  /// Parses one release entry; missing or mistyped fields throw
  /// [FormatException] wrapped as an invalid-manifest [UpdateException].
  static UpdateManifestInfo _parseRelease(dynamic release) {
    if (release is! Map) {
      throw const UpdateException(
        UpdateErrorKind.invalidManifest,
        'Update manifest release is not a mapping',
      );
    }
    try {
      return UpdateManifestInfo.fromMap(release);
    } on FormatException catch (error) {
      throw UpdateException(
        UpdateErrorKind.invalidManifest,
        'Update manifest release invalid: $error',
      );
    }
  }

  /// Parses a version number; returns null on failure.
  static Version? _tryParseVersion(String text) {
    try {
      return Version.parse(text);
    } on FormatException {
      return null;
    }
  }

  /// Closes the download stream, ignoring close errors (partial files are
  /// deleted on the [UpdateException] path).
  static Future<void> _disposeSink(IOSink? sink) async {
    if (sink == null) return;
    try {
      await sink.close();
    } catch (_) {
      // A failed close does not affect the subsequent cleanup.
    }
  }

  static Future<void> _deleteQuietly(File file) async {
    try {
      if (await file.exists()) {
        await file.delete();
      }
    } catch (_) {
      // Cleanup failures are absorbed by the system temp directory.
    }
  }
}
