import Vue from "vue";
import {
  Container,
  Main,
  Header,
  Aside,
  Row,
  Col,
  Button,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  MenuItem,
  MenuItemGroup,
  Submenu,
  Table,
  TableColumn,
  Card,
  Input,
  InputNumber,
  Form,
  FormItem,
  Breadcrumb,
  BreadcrumbItem,
  Tabs,
  TabPane,
  Loading,
  Pagination,
  Tooltip,
  Select,
  Option,
  Avatar,
  Switch,
  Tag,
  Dialog,
  Checkbox,
  Image,
  // Notification
} from "element-ui";

Vue.use(Button);
Vue.use(Container);
Vue.use(Main);
Vue.use(Header);
Vue.use(Aside);
Vue.use(Row);
Vue.use(Col);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(MenuItemGroup);
Vue.use(Submenu);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Card);
Vue.use(Input);
Vue.use(InputNumber);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Loading);
Vue.use(Pagination);
Vue.use(Tooltip);
Vue.use(Select);
Vue.use(Option);
Vue.use(Avatar);
Vue.use(Switch);
Vue.use(Tag);
Vue.use(Dialog);
Vue.use(Checkbox);
Vue.use(Image);
// Vue.use(Notification);
