import 'package:foxy/database/migration_runner.dart';
import 'package:laconic/laconic.dart';

class Migration202604270000 implements Migration {
  @override
  String get name => 'migration_202604270000';

  @override
  Future<void> migrate(Laconic laconic) async {
    await laconic.table('foxy.features').insert([
      {
        'name': '关联掉落',
        'description': '定义参考掉落模板，用于配置生物或物体的掉落列表，包括掉落物品、几率、数量范围和任务要求。',
        'icon': 'list',
        'router_menu': 'referenceLootTemplate',
        'category': 'database',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 8,
      },
      {
        'name': '页面文本',
        'description': '管理游戏内可配置的界面文本内容，如书籍、信件、告示板等页面文本，支持多语言本地化。',
        'icon': 'bookOpen',
        'router_menu': 'pageText',
        'category': 'database',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 9,
      },
      {
        'name': '条件',
        'description': '定义脚本、掉落、事件等游戏逻辑的条件检查规则，控制游戏行为的触发机制。',
        'icon': 'listFilter',
        'router_menu': 'condition',
        'category': 'database',
        'is_pinned': 0,
        'is_favorite': 1,
        'sort_order': 10,
      },
      {
        'name': '出生信息',
        'description': '配置玩家新角色创建时的初始信息，按种族和职业区分出生装备、技能和动作按钮。',
        'icon': 'userPlus',
        'router_menu': 'playerCreateInfo',
        'category': 'database',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 11,
      },
      {
        'name': '区域',
        'description': '管理游戏世界中的区域定义，配置区域名称、父区域关系和探索标识等地理信息。',
        'icon': 'map',
        'router_menu': 'areaTable',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 12,
      },
      {
        'name': '表情文本',
        'description': '定义游戏内各表情动作对应的文本消息输出，如/train、/dance等表情命令的文本内容。',
        'icon': 'laugh',
        'router_menu': 'emoteText',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 13,
      },
      {
        'name': '任务声望',
        'description': '配置完成任务后给予玩家各阵营的声望奖励数值。',
        'icon': 'trophy',
        'router_menu': 'questFactionReward',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 14,
      },
      {
        'name': '任务排序',
        'description': '管理任务日志界面中的分类排序规则，定义各品质分类的显示名称。',
        'icon': 'arrowUpDown',
        'router_menu': 'questSort',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 15,
      },
      {
        'name': '任务信息',
        'description': '定义任务详情信息的描述文本，包括任务标题、目标摘要和完成日志提示等。',
        'icon': 'info',
        'router_menu': 'questInfo',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 16,
      },
      {
        'name': '扩展价格',
        'description': '定义物品的扩展购买成本，支持荣誉点数、竞技场点数、竞技场等级等非金币货币价格。',
        'icon': 'coins',
        'router_menu': 'itemExtendedCost',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 17,
      },
      {
        'name': '属性缩放分布',
        'description': '定义生物属性随等级动态缩放的分布规则，配置不同等级下各属性的增长比例。',
        'icon': 'trendingUp',
        'router_menu': 'scalingStatDistribution',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 18,
      },
      {
        'name': '法术附魔',
        'description': '管理物品附魔效果的定义，控制附魔的外观特效、属性加成和触发效果。',
        'icon': 'wand',
        'router_menu': 'spellItemEnchantment',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 19,
      },
      {
        'name': '宝石属性',
        'description': '定义宝石的镶嵌属性效果，配置不同颜色宝石对应镶嵌后提供的属性加成。',
        'icon': 'gem',
        'router_menu': 'gemProperty',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 20,
      },
      {
        'name': '雕文属性',
        'description': '管理雕文的属性配置，定义各职业雕文对特定技能的修改效果和增强能力。',
        'icon': 'triangle',
        'router_menu': 'glyphProperty',
        'category': 'dbc',
        'is_pinned': 0,
        'is_favorite': 0,
        'sort_order': 21,
      },
    ]);
  }
}
